<script type="text/javascript">
    function togglePopup(form, id, val, note) {
        $('#popup-overlay').toggle();
        $('.'+form).toggle()
        $(id).val(val);
        if (form == 'add-note') {
            $('#'+form+' .Notes').val(note)
        } else {
            $('#'+form+' .Notes').val($('#hidden-note-'+val).val());
        }
    }

    function manageNote(form, action) {
        if (jQuery.trim($(form+' .Notes').val()) == '') {
            alert("Please enter the volunteer's notes")
        } else {
            $.post('/dashboard/'+action, $(form).serialize(), function(data) {
                alert(data);
                window.location.reload(true);
            })
        }
        return false;
    }

    function deleteNote(id) {
        if (confirm("Are you sure you want to delete this donation note?") == true) {
            $.post('/dashboard/deletenote', {DonationNoteId: id}, function(data) {
                alert(data);
                window.location.reload(true);
            })
        } else {
            return false;
        }
    }

    function resendReceipt(PDI) {
        $.post('/dashboard/reemailreceipt', {ProjectDonationId: PDI}, function(data) {
            alert(data);
            $('#resend-'+PDI).toggle();
            $('#sent-'+PDI).toggle();
        })
    }
<?php
$manual = in_array(
                $this->userNew->id,
                Zend_Registry::get('configuration')->user->manualDonation->toArray()
          );
$manual = ($manual && $this->isAdmin);
if ($manual) { ?>
    function manualEntry() {
        if (!isFloat($('#DonationAmount').val())) {
            alert('Please enter a valid donation amount.');
            return false;
        } else {
            $.post('/dashboard/manualentry', $('#manual-entry').serialize(), function(data) {
                alert(data);
                window.location.reload(true);
            });
        }
    }
<? } ?>
    function loadVolunteers(PID) {
        $('#VolunteerId').load('/dashboard/loadvolunteers', {ProjectId: PID});
    }

    function isFloat(value) {
        if(value == ""){
            return false;
        }
        value = value.replace(/,/, '.');
        if(parseFloat(value) != (value*1)) {
            return false;
        }
        return true;
    }

    function exportDonations(GID) {
        $.post('/reporting/export', {SiteId: GID, Type: 'Group'});
    }

    function filterByDate() {
        if ($('#FromDate').val() != '' && $('#ToDate').val() != '') {
            search_donation.submit();
        }
    }

    function showComment(id) {
        $.fancybox($("#"+id).html());
    }

    function editDestination(transactionId, volId) {
        $.fancybox($('#editDestinationFcyBx').html());
        if ($("#fancybox-content select>option[value='"+volId+"']").length > 0) {
            $("#fancybox-content select>option[value='"+volId+"']").attr('selected', true);
            $("#fancybox-content input#transactionId").val(transactionId);
            $("#fancybox-content span.transId").html(transactionId);
        } else {
            $("#fancybox-content div.errorMsg").show();
        }
        var formBox = $("#fancybox-content form#edit-dest");
        formBox.validate({
            onfocusout: function(element) { this.element(element); },
            submitHandler: function(form) {
                $.fancybox.showActivity();
                $('input.btnSubmit').hide();
                $.ajax({
                    url: '/dashboard/editdestination',
                    type: 'POST',
                    data: {
                        ProjectId:     '<?=$this->project->id?>',
                        VolunteerId:   $('#fancybox-content select#VolunteerId').val(),
                        TransactionId: transactionId
                    },
                    success: function(data) {
                        $.fancybox.hideActivity();
                        $.fancybox.close();
                        alert('Donation destintion has been successfully updated');
                        window.location.reload(true);
                    }
                });
            }
        });
    }

    $(function() {
        $('#FromDate').datepicker({ changeMonth: true, changeYear: true });
        $('#ToDate').datepicker({ changeMonth: true, changeYear: true });
<? if ($manual) { ?>
        $('.manualEntry').click(function() {
            $.fancybox($('#manualEntryFcyBx').html());

            var formBox = $("#fancybox-content form#manual-entry");
            formBox.validate({
                onfocusout: function(element) { this.element(element); },
                submitHandler: function(form) {
                    $.fancybox.showActivity();
                    $('input.btnSubmit').hide();
                    $.ajax({
                        url: '/dashboard/manualentry',
                        type: 'POST',
                        data: {
                            ProjectId:      '<?=$this->project->id?>',
                            VolunteerId:    $('#fancybox-content select#ManualVolunteerId').val(),
                            DonationAmount: $('#fancybox-content #ManualDonationAmount').val(),
                            Notes:          $('#fancybox-content #Notes').val(),
                            IsPrivate:      $('#fancybox-content #isPrivate:checked').val(),
                            PaidFees:       $('#fancybox-content #paidFees:checked').val()
                        },
                        success: function(data) {
                            if (data == 'success') {
                                $.fancybox.hideActivity();
                                $.fancybox.close();
                                alert('Manual donation has been successfully processed');
                                window.location.reload(true);
                            } else {
                                $.fancybox.hideActivity();
                                $('input.btnSubmit').show();
                            }
                        }
                    });
                }
            });
        });
<? } ?>
    })
</script>
<style>
    .popup-box { width: 600px; left: 30%; right: 30%; top:25%; position: fixed; z-index: 999999!important; background-color:#ffffff; border:5px solid #e5e5e5; padding:10px 0 20px 0; -moz-border-radius:5px; margin:auto }
    #popup-overlay {
        background: url(<?php echo $this->contentLocation ?>public/images/bg-overlay.png);
        height:100%;
        position:fixed;
        display:block;
        left:0;
        top:0;
        width:100%!important;
        z-index:998;
        display:none;
    }
    .right {
        float:right;
    }
    .hidden { display:none }
    #ui-datepicker-div { font-size:11px }
</style>
<div class="add-note popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <h2>Add Donation Note</h2>
    <form id="add-note" onsubmit="manageNote('#add-note', 'addnote'); return false;">
        <input id="ProjectDonationId" type="hidden" name="ProjectDonationId" value="" />
        <textarea cols="60" rows="3" name="Notes" class="Notes"></textarea><br>
        <input type="hidden" name="isPrivate" value="0">
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="togglePopup('add-note', '#ProjectDonationId', '', '')">Cancel</a>
        <input type="submit" class="btn btngreen" value="Submit" />&nbsp;
    </form>
</div>
<div class="edit-note popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <h2>Edit Donation Note</h2>
    <form id="edit-note" onsubmit="manageNote('#edit-note', 'editnote'); return false;">
        <input id="DonationNoteId" type="hidden" name="DonationNoteId" value=""/>
        <textarea cols="60" rows="3" name="Notes" class="Notes"></textarea><br>
        <input type="hidden" name="isPrivate" value="0">
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="togglePopup('edit-note', '#DonationNoteId', '', '')">Cancel</a>
        <input type="submit" class="btn btngreen" value="Submit" />&nbsp;
    </form>
</div>
<? if ($manual) { ?>
<div id="manualEntryFcyBx" style="display:none;">
    <h2>Manual Entry Tool</h2>
    <form id="manual-entry" method="post">
        <? if (count($this->project->volunteers) > 0) { ?>
        <strong>Volunteer/Fundraiser:</strong><br>
        <select id="ManualVolunteerId" name="ManualVolunteerId">
            <option value="">General Destination</option>
            <?php foreach($this->project->volunteers as $volunteer) { ?>
            <option value="<?php echo $volunteer->user->id ?>"><?php echo stripslashes($volunteer->user->fullName) ?></option>
            <?php } ?>
        </select>
        <? } else { ?>
        <input type="hidden" id="ManualVolunteerId" name="ManualVolunteerId" value="" />
        <? } ?>
        <div class="clear" style="margin-bottom:5px"></div>
        <strong>Amount:</strong><br>
        <input type="text" id="ManualDonationAmount" name="ManualDonationAmount" class="required" />
        <div class="clear" style="margin-bottom:5px"></div>
        <strong>Comment:</strong><br>
        <textarea cols="60" rows="3" id="Notes" name="Notes" class="Notes"></textarea><br>
        <input type="checkbox" name="isPrivate" value="yes" id="isPrivate">&nbsp;Make Comment Private?<br />
        <input type="checkbox" name="paidFees" value="yes" id="paidFees">&nbsp;Paid Fees?
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="$.fancybox.close();">Cancel</a>
        <input type="submit" class="btn btngreen btnSubmit" value="Submit" />&nbsp;
    </form>
</div>
<? } ?>
<?
$hasVol = (count($this->project->volunteers) > 0);
$hasVol = ($hasVol && in_array($this->userNew->id, Zend_Registry::get('configuration')->user->manageFunds->toArray()));
?>
<? if ($hasVol) { ?>
<div id="editDestinationFcyBx" style="display:none;">
    <h2>Edit Donation Destination #<span class="transId"></span></h2>
    <form id="edit-dest" method="post">
        <input id="transactionId" name="transactionId" value="" type="hidden"/>
        <strong>Destination:</strong><br>
        <select id="VolunteerId" name="VolunteerId">
            <option value="">General Destination</option>
            <?php foreach($this->project->volunteers as $volunteer) { ?>
            <option value="<?php echo $volunteer->user->id ?>"><?php echo stripslashes($volunteer->user->fullName) ?></option>
            <?php } ?>
        </select>
        <div class="hide errorMsg"><div class="clear"></div><br>The original destination is not participating under the initiative.</div>
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="$.fancybox.close();">Cancel</a>
        <input type="submit" class="btn btngreen btnSubmit" value="Save" />&nbsp;
    </form>
</div>
<? } ?>
<div id="popup-overlay"></div>
<div class="wrapper">
   <!-- org header -->
  <?php echo $this->placeholder('header') ?>
  <!-- // org header -->

  <div class="clr"></div>

  <div class="BodyCon">
    <!-- breadcrumb -->
    <?php echo $this->placeholder('breadcrumb') ?>
    <!-- // breadcrumb -->
    <div class="clr"></div>

    <!-- tabs -->
    <?php echo $this->placeholder('tabs') ?>
    <!-- // tabs -->

    <div class="mainC">
      <div class="box05">
        <div class="headingStyle02">
            <?= isset($this->project) ? $this->project->name : $this->group->name ?>'s Donations (<?php echo number_format(count($this->donations)) ?> totaling <?=(isset($this->group)) ? $this->group->currency : $this->organization->currency?><?= isset($this->project) ? number_format($this->project->raised) : number_format($this->group->raised); ?>)
        </div>
        <div id="mainnotleftdonations">
            <table width="100%">
                <tr>
                    <td valign="top" style="padding-top:6px;">
                        <div id="donationFilters" class="article01" style="width:98%!important; padding-bottom:6px; margin-bottom:10px; display:none;">
                            <form id="search_donation" name="search_donation" method="post">
                                <?php if (isset($this->group) && empty($this->isProgram)) { ?>
                                <span style="float:left;">
                                    <span style="color:#693; font-weight:bold; font-size:13px;" >Filter By: </span>
                                        <option value="">Activity or Campaign: All</option>
                                        <?php foreach ($this->projects as $activity) { ?>
                                            <option value="<?php echo $activity->id ?>" <?= isset($this->project) && $this->project->id == $activity->id ? "selected" : ""; ?>><?php echo stripslashes($activity->name) ?></option>
                                        <?php } ?>
                                    </select>
                                </span>
                                <?php } ?>
                                <div class="clear" style="margin-bottom:25px;"></div>
                                <div class="search" style="float:left;margin:0;width:auto;">
                                    <input type="text" name="search_text" style="width:250px; border:2px solid #528D19; padding:3px; float: left; color: gray; background: url(/public/images/search.gif) no-repeat 98% center" <?php if (isset($_POST['search_text'])) echo 'value="' . $_POST['search_text'] . '"';?> />
                                    <input type="submit" style="position: absolute; left: -9999px"/>
                                </div>
                                <span style="float:left;margin:3px 0 0 5px;">Show:
                                    <select name="show_list" onchange="search_donation.submit()">
                                        <option value="10" <?php echo $this->showList == 10 ? "selected" : "" ?>>10</option>
                                        <option value="25" <?php echo $this->showList == 25 ? "selected" : "" ?>>25</option>
                                        <option value="50" <?php echo $this->showList == 50 ? "selected" : "" ?>>50</option>
                                        <option value="100" <?php echo $this->showList == 100 ? "selected" : "" ?>>100</option>
                                    </select>
                                </span>
                                <div style="float:right; margin:3px 0 0 15px;">
                                    <span style="float:left;">
                                        <div style="float:left; margin-top:5px; font-weight:bold; color:#693; font-size:13px;">Filter By Donation Date:&nbsp;</div>
                                        <input id="FromDate" name="FromDate" <?= (isset($_POST['FromDate'])) ? 'value="' . $_POST['FromDate'] . '"' : '' ; ?> style="float:left; width:100px; cursor: pointer" class="text smaller" onchange="filterByDate();" />
                                        <div style="float:left; width:20px; margin-top:5px; font-weight:bold; text-align:center; color:#693; font-size:13px;">&nbsp;to&nbsp;</div>
                                        <input id="ToDate" name="ToDate" <?= (isset($_POST['ToDate'])) ? 'value="' . $_POST['ToDate'] . '"' : ''; ?> style="float:left; width:100px; cursor: pointer" class="text smaller" onchange="filterByDate();" />
                                    </span>
                                </div>
                            </form>
                        </div>

                        <div class="article01" style="width:100%!important;padding-bottom:10px;">
                            <ul id="tools-links">
                                <h2 style="border:none;"><li><a href="javascript:;"><img src="/public/images/wrench.jpeg" style="border:1px solid #AAA;"></a>
                                    <ul style="font-size:12px; font-weight:normal;">
                                        <? if ($manual) { ?><li><a href="javascript:;" class="manualEntry"><img src="/public/images/dollarsign.png" style="margin:3px 5px;"><span style="vertical-align:top;margin-right:15px;">Manual Donation Tool</span></a></li><br /> <? } ?>
                                        <li><a href="/reporting/export2?SiteId=<?= isset($this->project) ? $this->project->id : $this->group->id; ?>&Type=<?= isset($this->project) ? 'Project' : 'Group'; ?>"><img src="/public/images/reports.png" style="margin:3px 5px;"><span style="vertical-align:top;margin-right:15px;">Pull Donations Report</span></a></li><br />
                                    </ul>
                                </li>
                            </ul></h2>
                            <div id="showFilterLink" style="float:right;margin-right:20px;margin-top:10px;"><a href="javascript:;" onclick="$('#showFilterLink').hide(); $('#donationFilters').show(); $('#hideFilterLink').show();" >Show Filters</a></div>
                            <div id="hideFilterLink" style="float:right;margin-right:20px;margin-top:10px;display:none;"><a href="javascript:;" onclick="$('#showFilterLink').show(); $('#donationFilters').hide(); $('#hideFilterLink').hide();" >Hide Filters</a></div>
                        </div>
                    </td>
                </tr>
            </table>
            </div>
            <div class="clear"></div>
            <div class="tab-container">
                <table cellpadding="5" cellspacing="0" width="100%">
                    <tr>
                        <td colspan="10" class="donation_tablehead">
                            <div class="donation_navpage">

                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="do_col1" style="color: #000">Transaction ID</td>
                        <td class="do_col2">Source</td>
                        <td class="do_col2">Donor</td>
                        <td class="do_col2">Destination</td>
                        <td class="do_col2" align="center">Amount</td>
                        <td class="do_col2" align="center">Charged</td>
                        <td class="do_col2" align="center">Notes</td>
                        <td class="do_col2" align="center">Comment</td>
                        <td class="do_col2" align="center">Date</td>
                        <td class="do_col3" align="center">Re-Email <br />Receipt</td>
                    </tr>
                    <?php foreach ($this->paginator as $donation) { ?>
                    <tr>
                        <td class="xdo_col1">
                            <?php echo $donation->transactionId ?>
                        </td>
                        <td class="xdo_col2">
                            <?= $donation->transactionSource ?>
                        </td>
                        <td class="xdo_col2">
                            <?php if($donation->donor) {
                                echo $donation->donor->fullName;
                            } else if(!empty($donation->supporterName)) {
                                echo $donation->supporterName;
                            } else {
                                echo 'Guest';
                            }?>
                        </td>
                        <td class="xdo_col2">
                            <span id="destination_<?php echo $donation->transactionId ?>"><?php echo $donation->destination; ?></span>
                            <? if ($hasVol) { ?><a href="javascript:void(0);" onclick="editDestination('<?php echo $donation->transactionId ?>','<?=$donation->userId?>')"><img src="/public/images/icon_edit.jpg" /><? } ?>
                        </td>
                        <td  class="xdo_col2" align="center"><?= (isset($this->project) ? $this->project->currency : $this->group->currency).number_format($donation->amount,2) ?></td>
                        <td  class="xdo_col2" align="center">
                            <?php if ($donation->orderStatusId == 2) { ?>
                            <img src="/public/images/dashboard/note.png" />
                            <?php } else if ($donation->orderStatusId == 3) { ?>
                            <img src="/public/images/dashboard/decline.png" alt="Cancelled" title="Cancelled"/>
                            <?php } ?>
                        </td>
                        <td class="xdo_col2" align="center">
                            <?php if (count($donation->notes)) { ?>
                            <a href="javascript:;" onclick="$('#notes-<?php echo $donation->id ?>').toggle()">View</a>
                            <?php } else { ?>
                            <a href="javascript:;" onclick="togglePopup('add-note', '#ProjectDonationId', '<?php echo $donation->id ?>', '')">+</a>
                            <?php } ?>
                        </td>
                        <td class="xdo_col2">
                            <?= substr($donation->comments,0,50) ?>
                            <? if (strlen($donation->comments) > 50 ) {
                                echo "<div id='comment{$donation->id}' class='hidden'>" . $donation->comments . "</div>
                                ... <a href='javascript:;' onclick='showComment(\"comment{$donation->id}\")'>Show Comment</a>";
                            } ?>
                        </td>
                        <td class="xdo_col2" align="center">
                            <?php echo date('M d, Y h:i:s A', strtotime($donation->createdOn)) ?>
                        </td>
                        <td class="xdo_col3" align="center">
                            <a id="resend-<?php echo $donation->id ?>" href="javascript:;" onclick="resendReceipt('<?php echo $donation->id ?>')"><img src="/public/images/dashboard/e.png" /></a>
                            <img id="sent-<?php echo $donation->id ?>" src="/public/images/dashboard/check_icon.png" style="display:none" />
                        </td>
                    </tr>
                        <?php if (count($donation->notes)) { ?>
                        <tr id="notes-<?php echo $donation->id ?>" style="display:none; background-color:#e7e7e9; border-left:1px solid #BBCFF9!important; border-bottom:1px solid #BBCFF9!important; padding:3px 5px!important">
                            <td colspan="7">
                                <div style="padding:5px 0;">
                                    <?php foreach($donation->notes as $note) { ?>
                                        &nbsp;&nbsp;<?php echo ($note->isPrivate == 1 ? "Private Note - " : "Public Note - ").stripslashes($note->note) ?>
                                        <input type="hidden" id="hidden-note-<?php echo $note->id ?>" value="<?php echo stripslashes($note->note) ?>" />
                                        <a href="javascript:;" onclick="togglePopup('edit-note', '#DonationNoteId', '<?php echo $note->id ?>', '')">Edit</a>
                                        &nbsp;/&nbsp;
                                        <a href="javascript:;" onclick="deleteNote('<?php echo $note->id ?>')">Delete</a>
                                        <br>
                                    <?php } ?>
                                    <a style="margin-left:10px" href="javascript:;" onclick="togglePopup('add-note', '#ProjectDonationId', '<?php echo $donation->id ?>')">Add New</a>
                                    <br>
                                </div>
                            </td>
                        </tr>
                        <?php } ?>
                    <?php } ?>
                </table>
                <div class="spacer"></div>
                <div class="navpage">
                    <div class='s2st03' style="margin-top:10px"><?= $this->paginationControl($this->paginator, 'Sliding', '/dashboard/page_selector.phtml'); ?></div>
                </div>
                <a class="btn btngreen" href="/<?= isset($this->project) ? $this->project->urlName : $this->group->urlName ?>">Back</a>
            </div><!--End Main Content-->
        </div>
    </div>
    <div class="clr"></div>
    <div class="clr"></div>
</div>
