<?php $this->headTitle("Empowered.org: FAQ"); ?>
<script src="/public/js/twisties.js"></script>
<style>
h3 { font-size: 1em; margin: 10px 0; font-weight:normal; }
</style>
<div>
    <div id="mainco2">
        <div class="roundedbox">
        <div class="section">
            <h2>Empowered.org General FAQ</h2>
            <div class="alt c1">
                <h3 class="twisty">What is empowered?</h3>
                <div style="display: block; opacity: 1;"> Empowered.org is an online platform for groups looking to create social change around the world. Our site is designed to facilitate positive social impact by facilitating growth in organizations, saving them money, and helping them operate more efficiently. We help groups and social movements build and grow online communities by providing the tools to organize and mobilize more efficiently, thus promoting your cause and fundraise more effectively.  This means everything runs easier and results in more support for your group, helping you grow organically. </div>
                <h3 class="twisty">How does it work?</h3>
                <div style="display: none; height: 0pt; opacity: 0;"> Empowered is easy and simple to use! Want to start a group? Just click the “Get Started” link at the top of the page, enter your information, and select “Create Group.” Now you have your own group page that anyone can see, with many useful tools like creating volunteer activities, managing volunteers, and fundraising. Anyone who may be interested can now easily support your cause, either by signing up as a volunteer or making a donation.
                    Want to join a group? Easy. Just click the “Join” link at the top right of the page and enter your info to create an account. Now you can search for groups to support by using the search function. When you find one you’re interested in, click on “Become a Group Member” on the group page, and a request will be sent to the group. Once they accept the request, you are now part of the group’s online community! </div>
                <h3 class="twisty">What does it cost?</h3>
                <div style="display: none; height: 0pt; opacity: 0;"> Empowered is free for all members and groups to sign up, with unlimited use of all tools and functionalities. Empowered.org also makes it possible for you to pass your online merchant fees to donors during checkout. To keep Empowered alive, we also ask for a 1.5% contribution from donors to help maintain the site - which is optional or mandatory depending on your settings. This process ensures that Empowered will never have any set up costs or monthly fees... EVER!</div>
                <h3 class="twisty">Is empowered a non-profit? What does it do with the money it charges/makes?</h3>
                <div style="display: none; height: 0pt; opacity: 0;"> Empowered.org is not a non-profit, but instead it operates as a social business. All of the fees processed are reinvested into improving our platform. </div>
            </div>
            <div class="clear" style="margin-bottom:10px;"></div>
                <h2> Questions for Groups/Organizations Getting Started: </h2>
                <div class="alt c1">
                    <h3 class="twisty">Who does Empowered help? What can it do for my org/group?</h3>
                    <div style="display: none; height: 0pt; opacity: 0;"> Empowered is here to help all working to make a difference, from local grassroots movements to multination organizations. Our platform gives you a true presence online. Most importantly, our flexible features mean that Empowered.org can grow with your group, Empowering you to build and develop your online community.  This means you’ll be able to clearly edit your group’s activities and spread the word to whoever you choose. And, you’ll enhance your group’s ability to fundraise with “Donate” buttons on your volunteer activities and fundraising campaigns, personal fundraising pages for individual group members, and tools to spread the word to new donors anywhere. Perfect for any size group, with grow with you and ensure that things run smoothly and effectively. </div>
                    <h3 class="twisty">Is it open to anyone? Do I have to be a non-profit?</h3>
                    <div style="display: none; height: 0pt; opacity: 0;"> Empowered.org is open to any and all organizations in 190 countries, regardless of charitable status. We are unique in that you do NOT have to be a registered non-profit to benefit from the services that Empowered has to offer. Simply put, the site is for anyone working to make a difference in the world. </div>
                    <h3 class="twisty">How do I create a group or organization?</h3>
                    <div style="display: none; height: 0pt; opacity: 0;"> Creating a group on Empowered.org is quick and simple! Just click on the “Get Started” link at the top of the page, fill out the appropriate information, and there you have it: your group has its own personal webpage for developing your online community. From here you can manage volunteers, fundraise, and more.
                        If you believe that your organization could benefit from having a multi-chaptered setup, please contact us at oisin@empowered.org so that we may discuss your needs and provide you with the setup that best fits your organization. </div>
                        <h3 class="twisty">What’s the difference between groups and orgs?</h3>
                        <div style="display: none; height: 0pt; opacity: 0;"> “Groups” are intended for smaller, less complex movements. “Organizations” are geared toward layered, multi-chaptered movements that coordinate multiple groups. For example, a single Soup Kitchen in Oakland would benefit from a Group setup because it is less complex, working out of a single location as a single group. But an organization that ran Soup Kitchens throughout all of Northern California would probably benefit from an “Organization” setup, so that each location can be managed as its own group, and all the groups would be part of the umbrella organization.
                            Can I Customize my Group/Org URL?
                            No Problem! On your Group Home Page roll your cursor over the “Tools” button and click “Edit Details.” In the second box under URL, you can change your Empowered URL. The default setup is www.empowered.org/GROUPNAME, but you can change it to anything you want. </div>
                            <h3 class="twisty">Is my group page public? Can non members see it?</h3>
                            <div style="display: none; height: 0pt; opacity: 0;"> Yes, any interested person can search for and explore your group page. However, in order to sign up for volunteer activities or events, or to fundraise for your group, a person must make an account and register as a member of your group. Group Administrators will receive email requests from people trying to join the group, which you can Accept or Deny. Group member requests can also be automated, so that new members are automatically accepted or denied </div>
                        </div>
                        <div class="clear" style="margin-bottom:10px;"></div>
                        <h2> Using the Platform: </h2>
                        <div class="alt c1">
                            <h3 class="twisty">How do I create an activity? A campaign? An event? </h3>
                            <div style="display: none; height: 0pt; opacity: 0;"> Creating volunteer activities, fundraising campaigns, and events is easy on Empowered. From the group home page, simply click one of the blue links on the right that say “+ Create a new XXX.” Then just fill out the info, and you’re done. Now people can see what upcoming events and activities your group has planned, and what fundraising campaigns it is currently working on. </div>
                            <h3 class="twisty">How do I manage all these different features? </h3>
                            <div style="display: none; height: 0pt; opacity: 0;"> Managing these features is easy as well. Just click on the appropriate gray tab at the top (either “Volunteer Activities”, “Fundraising Campaigns”, or “Events”). On the new page that loads, you can create, delete, or edit details for any of these features, any time you wish. </div>
                            <h3 class="twisty">What exactly are the admin tools? How do they work? </h3>
                            <div style="display: none; height: 0pt; opacity: 0;"> The admin tools are located in the “Tools” drop-down tab on the Group Home page. These tools allow you to edit Group Details, upload Logos and Banners, Share Files with group members, and view information on volunteers, donations, donors, and other reports. They are simple to use, just roll over the “Tools” button, and click on the link you are interested in from the drop-down menu.
                                NOTE: If ever you cannot see the “Tools” tab, be sure Admin Tools are visible and enabled. If the “Tools” tab is not appearing, click on the “Show Admin Controls” button at the top of your group page. </div>
                            </div>
                            <div class="clear" style="margin-bottom:10px;"></div>
                            <h2> Groups and members: </h2>
                            <div class="alt c1">
                                <h3 class="twisty"> Can I decide who becomes a member/volunteer? Can I accept/deny? How? </h3>
                                <div style="display: none; height: 0pt; opacity: 0;"> Yes, the Empowered.org platform gives you complete control over who can become members and volunteers of your group. This means groups and activities can become as large (or not) as you like. When a new person requests to become a member of your group, you will receive a request email from the site, on through this email you can choose to Accept or Deny this new potential member. Same goes for volunteer activities: as group members try and volunteer for activities, you will receive requests which you may accept or deny. All of these features can be automated, so members and volunteers are automatically accepted or denied. </div>
                                <h3 class="twisty"> How do I manage all these different features? </h3>
                                <div style="display: none; height: 0pt; opacity: 0;"> Managing these features is easy as well. Just click on the appropriate gray tab at the top (either “Volunteer Activities”, “Fundraising Campaigns”, or “Events”). On the new page that loads, you can create, delete, or edit details for any of these features, any time you wish. </div>
                                <h3 class="twisty"> What exactly are the admin tools? How do they work? </h3>
                                <div style="display: none; height: 0pt; opacity: 0;"> The admin tools are located in the “Tools” drop-down tab on the Group Home page. These tools allow you to edit Group Details, upload Logos and Banners, Share Files with group members, and view information on volunteers, donations, donors, and other reports. They are simple to use, just roll over the “Tools” button, and click on the link you are interested in from the drop-down menu.
                                    NOTE: If ever you cannot see the “Tools” tab, be sure Admin Tools are visible and enabled. If the “Tools” tab is not appearing, click on the “Show Admin Controls” button at the top of your group page. </div>
                                    <h3 class="twisty"> Is there a way to contact members/volunteers? </h3>
                                    <div style="display: none; height: 0pt; opacity: 0;"> Absolutely! Contacting members is easy. Just go to the “Members” page by clicking the gray tab at the top. Then using the “Tools” drop down menu, select “Email Members.” From here you can email all members, or choose specific ones to contact. Using the same “Tools” tab on the Members page, you can also send Surveys to members to collect info, ask about experiences, get feedback, etc.
                                        To contact Volunteers or Fundraisers for a specific Activity or Campaign, simply go to the Activity/Campaign page (click the gray tab at the top for either “Volunteer Activities” or Fundraising Campaigns” and then click on the specific activity or campaign you want). From here, just use the “Tools” drop-down menu to email volunteers/fundraisers or send surveys. </div>
                                        <h3 class="twisty"> Can I share files with the others in my community? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> No Problem! On the Group Home page, roll over the “Tools” button and select the “Share Files” link. Hit “Upload,” and select a file to upload. Now the file will be listed on the Files section of the Group Home page (on the bottom left) for any member to download. </div>
                                    </div>
                                    <div class="clear" style="margin-bottom:10px;"></div>
                                    <h2> Editing, updating, and maintaining my group/org page: </h2>
                                    <div class="alt c1">
                                        <h3 class="twisty"> How can I edit my group/organization info? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> You can easily edit group info by going to the Group Home page, rolling over the “Tools” button, and selecting “Edit Details” from the drop down menu. Same goes for organizations: just go to the Organizations Home page, roll over the “Tools” button, and select “Edit Details.” </div>
                                        <h3 class="twisty"> We have just become a non-profit! How do we change status? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"></div>
                                        <h3 class="twisty"> How do I enable fundraising? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"></div>
                                        <h3 class="twisty"> Started as a group but growing! How can we expand to an organization with connected groups? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"></div>
                                        <h3 class="twisty"> Is there a way to customize my page to make it look like our own website? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> These features will soon be added to the site. </div>
                                        <h3 class="twisty"> How do I upload for the community to see? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> Select the “Photos” tab from the gray tabs on the top. From here you can add new photos, and manage photos by grouping them into different albums. Just click either the “Add New Photo” or “Manage Photo Albums” link. Photos uploaded to the site here will be easily available for the community to see. </div>
                                    </div>
                                    <div class="clear" style="margin-bottom:10px;"></div>
                                    <h2> Donations: </h2>
                                    <div class="alt c1">
                                        <h3 class="twisty"> How do donations work with the platform? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> Donors will be able to give donations through the Donate buttons on the group page, or by accessing individual members’ fundraising pages. All donations processed will go straight to your group’s account through either PayPal or Google Checkout. With Empowered.org, we do not hold onto your money, which means no middle man! </div>
                                        <h3 class="twisty"> How quickly do we get the money? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> As soon as a donation is processed! Unlike other sites which hold your money and cut you checks in monthly lump sums,  with Empowered you will receive the funds from donations immediately, either through PayPal or Google Checkout (depending on your preference). We never hold the money, there is no middle man, and all donations are securely deposited directly to your account. </div>
                                        <h3 class="twisty"> What is the cost? How are we billed? </h3>
                                        <div style="display: none; height: 0pt; opacity: 0;"> There are no fixed costs with Empowered.org. We do charge an industry low 1.5% of all donations processed through Paypal (and no fee for Google Checkout!), plus applicable merchant fees, to help maintain the site. With PayPal, the 1.5% fee will automatically be taken from the donation. With Google Checkout we do not charge any fees for anything! (Google Checkout does take their fee though)
                                            We also offer donors the option to cover site and merchant fees in their donation, making the service completely free for you group or organization. </div>
                                            <h3 class="twisty"> Is it safe and secure? </h3>
                                            <div style="display: none; height: 0pt; opacity: 0;"> Absolutely. We connect donations directly to the merchant processor of the group (PayPal or Google Checkout). These processors are held to the highest security standards, so rest assured: donations are 100% safe and secure. </div>
                                            <h3 class="twisty"> Can I view all donors? Can I pull donor reports? How? </h3>
                                            <div style="display: none; height: 0pt; opacity: 0;"> On the Group Home page, roll over the “Tools” button. In the drop-down menu, you can select links to View Donors, View Donation History, and View Reports. </div>
                                            <h3 class="twisty"> Do they get receipts? </h3>
                                            <div style="display: none; height: 0pt; opacity: 0;"> Once a donation is processed, a receipt is send immediately via email from Empowered.org. Donors can print this for records and use it as a receipt whenever needed. If someone didn’t receive such an email, please let us know at donations@empowered.org and we will be happy to resend it. </div>
                                            <h3 class="twisty"> Is there a way to contact donors? A way to automate Thank You messages? </h3>
                                            <div style="display: none; height: 0pt; opacity: 0;"> Yes, you can absolutely contact donors. Go to the Group Home page, roll over the “Tools” button, and select “View Donors.” On the new page that loads, roll over the “Tools” icon and select “Email Donors.” This will allow you to email all donors, donors of a specific activity or campaign, or specific donors on an individual basis. </div>
                                        </div>
                                        <div class="clear" style="margin-bottom:10px;"></div>
                                        <h2> Questions for Members/Volunteers: </h2>
                                        <div class="alt c1">
                                            <h3 class="twisty"> What is Empowered? What is it? How does it work? </h3>
                                            <div style="display: none; height: 0pt; opacity: 0;"> Empowered.org is an online platform to give groups and social movements an online presence, helping them grow their online communities, organize activities, manage volunteers, and fundraise. Groups and organizations create their own pages on through which they can create and organize volunteer activities, start fundraising campaigns, and more.
                                                Individuals who are interested in being part of a group or social movement need only make an account and join the group! From here you can volunteer or raise funds, and each individual gets his/her own personal page. Use this page to edit info </div>
                                                <h3 class="twisty"> How are you affiliated with the org/group on the site? </h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> Empowered.org is an online platform to help groups and social movements organize, mobilize, and fundraise effectively. We provide the tools to help groups build and grow their online communities. We are simply a tool for these groups and organizations to use to establish and maintain and online presence, as well as offering unique online tools and features. Simply put, we are here to augment and accelerate groups and social movements. </div>
                                                <h3 class="twisty"> How can I get started? </h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> Getting started on Empowered.org is quick and simple. At the top right of the page select the “Join” link, enter the necessary information, and your account is created. From here you can use the search function the look for groups or activities that interest you. Once you find something that looks good, select the “Become Group Member” or “Volunteer” button (you must be a group member to volunteer for an activity; the Volunteer button will automatically send a Group Member request). Once the group accepts your request, you are part of the group and a member of the online community. Now you are free to volunteer for activities, fundraise for campaigns, and work with the group to make a difference. </div>
                                            </div>
                                            <div class="clear" style="margin-bottom:10px;"></div>
                                            <h2> Questions for Members/Volunteers: </h2>
                                            <div class="alt c1">
                                                <h3 class="twisty"> How do I find a group/org/activity? </h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> Simply use the Search Box at the top of the page to search for Groups, Organizations, or Activities. </div>
                                                <h3 class="twisty"> How do I join? Do I need an account? </h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> You do need an account to join a Group or volunteer for an Activity. Creating an account is fast and easy, just click “Join” at the top right of the page, enter the necessary information, and your account is created. Now you can join groups, volunteer, and fundraise. </div>
                                                <h3 class="twisty"> I joined a group but am not listed as volunteer (difference between members and volunteers) </h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> If you have found a group that you are interested in, selected “Become Group Member” and your request was accepted, this makes you a member of the group. You will receive group updates, be listed as a member, and can be contacted by leaders and administrators of that group. Once you are a member, you can volunteer for specific activities and opportunities you are interested in by selecting the Volunteer button.
                                                    In short: after becoming a member of a group, you then select specific opportunities to volunteer for, or specific campaigns to fundraise for. </div>
                                                </div>
                                                <h3 class="twisty"> Want to cancel your membership?</h3>
                                                <div style="display: none; height: 0pt; opacity: 0;"> If you would like to discontinue your Membership, you will need to sign into your personal empowered.org page, select "Tools" and click "Deactivate Membership."</div>
                                                </div>
                                                <div class="clear" style="margin-bottom:10px;"></div>
                                                <h2> Your Personal Page: </h2>
                                                <div class="alt c1">
                                                    <h3 class="twisty"> What can I do with my own personal page? </h3>
                                                    <div style="display: none; height: 0pt; opacity: 0;"> Once you create an account on Empowered.org, you will have your own personal page. Your Dashboard/Profile Home will display groups and organizations which you are a part of, as well as any upcoming volunteer activities, past volunteer activities, active fundraising campaigns, and past fundraising campaigns. To your Dashboard just roll over the top right where it says “Hi YOUR NAME” and select “Go To Dashboard” from the drop-down menu.
                                                        You will also have your own personal fundraising pages for campaigns you are working on. Just click on the gray “Fundraising Pages” tab at the top. Give links to active campaigns to friends and family to gain support for your cause.
                                                        You will also have a profile to talk about and display any information about yourself you wish to share, such as your passions and the city/region in which you live. Go to the top right, roll over the “Hi YOUR NAME” button, and select “View Profile.” </div>
                                                        <h3 class="twisty"> How do I update/edit my profile? </h3>
                                                        <div style="display: none; height: 0pt; opacity: 0;"> While viewing your profile, select the “Edit” button at the top/center of the page, located beneath your name and next to your picture, to update and edit details about your profile. </div>
                                                        <h3 class="twisty"> How do I see the campaigns, activities, groups that I am a part of? </h3>
                                                        <div style="display: none; height: 0pt; opacity: 0;"> Go to your Dashboard to view this information. At the top right of the screen roll over the “Hi YOUR NAME” button, and select “Go To Dashboard.” </div>
                                                        <h3 class="twisty"> How does my fundraising page work? </h3>
                                                        <div style="display: none; height: 0pt; opacity: 0;"> Fundraising is simple. Just give the URL to a specific, active campaign to friends, family, or anyone else you are reaching out to for support. By clicking this link they will go to your personal fundraising page for that campaign where they can find more information about the group and the campaign/activity for which you are raising money. There is a big, easy to use “Donate” button on your page, should they choose to make a donation and give support. </div>
                                                        <h3 class="twisty"> How do I share this with friends/family? </h3>
                                                        <div style="display: none; height: 0pt; opacity: 0;"> There are a number of easy ways to do this. On your Dashboard there are Share Icons to share the fundraising page either through email, Facebook, or Twitter.
                                                            Or you can select gray tab that says “Manage Fundraising Pages,” select the specific campaign you wish to share, and then provide the link to friends by copying the URL from your browser and pasting it wherever you wish to share it. There are also share icons for email, Facebook, and Twitter located beneath the “Donate” button on each campaign page. </div>
                                                            <h3 class="twisty"> Can I share on Facebook/Twitter? How? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Yes, easily. Just use the Share Icons, located on the Dashboard or at the top of the Fundraising Campaign page beneath the “Donate” button. Immediately after signing up for a campaign or activity, the site will also prompt you to share with your friends and family via Facebook, Twitter, or email. </div>
                                                        </div>
                                                        <div class="clear" style="margin-bottom:10px;"></div>
                                                        <h2> Donations: </h2>
                                                        <div class="alt c1">
                                                            <h3 class="twisty"> How do they work? Where does the money go? When/How fast? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Donations made through Empowered.org are processed by either PayPal or Google Checkout. The money is deposited directly to the account of the group or organization, giving them immediate access to these funds. Empowered.org never holds the money, it goes straight from donor to the cause they are supporting. </div>
                                                            <h3 class="twisty"> What is the cost to my supporters to donate? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> It does not cost any extra money for supporters to donate to a cause. Empowered.org does charge the group/organization 1.5% of all donations processed through Paypal on the site (no fee for Google Checkout), plus merchant fees, and we do offer donors the chance to cover these costs on behalf of the organization they are supporting. </div>
                                                            <h3 class="twisty"> Is it safe and secure? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Absolutely. We connect donations directly to the merchant processor of the group (PayPal or Google Checkout). These processors are held to the highest security standards, so rest assured: donations are 100% safe and secure. </div>
                                                            <h3 class="twisty"> Are donations Tax deductible? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> This depends. Groups with official 501(c)(3) non-profit status should be able to help make sure your donation is tax deductible; however, groups without such status may not be able to. Because each group is different, we ask you consult with your specific group leader to make sure. </div>
                                                            <h3 class="twisty"> How can I be a helpful, active member of the online community? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> This is simple, just make use of the site! Sign up for volunteer activities and fundraising campaigns, and provide links to these activities and campaigns to friends and family. And be sure that if you sign up for something, you show up! Just do your best do stay engaged. </div>
                                                            <h3 class="twisty"> How can I contact a group/org? How do I get more info on them? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Groups provide contact information on their Group Home pages. Just go to the Group Home page to see this information. Groups also typically display information on who they are and the work they are doing on their Group Home page. They may also provide a link to their official website where more information may be available. </div>
                                                        </div>
                                                        <div class="clear" style="margin-bottom:10px;"></div>
                                                        <h2> Questions for Donors: </h2>
                                                        <div class="alt c1">
                                                            <h3 class="twisty"> How do I donate? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Once you have found a campaign or activity that you wish to donate to (either by searching the site or from a link provided by a friend or family member), just click on the big orange “Donate” button to make a donation and support the cause! </div>
                                                            <h3 class="twisty"> Do I need an account? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> No, you do not need an account to donate. </div>
                                                            <h3 class="twisty"> Is it safe and secure? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Absolutely. We connect donations directly to the merchant processor of the group (PayPal or Google Checkout). These processors are held to the highest security standards, so rest assured: donations are 100% safe and secure. </div>
                                                            <h3 class="twisty"> Is it tax deductible? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> This depends. Groups with official 501(c)(3) non-profit status should be able to help make sure your donation is tax deductible; however, groups without such status may not be able to. Because each group is different, we ask you consult with your specific group leader to make sure. </div>
                                                            <h3 class="twisty"> Where does the money go? When does the cause/org/group get it? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Donations made through Empowered.org are processed by either PayPal or Google Checkout. The money is deposited directly to the account of the group or organization, giving them immediate access to these funds. Empowered.org never holds the money, it goes straight from donor to the cause they are supporting. </div>
                                                            <h3 class="twisty"> I am donating to a friend’s page who is raising money for X. Does my friend get the money or does it go straight to X? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> The money goes straight to the account of the group or organization your friend is working to support. </div>
                                                            <h3 class="twisty"> What is the cost to me? To the organization/group? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> As a donor, it costs you no extra money to donate. There is a 1.5% fee that Empowered.org charges to groups and organizations for all donations processed through Paypal, but no fee from us for donations processed through Google Checkout. For Paypal, we give donors the options of covering this cost to the organization by increasing their donation amount by 1.5%, but this is not obligatory. </div>
                                                            <h3 class="twisty"> What does Empowered do with the money it makes? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> The money that Empowered.org receives from the 1.5% fee on Paypal donations is reinvested into the platform. The money we take only covers our costs. </div>
                                                            <h3 class="twisty"> Can I get a receipt? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Once a donation is processed, a receipt is send immediately via email from Empowered.org. Donors can print this for records and use it as a receipt whenever needed. If someone didn’t receive such an email, please let us know at donations@empowered.org and we will be happy to resend it. </div>
                                                            <h3 class="twisty"> How do I contact a group/org or get more info? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Groups/organizations offer contact info as well as additional information on their group homepage. Here you may find email, phone numbers, and links to official websites, depending on what kind of information the group has provided. </div>
                                                            <h3 class="twisty"> Offline donations? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> All offline donations in the form of cash, check or money order should be given to the appropriate group directly (either in person or via mail). For mailing information, please contact the specific group leader to see where to send your donation. Note: If you are donating to a specific individual, we will make sure that donation amount is reflected on their personal fundraising page. </div>
                                                            <h3 class="twisty"> Who do I contact about donor issues? </h3>
                                                            <div style="display: none; height: 0pt; opacity: 0;"> Please contact the specific group administrator with donations issues; their contact information is on the group homepage and they should have the correct answers to your questions. If the group admin cannot help with your issue, feel free to contact us at: donations@empowered.org with any additional queries. </div>
                                                        </div>
                                                    </div>
                                                    <script>
                                                    var twisties = new goog.ui.Twisties( {
                                                        enableFade: true,
                                                        classTwisty: 'twisty',
                                                        classCollapse: 'twisty-expand',
                                                        classExpand: 'twisty-collapse',
                                                        twistyTag: 'h3'
                                                    } );
                                                    </script>
        </div>
    </div>
</div>
