<?php
$this->headTitle($this->organization->name."'s Custom Donation Receipt");
$this->placeholder('currenttab')->set('orghome');
?>
<div class="wrapper">
   <!-- org header -->
  <?php echo $this->placeholder('header') ?>
  <!-- // org header -->

  <div class="clr"></div>

  <div class="BodyCon">
    <!-- breadcrumb -->
    <?php echo $this->placeholder('breadcrumb') ?>
    <!-- // breadcrumb -->
    <div class="clr"></div>

    <!-- tabs -->
    <?php echo $this->placeholder('tabs') ?>
    <!-- // tabs -->

    <div class="mainC">
      <div class="box05">
        <div class="headingStyle02">Customize Your Donation Receipt</div>
          <div style="border:1px solid #dcbd00; background-color:#fff7c8; padding:10px; margin-top:8px;">Below is an example of your customizable, Empowered.org donation receipt.<br /> Variable text is highlighted in yellow; text that is only displayed when applicable is contained in brackets (i.e., [ ]).<br />Use the text box at the bottom to include custom content into your donation receipts.</div><br /><br />
			Dear <span style="background:yellow;">Donor-Name</span>,<br /><br />
			Thank you for your donation to <strong><?=$this->organization->name?></strong> [on behalf of <span style="background:yellow;">Volunteer-or-Funraiser-Name</span>]. Your donation details are as follows:<br /><br />
			Recipient: <?=$this->organization->name?><br />
			Amount: <span style="background:yellow;">Donation-Amount</span><br />
			Donation #: <span style="background:yellow;">Donation-Number</span><br /><br />
			Know someone who would love to help? Share this cause with family and friends by sending them this link: <span style="background:yellow;">Link-to-Campaign-or-Activity</span><br /><br /><br />
			<form method="post" action="/nonprofit/donationreceipt">
				<input type="hidden" name="SiteId" id="SiteId" value="<?=$this->organization->id?>">
				<input type="hidden" name="NetworkId" id="NetworkId" value="<?=$this->organization->id?>">							
				<textarea id="Message" name="Message" rows="10" <?php echo $this->message == '' ? 'style="color:#888;width:80%;" onclick="this.value=\'\'; $(this).css(\'color\', \'#000\');"' : 'style="width:80%;"' ?>><?php echo $this->message == '' ? 'Place your customized message into this box. You may use HTML to include logos and make other customizations as you desire.' : $this->message; ?></textarea>
				<div class="clear"></div><br /><br />
				Regards,<br />
				<?=$this->organization->name?>
				<br /><br />
				<a class="btn btngreen" href="/<?=$this->organization->urlName?>">Back</a>
				<input type="submit" value="Save" class="btn btngreen" />
			</form>
		</div>
	</div>
	<div class="clr"></div>
	<div class="clr"></div>
</div>
