<?php $this->headTitle("Empowered.org - Start an Organization"); ?>
<script type="text/javascript" language="javascript">
    function ValidateForm() {
        var error = "";
        if (!$('#hasPrograms-1').attr('checked') && !$('#hasPrograms-2').attr('checked')) {
            error += "Please specify if your organization has programs or none.<br>";
        }
        if (jQuery.trim($('#NetworkLogo').val()) != '') {
            var image = $('#NetworkLogo').val().split(".");
            var accepted_files = new Array("jpeg", "jpg", "png", "gif");
            var extension = image[image.length-1].toLowerCase();
            if (!accepted_files.inArray(extension)) {
                error += "Please upload pictures in jpeg, png and gif format only.<br>";
            }
        }
        if (jQuery.trim($('#NetworkName').val()) == '') {
            error += "Please specify the name of organization.<br>";
        }
        if (jQuery.trim($('#Description').val()) == '') {
            error += "Please enter the organization's description.<br>";
        }
        if (jQuery.trim($('#Email').val()) == '') {
            error += "Please provide the organization's contact email.<br>";
        } else {
	    if(!validateEmail(jQuery.trim($('#Email').val()))) {
		error += "You have entered an invalid email.<br>";
	    }
	}
	if (jQuery.trim($('#WebAddress').val()) != "" && !validateURL(jQuery.trim($('#WebAddress').val()))) {
            error += "You have entered an invalid website.<br>";
        }
	if (error != '') {
            $('#message').removeClass('success').addClass('error').html(error).show();
            window.location.href= "#top";
            return false;
        } else {
            return true;
        }
    }
    
    function hideBoxes() {
        $('.info-boxes').hide();
    }

    function hidePopup() {
        $('#popup-box').hide();
        if ($('#NetworkLogo').val() != '') {
            $('#add-photo').html("Change Photo");
        }
    }

</script>
<style type="text/css">
    .success { color:green }
    .error { color:red }
    .field-label { float:left; font-weight:bold; color:#000; width:200px; margin-bottom:15px;}
    .field-input { float:left; width:455px; margin-bottom:15px; }
    .field-input .input { width:300px; }
    .field-input input { padding:1px; }
    .field-input .date { width:95px; }
    .hidden { display:none }
    .popup-box { width: 370px; left: 40%; right: 40%; top:25%; position: absolute; z-index: 999999!important; background-color:#ffffff; border:5px solid #e5e5e5; padding:10px 0 20px 0; -moz-border-radius:7px }
    .info-boxes, .info-boxes2 { margin: 10px 0px; margin-left: 15px; background: #fff7c8; border:1px solid #dcbd00; padding: 10px 5px; -moz-border-radius:5px; width: 500px; float: left }
</style>


<div>
    <div id="mainco2">
        <div class="roundedbox">
            <a id="top" href="#top" style="text-decoration:none">&nbsp;</a>
            <form name="CreateOrganization" method="post" enctype="multipart/form-data" onsubmit="return ValidateForm()">
                <input type="hidden" name="isMultichaptered" value="1" />
                <input type="hidden" name="NetworkId" value="<?php echo $this->data['NetworkId'] ?>" />
                <input type="hidden" name="MediaId" value="<?php echo $this->data['LogoMediaId'] ?>" />
                <input type="hidden" name="ContactId" value="<?php echo $this->contactInfo['ContactId'] ?>" />
                <div style="margin:auto; width:960px; padding-right:5px; ">
                    <div id="message" class="error" style=" border:2px solid #e3e3e3; margin-bottom:15px; padding:5px; width:475px; display: none"></div>
                    <div id="popup-box" class="popup-box" style="display:none;">
                        <div style="padding:10px; padding-top:0px">
                            <h3 style="margin:auto; padding:5px 0px; color:#3366FF; margin-bottom:20px; font-size:15px; border-bottom:2px solid #e5e5e5">Choose Network Logo</h3>
                            <div style="border:1px solid #A00; background-color:#FF4F4F; padding:10px; margin-bottom:8px;">Please select jpeg, gif and png files that are under 2MB.</div>
                            <span style="font-weight:bold">Select an image:&nbsp;</span>
                            <input type="file" size="24" name="NetworkLogo" id="NetworkLogo" class="textfield" /><br>
                            <div style="border:1px solid #dcbd00; background-color:#fff7c8; padding:10px; margin-top:8px;">You will be asked to crop your image after creating this organization.</div>
                            <input id="add-photo" class="button" type="button" value="Upload" style="float:right; margin-top:10px; margin-right:5px" onclick="hidePopup()">
                        </div>
                    </div>
                    <ul style="list-style:none; padding-bottom:0px">
                        <li style="width:180px; float:left; margin-right:20px; margin-left:5px">
                            <div style=" background-color:#BDD1DE; width:105px; height:80px; padding:20px 35px; margin:0px;">
                                <div style="border:2px solid rgb(255, 255, 255); width: 100px; height: 75px; margin:0px;">
                                    <img src="/public/images/addphoto.jpeg" style="width:100px; height:75px;" />
                                </div>
                            </div>
                            <div style="width:180px; text-align:center; margin-top:10px">
                                <a id="add-photo" href="javascript:;" onclick="$('#popup-box').show()" class="btn btngreen" style="text-decoration:none">Upload Logo</a>
                            </div>
                        </li>
                        <li style="border-left:1px solid #e5e5e5; width:725px; float:left; padding-left:20px">
                            <h1 style="margin-bottom:0px; font-size:23px; font-weight:bold">Update your organization profile:</h1>
                            <div id="message" class="error" style="width:500px; border:2px solid #e3e3e3; margin-bottom:15px; padding:5px; display: none"></div><br />
                            <ul style="list-style:none; padding-bottom:0px; margin-bottom:0px">
                                <li style="float: left; width: 100%; margin-bottom: 20px;" class="multi-chaptered">
                                    <strong><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Would your organization benefit from the use of programs as well as groups?</strong> <br>
                                    <span style="color: gray">(i.e. How is your organization set up? Are there more than two layers to the organization? see example image below)</span><br>
                                    <span><input name="hasPrograms" type="radio" id="hasPrograms-1" class="create-opts" value="1" /> <span style="margin-right: 10px">Yes</span></span>
                                    <span><input name="hasPrograms" type="radio" id="hasPrograms-2" class="create-opts" value="0" /> <span style="margin-right: 10px">No</span></span>
                                    <br>
                                    <div class="info-boxes2">
                                        <center><img src="/public/images/sample-image2.gif" /></center>
                                    </div>
                                </li>
                                <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Name:</li>
                                <li class="field-input">
                                    <input name="NetworkName" type="text" id="NetworkName" class="input" value="<?php echo stripslashes($this->data['NetworkName']) ?>" />
                                </li>
                                <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Description:</li>
                                <li class="field-input">
                                    <textarea name="Description" rows="10" cols="20" id="Description" class="input" onblur="return fnKeepWordLenTrack(this,3000);" onkeyup="return fnKeepWordLenTrack(this,3000);" style="font-size:14px"><?php echo stripslashes($this->data['AboutUs']) ?></textarea>
                                </li>
                                <li class="field-label adrress" style="margin-top:-10px">&nbsp;</li>
                                <li class="field-input adrress" style="margin-top:-10px">
                                    <a href="javascript:;" onclick="$('.adrress').hide(); $('.locationbox').show();">Edit Location</a>
                                </li>
                                <li class="field-label locationbox" style="display:none;">Country:</li>
                                <li class="field-input locationbox" style="display:none;">
                                    <select type="text" name="CountryId" id="CountryId" style="width:300px" onchange="populateLocation('state', this.value); $('#Country').val(this.options[this.selectedIndex].text); populateLocation('city', 0);">
                                        <option value="all" selected>All</option>
                                        <?php foreach ($this->country_list as $country) { ?>
                                        <option value="<?php echo $country['CountryId'] ?>"><?php echo $country['Country'] ?></option>
                                        <?php } ?>
                                    </select>
                                    <input type="text" id="Country" name="Country" value="<?php echo $this->contactInfo['Country'] ?>" style="display:none;"/>
                                </li>
                                <li class="field-label locationbox" style="display:none;">Region:</li>
                                <li class="field-input locationbox" style="display:none;" id="state-list">
                                    <select type="text" name="RegionId" id="RegionId" style="width:300px" onchange="populateLocation('city', this.value); $('#Region').val(this.options[this.selectedIndex].text);">
                                        <option value="0">All</option>
                                    </select>
                                    <input type="text" id="Region" name="Region" value="<?php echo $this->contactInfo['Region'] ?>" style="display:none;"/>
                                </li>
                                <li class="field-label locationbox" style="display:none;">City:</li>
                                <li class="field-input locationbox" style="display:none;" id="city-list">
                                    <select type="text" name="CityId" id="CityId" style="width:300px" onchange="$('#City').val(this.options[this.selectedIndex].text);">
                                        <option value="0">All</option>
                                    </select>
                                    <input type="text" id="City" name="City" value="<?php echo $this->contactInfo['City'] ?>" style="display:none;"/>
                                </li>
                                <li class="field-label locationbox" style="display:none;">Street Address:</li>
                                <li class="field-input locationbox" style="display:none;">
                                    <input name="Street" type="text" maxlength="100" id="Street" class="input" value="<?php echo stripslashes($this->contactInfo['Street']) ?>" />
                                </li>
                                <li class="field-label">Website:</li>
                                <li class="field-input">
                                    <input name="WebAddress" type="text" id="WebAddress" class="input" value="<?php echo $this->contactInfo['WebAddress'] ?>" />
                                </li>
                                <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Email:</li>
                                <li class="field-input">
                                    <input name="Email" type="text" maxlength="50" id="Email" class="input" value="<?php echo $this->contactInfo['Email'] ?>" />
                                </li>
                                <div style="margin-top:15px; float:left; width:100%; margin-bottom:20px">
                                    <a class="btn btngreen" title="Back" href="/<?php echo $this->data['URLName'] ?>" style="padding: 3px 15px;">Back</a>
                                    <input type="submit" class="btn btngreen" name="btnCreateNew" value="Update" id="btnCreateNew" />
                                </div>
                                <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;">*</span><span style="color:#AAA;"> denotes a required field.</span></li>
                                <li class="field-input">&nbsp;</li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>