<script>
$(function() {
    //Program Filter
    $("#ProgramId").change(function(){
        if ($('#ProgramId').val() != 'all') {
            <? if ($this->organization->hasGroups) { ?>
            $("#loadingChapters").show();
            $("#GroupId").hide();
            $("#GroupId").children().remove().end().append($('<option>', { value : 'null' }).text('Select chapter ...'));
            <? } ?>
            cleanActivities();
            $.ajax({
                url: "<?=($this->organization->hasGroups)?'get-groups':strtolower($this->list).'-campaigns'?>",
                <? if($this->organization->hasGroups) { ?>dataType: 'json',<? } ?>
                data: 'ProgramId=' + $('#ProgramId').val() + '&filter=true',
                success: function(data) {
                    <? if ($this->organization->hasGroups) { ?>
                    $("#GroupId").show();
                    for (i=0;i<data.length;i++) {
                        $("#GroupId").append($('<option value="'+data[i].GroupId+'">').text(data[i].GroupName));
                    }
                    $("#loadingChapters").hide();
                    <? }?>
                }
            });
        } else {
            <? if ($this->organization->hasGroups) { ?>
            $("#GroupId").hide();
            $("#GroupId").children().remove();
            <? } ?>
            loadActivities();
        }
    });

    //Group Filter
    <? if ($this->organization->hasGroups) { ?>
    $("#GroupId").change(function(){
        loadActivities();
    });
    <? } ?>
});

function loadActivities() {
    $("#loadingProjects").show();
    cleanActivities();
    $.ajax({
        url: 'get-activities',
        dataType: 'json',
        data: 'ProgramId=' + $('#ProgramId').val()<? if ($this->organization->hasGroups) { ?>+ '&GroupId=' + $('#ProgramId').val()<? } ?>,
        success: function(data) {
            $("#ProjectId").show();
            for (i=0;i<data.length;i++) {
                $("#ProjectId").append($('<option value="'+data[i].GroupId+'">').text(data[i].GroupName));
            }
            $("#loadingProjects").hide();
        }
    });
}

function cleanActivities() {
    $("#ProjectId").hide();
    $("#ProjectId").children().remove().end().append($('<option value="">').text('Activities: All'));
}

function togglePopup(form, id, val, note) {
    $('#popup-overlay').toggle();
    $('.'+form).toggle()
    $(id).val(val);
    if (form == 'add-note') {
        $('#'+form+' .Notes').val(note)
    } else {
        $('#'+form+' .Notes').val($('#hidden-note-'+val).val());
    }
}

function manageNote(form, action) {
    if (jQuery.trim($(form+' .Notes').val()) == '') {
        alert("Please enter the volunteer's notes")
    } else {
        $.post('/volunteer/'+action, $(form).serialize(), function(data) {
            alert(data);
            window.location.reload(true);
        })
    }
    return false;
}

function deleteNote(id) {
    if (confirm("Are you sure you want to delete this volunteer note?") == true) {
        $.post('/volunteer/deletenote', {VolunteerNoteId: id}, function(data) {
            alert(data);
            window.location.reload(true);
        })
    } else {
        return false;
    }
}

function exportDonations(UID) {
    $.post('/reporting/export', {UserId: UID, Type: 'User'});
    return false;
}

function loadHistory(NetworkId, UserId, ProgramId, GroupId, ProjectId) {
    $('#history-'+UserId).load('/nonprofit/loadhistory', {NetworkId: NetworkId, UserId: UserId, ProgramId: ProgramId, GroupId: GroupId, ProjectId: ProjectId})
    $('#history-'+UserId).toggle();
}

function deleteVolunteer(VID) {
    if (confirm("Are you sure you want to delete the selected volunteer from this activity?") == true) {
        $.post('/volunteer/delete', {VolunteerId: VID}, function(data) {
            alert(data);
            window.location.reload(true);
        });
    }
    return false;
}
</script>
<style>
    .popup-box { width: 600px; left: 30%; right: 30%; top:25%; position: fixed; z-index: 999999!important; background-color:#ffffff; border:5px solid #e5e5e5; padding:10px 0 20px 0; -moz-border-radius:5px; margin:auto }
    #popup-overlay {
        background: url(<?=$this->contentLocation ?>public/images/bg-overlay.png);
        height:100%;
        position:fixed;
        display:block;
        left:0;
        top:0;
        width:100%!important;
        z-index:998;
        display:none;
    }
    .right {
        float:right;
    }
    .hidden { display:none }
</style>
<div class="add-note popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <h2>Add Volunteer Note</h2>
    <form id="add-note" onsubmit="manageNote('#add-note', 'addnote'); return false;">
        <input id="VolunteerId" type="hidden" name="VolunteerId" value="" />
        <textarea cols="60" rows="3" name="Notes" class="Notes"></textarea>
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="togglePopup('add-note', '#VolunteerId', '', '')" style="padding: 3px 15px">Cancel</a>
        &nbsp;<input type="submit" class="btn btngreen" value="Submit" />
    </form>
</div>
<div class="edit-note popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <h2>Edit Volunteer Note</h2>
    <form id="edit-note" onsubmit="manageNote('#edit-note', 'editnote'); return false;">
        <input id="VolunteerNoteId" type="hidden" name="VolunteerNoteId" value="" />
        <textarea cols="60" rows="3" name="Notes" class="Notes"></textarea>
        <div class="clear"></div><br>
        <a href="javascript:;" class="btn btngreen" onclick="togglePopup('edit-note', '#VolunteerNoteId', '', '')" style="padding: 3px 15px">Cancel</a>
        &nbsp;<input type="submit" class="btn btngreen" value="Submit" />
    </form>
</div>
<div id="popup-overlay"></div>
<div class="wrapper">
   <!-- org header -->
  <?=$this->placeholder('header') ?>
  <!-- // org header -->

  <div class="clr"></div>

  <div class="BodyCon">
    <!-- breadcrumb -->
    <?=$this->placeholder('breadcrumb') ?>
    <!-- // breadcrumb -->
    <div class="clr"></div>

    <!-- tabs -->
    <?=$this->placeholder('tabs') ?>
    <!-- // tabs -->

    <div class="mainC">
      <div class="box05">
        <div class="headingStyle02">
            Volunteers (<?=number_format($this->total_volunteers) ?>)
        </div>
        <div id="mainnotleft" style="width:100%;">
            <div class="clear"></div>
            <div class="tab-container" style="width:100%;padding-top:0;margin-left:0;">
                <div id="volunteerFilters" class="article01" style="padding-bottom:15px; border:0; display:none;">
                    <form id="filter_records" name="filter_records" method="post">
                    <span style="float:left;">
                        <div style="float: left;font-size:12px;">
                            <span style="color:#693; font-weight:bold; font-size:13px;" >Filter By:&nbsp;&nbsp;</span>
                            <?php if ($this->organization->hasPrograms == 1) { ?>
                            <select name="ProgramId" id="ProgramId" style="max-width: 260px;">
                                <option value="">Program: All</option>
                                <?php foreach($this->organization->programs as $program) { ?>
                                <option value="<?=$program->id?>" <?= isset($this->program) && $this->program->id == $program->id ? "selected" : "" ?>>Program: <?=stripslashes($program->name)?></option>
                                <?php } ?>
                            </select>
                            <?php } ?>
                        </div>
                        <?php if ($this->organization->hasGroups == 1) { ?>
                        <div style="float: left">
                            <select name="GroupId" id="GroupId" style="max-width:260px;" <?php if(!isset($_POST['ProgramId']) && $this->organization->hasPrograms == 1) { ?>class="hide"<? } ?>>
                              <option value="">Chapter: All</option>
                              <?php foreach($this->organization->groups as $group) {
                              if (isset($_POST['GroupId']) && $_POST['GroupId'] == $group->id) $selectedGroup = $group;
                              ?>
                              <option value="<?=$group->id ?>" <?=isset($_POST['GroupId']) && $_POST['GroupId'] == $group->id ? "selected" : "" ?>>Chapter: <?=stripslashes($group->name) ?></option>
                              <?php } ?>
                            </select>
                            <span id="loadingChapters" class="hide">Loading chapters ...</span>
                        </div>
                        <?php } ?>
                        <div style="float: left">
                            <select name="ProjectId" id="ProjectId" style="max-width:260px;" <?php if(!isset($_POST['GroupId']) && $this->organization->hasGroups) { ?>class="hide"<? } ?>>
                              <option value="">Activity: All</option>
                              <?php foreach($selectedGroup->initiatives as $activity) { ?>
                              <option value="<?=$activity->id ?>" <?=isset($_POST['ProjectId']) && $_POST['ProjectId'] == $activity->id ? "selected" : "" ?>><?=$activity->type == 1 ? 'Campaign: ' : 'Activity: ' ?><?=stripslashes($activity->name) ?></option>
                              <?php } ?>
                            </select>
                            <span id="loadingProjects" class="hide">Loading activities ...</span>
                        </div>
                        <input type="submit" value="Update" class="btn btngreen" style="float:left;margin:-2px 0 0 2px; " />
                        <div class="clear" style="margin-bottom:25px"></div>
                        <div class="search" style="float: left; margin:0; width: auto;">
                            <input type="text" id="search_text" name="search_text" value="<?=isset($_REQUEST['search_text']) ? $_REQUEST['search_text'] : "Search for Volunteer" ?>" style="width:250px; border:2px solid #528D19; padding:3px; float: left; color: gray; background: url(/public/images/search.gif) no-repeat 98% center" onclick="if (this.value == 'Search for Volunteer') { $('#search_text').val('') }" onblur="if (jQuery.trim(this.value) == '') { $('#search_text').val('Search for Volunteer') }" />
                            <input type="submit" value="" style="display: none">
                            <span style="float:left; margin:3px 0 0 5px;">
                                Show:
                                <select name="limit" id="limit" style="padding: 2px 2px 2px 0" onchange="this.form.submit();">
                                    <option value="10" <?=isset($_POST['limit']) && $_POST['limit'] == 10 ? "selected" : "" ?>>10</option>
                                    <option value="25" <?=isset($_POST['limit']) && $_POST['limit'] == 25 ? "selected" : "" ?>>25</option>
                                    <option value="50" <?=isset($_POST['limit']) && $_POST['limit'] == 50 ? "selected" : "" ?>>50</option>
                                    <option value="100" <?=isset($_POST['limit']) && $_POST['limit'] == 100 ? "selected" : "" ?>>100</option>
                                    <option value="" <?=isset($_POST['limit']) && $_POST['limit'] == 'All' ? "selected" : "" ?>>All</option>
                                </select>
                            </span>
                        </div>

                    </span>
                </div>
                <div class="article01" style="margin:10px 0;padding-bottom:20px;">
                    <ul id="tools-links">
                        <li><a href="javascript:;"><img src="/public/images/wrench.jpeg" style="border:1px solid #AAA;"></a>
                            <ul style="font-size:12px; font-weight:normal;">
                                <li><a href="/<?=$this->organization->urlName?>/email-volunteers?Prev=volunteers<?= isset($this->program) ? '&ProgramId='.$this->program->id : ''; ?>"><img src="/public/images/envelope.png" style="margin:3px 5px;"><span style="vertical-align:top;">Email Volunteers</span></a></li><br />
                                <li><a href="/volunteer/volunteersreport?NetworkId=<?=$this->organization->id.(isset($this->program) ? "&ProgramId=".$this->program->id : "").(isset($_REQUEST['GroupId']) ? "&GroupId=".$_REQUEST['GroupId'] : "").(isset($_REQUEST['ProjectId']) ? "&ProjectId=".$_REQUEST['ProjectId'] : "") ?>"><img src="/public/images/reports.png" style="margin:3px 5px;"><span style="vertical-align:top;margin-right:15px;">Pull Volunteer Report</span></a></li><br />
                            </ul>
                        </li>
                    </ul>
                    <div id="showFilterLink" style="float:right; margin-top:10px;"><a href="javascript:;" onclick="$('#showFilterLink').hide(); $('#volunteerFilters').show(); $('#hideFilterLink').show();" >Show Filters</a></div>
                    <div id="hideFilterLink" style="float:right; margin-top:10px;display:none;"><a href="javascript:;" onclick="$('#showFilterLink').show(); $('#volunteerFilters').hide(); $('#hideFilterLink').hide();" >Hide Filters</a></div>

                </form>
                </div>
                <?php
                foreach($this->paginator as $volunteer) {
                    $total_donation = $this->project_donations->getUserDonations($volunteer['uUserId'], $this->organization->id, isset($this->program) ? $this->program->id : '', isset($_REQUEST['GroupId']) ? $_REQUEST['GroupId'] : '');
                ?>
                <div class="article01">
                    <div class="tab-left">
                        <img src="/profile/loadimage/?UserId=<?=$volunteer['uUserId'] ?>" width="52" height="50"/>
                    </div>
                    <div class="tab-right">
                        <table width="100%">
                            <tr style="border-right: none">
                                <td valign="top" width="600px" class="tablespace">
                                    <b><a href="/<?=$volunteer['URLName'] ?>" style="color:#000;"><?=stripslashes($volunteer['FullName']) ?></a></b><br />
                                    <a href="javascript:;" onclick="loadHistory('<?=$this->organization->id?>', '<?=$volunteer['uUserId'] ?>', '<?=isset($this->program) ? $this->program->id : '' ?>', '<?=isset($_REQUEST['GroupId']) ? $_REQUEST['GroupId'] : '' ?>', '<?=isset($_REQUEST['ProjectId']) ? $_REQUEST['ProjectId'] : '' ?>')" style="margin-right:5px">&bull; History</a>
                                    <a href="javascript:;" onclick="$('#notes-<?=$volunteer['uUserId'] ?>').toggle()" style="margin-right:5px">&bull; Notes</a>
                                    <?php //if ($total_donation > 0) { ?>
                                    <a href="/<?=$this->organization->urlName?>/volunteer-donations/<?=$volunteer['uUserId'] ?>">&bull; Donation Report</a>
                                    <?php //} ?>
                                    <br />
                                    <div id="history-<?=$volunteer['uUserId'] ?>" style="display:none; margin-top:10px; margin-bottom:5px;">
                                    <!--
                                    <?php
                                    $activities_participated = $this->volunteer_class->getProjectsParticipatedByOrganization($this->organization->id, $volunteer['uUserId'], NULL, isset($this->program) ? $this->program->id : '', isset($_REQUEST['GroupId']) ? $_REQUEST['GroupId'] : '', isset($_REQUEST['ProjectId']) ? $_REQUEST['ProjectId'] : '');
                                    //foreach($activities_participated as $activity) {
                                    ?>
                                        <a href="/<?php //echo $activity['URLName'] ?>"><?php //echo stripslashes($activity['Name']) ?></a> on <?php //echo date('F d, Y', strtotime($activity['DateParticipated'])) ?><br />
                                    <?php //} ?>
                                    -->
                                    </div>
                                    <div id="notes-<?=$volunteer['uUserId'] ?>" style="display:none; margin-top:10px; margin-bottom:5px;">
                                        <a href="javascript:;" onclick="togglePopup('add-note', '#VolunteerId', '<?=$volunteer['VolunteerId'] ?>', '')">Add Note</a><br />
                                    <?php
                                    $notes = $this->volunteer_notes->getVolunteerNotes($volunteer['VolunteerId']);
                                    foreach($notes as $note) {
                                    ?>
                                        <span> - <?=stripslashes($note['Notes']) ?></span>
                                        <input type="hidden" id="hidden-note-<?=$note['VolunteerNoteId'] ?>" value="<?=stripslashes($note['Notes']) ?>" />
                                        &bull; <a href="javascript:;" onclick="togglePopup('edit-note', '#VolunteerNoteId', '<?=$note['VolunteerNoteId'] ?>', '')">Edit</a>
                                        &nbsp;&bull;&nbsp;
                                        <a href="javascript:;" onclick="deleteNote('<?=$note['VolunteerNoteId'] ?>')">Delete</a>
                                        <br>
                                    <?php } ?>
                                    </div>
                                </td>
                                <td valign="top">
                                    Volunteer&nbsp;Activities:&nbsp;<?=count($activities_participated) ?><br />
                                    Fundraised:&nbsp;<?=$this->organization->currency.number_format($total_donation) ?><br />
                                </td>
                                <?php if (isset($_REQUEST['ProjectId']) && !empty($_REQUEST['ProjectId'])) { ?>
                                <td valign="top">
                                    <span style="float:right; margin-left: 10px">
                                        <a href="javascript:;" onclick="deleteVolunteer('<?=$volunteer['VolunteerId'] ?>')"><img src="/public/images/icon_delete_grey.gif" width="10" height="10" alt="Delete Volunteer" title="Delete Volunteer" /></a>
                                    </span>
                                </td>
                                <?php } ?>
                            </tr>
                        </table>
                    </div>
                </div>
                <?php } ?>
                <div class="clear" style="margin-bottom:10px;"></div>
                <a class="btn btngreen" href="/<?=$this->organization->urlName?>">Back</a>

                <div class="clear" style="margin-bottom:10px;"></div>

                <div class="navpage">
                    <div class='s2st03' style="margin-top:10px"><?= $this->paginationControl($this->paginator, 'Sliding', '/nonprofit/new_page_selector.phtml'); ?></div>
                </div>
            </div>
        </div><!--End Main Content-->
            </div>
        </div>
        <div class="clr"></div>
        <div class="clr"></div>
    </div>
