<?php $this->headTitle("Empowered.org - Start an Organization"); ?>
<div>
    <div id="mainco2">
        <div class="roundedbox">	
            <div style="text-align:center;">
		<span style="color:#693; font-size:20px;">Your Request Was Submitted Successfully</span>
		<div class="clear"></div>
		<center><div class="info-boxes" style="float:none; font-size:14px;">We will review your request as soon as possible and then contact you to discuss your customization needs. We look forward to speaking with you and hope that we can provide you with full customization, free of charge.</div></center>
		<div class="clear"></div>
            </div>
        </div>
    </div>
