<div>
    <div id="mainco2">
        <div class="roundedbox" style="min-height:200px;padding-left:30px;padding-top:100px;">
            <center>
            <h1 style="font-size:20px">
                Hi <?=$this->userNew->firstName?>, do you want to create a new organization?
            </h1>
            <a class="btn btngreen" href="/getstarted/create-organization">Yes</a>  <a href="<?=$this->urlNext?>" class="btn btngreen">No, thanks.</a>
            </center>
        </div>
    </div>
  </div>
</div>
