<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
?>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
                <?php echo $this->placeholder('aboutus_nav'); ?>
            </div>
            <div class="rightC">
                <span class="Heading01">Humanitarian Airfare Solutions</span>

                <p class="Text17">
                    <strong>VOLUNTEERS</strong> can fundraise for airfare.<br />
                    <strong>DONORS</strong> can receive a receipt.<br />
                    <strong>ORGANIZATIONS</strong> save time and money!
                </p>
                <div class="clr"></div><br />

                <img src="<?php echo $this->contentLocation ?>public/images/marketing/create.jpg" class="left marginSide"/>
                <span class="Heading03">1. Create a Page</span>
                <p>Volunteers create custom fundraising pages under accounts set by participating organizations.</p>

                <div class="clr"></div><br /><br />

                <img src="<?php echo $this->contentLocation ?>public/images/marketing/fundraise.jpg" class="right marginSide"/>
                <span class="Heading03">2. Fundraise</span>
                <p>Volunteers raise support from friends and family via Facebook and other social media tools.</p>

                <div class="clr"></div><br /><br />

                <img src="<?php echo $this->contentLocation ?>public/images/marketing/select.jpg" class="left marginSide"/>
                <span class="Heading03">3. Select and Secure a Flight</span>
                <p>Volunteers books their ticket on <a href="http://www.flyforgood.com" target="_blank">www.flyforgood.com</a> with the money raised.</p>

                <div class="clr"></div><br />
                <div class="JoinBtn JoinBtnL"><a href="/contactus">Get Started Today</a></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>
