<?php $this->headTitle("Empowered.org: Impact"); ?>
<link href="/public/css/style2.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->contentLocation ?>public/css/coda-slider-2.1.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->contentLocation ?>public/js/jquery.easing.1.3.js" type="text/javascript" language="javascript"></script>
<script src="<?php echo $this->contentLocation ?>public/js/jquery.coda-slider-2.0.js" type="text/javascript" language="javascript"></script>
<script type="text/javascript">
    $().ready(function() {
        $('#coda-slider-1').codaSlider();
    });
    
    $().ready(function() {
        $('#coda-slider-2').codaSlider();
    });
</script>
<style>
    .panel-wrapper .TextBox { border: none }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents"> 
            <div class="leftC" style="margin-right: 40px">
				<?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC"><span class="Heading01">Impact</span><span class="Heading02">Testimonials</span>
                <div class="clr"></div><noscript>
                </noscript>

                <div class="coda-slider-wrapper">
                    <div class="coda-slider preload" id="coda-slider-1">
                        <div class="panel">
                            <div class="panel-wrapper">
                                <div class="TextBox">
									<div class="testimonialbox">
									<div class="testimonialtop"></div>
                                    <div class="testimonial T01">"Empowered.org has transformed how volunteers prepare, interact and fundraise for social action events and made our life so much easier. Thank you so much!"<br/><br /><br /></div><div class="testimonialbottom"></div>
										<br /><strong><span class="color1">Michelle Menclewicz, </span></strong><br />Director of Student Activities<br />
                                        <span class="color1"><strong>Global Brigades</strong></span>
									</div>
									<div class="testimonialbox">
									<div class="testimonialtop"></div>
                                    <div class="testimonial T01">"I can't thank the team at Empowered.org enough for making everything so easy to use. Total we recruited over 50 volunteers and raised over $49,000. Our efforts became viral! I Can't wait to use Empowered.org again."</div><div class="testimonialbottom"></div>
										<br /><strong><span class="color1">Alex Dang, </span></strong><br />Director of Operations<br />
                                        <span class="color1"><strong>Empower Partners</strong></span>
									</div>
									<div class="testimonialbox">
									<div class="testimonialtop"></div>
                                    <div class="testimonial T01">"The incredible support of Empowered.org in helping us raise donations for Japan disaster victims made a huge impact on everyone in our group. We recommend Empowered.org to groups around the world."</div><div class="testimonialbottom"></div>
										<br /><strong><span class="color1">Franciska Karsay, </span></strong><br/>Student Leader<br />
                                        <span class="color1"><strong>Thunderbird Japan Club</strong></span>
									</div>
                                </div>
                            </div>
                        </div>
                        <div class="panel">
                            <div class="panel-wrapper">
                                <div class="TextBox">
									<div class="testimonialbox">
									<div class="testimonialtop"></div>
                                    <div class="testimonial T01">"With such a communicative technical support team, I am confident that Empowered is a safe place for my brigaders to fundraise for their trip."</div><div class="testimonialbottom"></div>
										<br /><strong><span class="color1">Thupten Phuntsog, </span></strong><br />VP of Finances<br />
                                        <span class="color1"><strong>UC Irvine Public Health Brigades</strong></span>
									</div>
                                </div>
                            </div>
                        </div>
                    </div><!-- .coda-slider -->
                </div><!-- .coda-slider-wrapper -->
                <div class="clr"></div>
                <span class="Heading02">Case Studies</span>
                <div class="leftAro"></div>
                <div class="clr"></div><noscript>
                </noscript>

                <div class="coda-slider-wrapper">
                    <div class="coda-slider preload" id="coda-slider-2">
                        <div class="panel">
                            <div class="panel-wrapper">
                                <div class="case">
                                    <div class="caseContents"><img src="<?php echo $this->contentLocation ?>public/images/NewDesign/GlobalBrigades.jpg" alt=" " width="584" height="108" align="left" />
                                        <div class="clear" style="margin-bottom:20px;"></div>
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
														<tr>
															<td width="0" valign="top"><p><strong><span class="TextStyle02" style="margin-right:22px;">Organization Type:</span></strong> University Chapter<br />
                                                                    <strong><span class="TextStyle02" style="margin-right:80px;">Website:</span></strong> <a href="http://www.ucscbrigades.org/" class="linkStyle">www.ucscbrigades.org</a><br />
                                                                    <strong><span class="TextStyle02" style="margin-right:45px;">Member since:</span></strong> September 2010</p></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="padding-right:15px;"><p><strong><span class="TextStyle02">About the University Chapter</span></strong><br /> UCSC Global
			                Brigades is a chapter of the Global Brigades Inc.
			                where students join many of the universities in the 
			                holistic model approach to sustainable health and development. At UC Santa Cruz, over 200 students
			                have participated in the Medical, Dental, Water,
			                Microfinance, and Business Brigade programs in
			                Honduras and Panama since 2009 and was granted
			                the Chancelor's Achievement for Diversity award in 2010..</p></td>
                                                        </tr>
                                                    </table></td>
                                            </tr>
                                            <tr>
                                                <td><p><strong><span class="TextStyle02">Challenge</span></strong> <br />Only being active since the Fall of 2008, below list some of the challenges UCSC Global 
			            Brigades faced when starting up for the first time:</p>
                                                    <ul class="TableStyle01">
                                                        <li>- Effective awareness building</li>
                                                        <li>- Email list organization</li>
                                                        <li>- Organization for multiple trips a year</li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><br /><p><strong><span class="TextStyle02">Solution</span></strong><br />After evaluating the issues that prevented the growth and expansion of the club, the following 
			            solutions were implemented:</p>
                                                    <ul class="TableStyle01">
                                                        <li>- Integrated social media platform such as Facebook and Twitter</li>
                                                        <li>- Internal mailing system at members, volunteers, and donor levels</li>
                                                        <li>- Upcoming and Past activities organizational levels</li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><br /><p><strong><span class="TextStyle02">Results</span></strong><br />Since the chapter came on board in 2010:</p>
                                                    <ul class="TableStyle01">
                                                        <li>- Increased club members from 20 students to over 200 in less than 2 academic years</li>
                                                        <li>- Expanded from one program to five programs with fours trips planned annually</li>
                                                        <li>- Local media attention and recipient of Diversity Award through awareness building</li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><br /><p><strong><span class="TextStyle02">Testimonial</span></strong><br />
			            "Empowered.org has catered to our club as the perfect medium for group and individual fundraising. 
			            Not only has the site given us the opportunity to recruit and fundraise, but it has also served as a means 
			            for our volunteers to highlight and engage with their own greatness. So far we've recruited over 
			            90 volunteers in 2011 and raised over $100,000. Cheers to the Empowered.org Team!"</p>
                                                    <p class="TableStyle02">Tenzin Norsang<br />
			              UCSC Medical and Dental Brigades President</p></td>
                                            </tr>
                                            <tr>
                                                <td>&nbsp;</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel">
                            <div class="panel-wrapper">
                                <div class="case">
                                    <div class="caseContents"><img src="<?php echo $this->contentLocation ?>public/images/NewDesign/GlobalBrigadesLogo.jpg" alt=" " width="598" height="118" align="left" />
                                        <div class="clear" style="margin-bottom:20px;"></div>
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
                                                <td><p><strong><span class="TextStyle02">Organization Type:</span></strong>Established Non-profit<br />
                                                        <strong><span class="TextStyle02" style="margin-right:110px">Website:</span></strong> <a href="http://www.globalbrigades.org/" class="linkStyle">www.globalbrigades.org</a><br />
                                                        <strong><span class="TextStyle02" style="margin-right:75px">Member since:</span></strong>July 2010</p></td>
                                            </tr>
                                            <tr>
												<td style="width:330px; padding-right:15px;"><p><strong><span class="TextStyle02">About the Organization</span></strong><br />Being the world's largest student-led sustainable  health and development organization, Global Brigades mobilizes over 4,000  annual student and professional volunteers to participate in 9 skill-based  programs in various countries including Honduras, Panama, and Ghana.</p></td>
											</tr>
                                            <tr>
                                                <td><p><strong><span class="TextStyle02">Challenge</span></strong><br />Global Brigades was with  a well established fundraising platform before joining Empowered.  They wanted something more dynamic and social  media driven to cross-advocate for their 9 programs.  Ultimately, they wanted a multiplier effect:  when one volunteer participated, they wanted their supporters to not only donate  to them, but see what other offerings Global Brigades had in case they were  also interested in participating.  They  needed a fundraising/volunteer platform that their sister organizations in the  UK, Ireland and Switzerland could share. Lastly, they received a Google Grant  that would subsidize merchant processing, but no fundraising platform could  directly to their Google Checkout. </p>
													Other features Global Brigades was looking for:
                                                    <ul class="TableStyle01">
                                                        <li>- A  low cost solution directly to their bank account for better accounting  practices</li>
                                                        <li>- A  smart/dynamic site that displayed both upcoming and past volunteer activities</li>
                                                        <li>- A  CRM system to communicate with volunteers and donors prior to and after their  support</li>
                                                        <li>- Integrated  waiver forms for volunteers and pre/post surveying</li>
                                                        <li>- File  sharing between groups</li>
                                                        <li><br />
                                                        </li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><strong><span class="TextStyle02">Solution</span></strong><br />
                                                    <ul class="TableStyle01">
                                                        <li>- A  fundraising process directly connected to their Google Checkout account</li>
                                                        <li>- Social  media integration with Facebook, and Twitter at the group and individual level</li>
                                                        <li>- Implemented  an online waiver at Volunteer Activity sign-up and file sharing</li>
                                                        <li>- Developed  easy and manageable pages for each individual, including photos, contact  information, and personalized message</li>
                                                        <li>- CRM  tools for both volunteers and donors</li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><br /><p><strong><span class="TextStyle02">Results</span></strong><br />After switching from  their previous fundraising platform to the dynamic/social media driven  fundraising platform on Empowered.org, the following were results:</p>
                                                    <ul class="TableStyle01">
                                                        <li>- An  annual average savings of $100,000 on administrative costs to not need to hire  an additional full-time Volunteer Coordinator and IT Director. </li>
                                                        <li>- A  single fundraising and volunteer platform that their sister organizations in  Ireland, UK and Switzerland could all share which allowed them to centralize  administrative duties and reduce overhead immediately</li>
                                                        <li>- $5,900,000  in total funds collected in less than 9 months on Empowered.org that went  directly to their Google Checkout account, saving them nearly $100,000 in extra  merchant fees</li>
                                                        <li>- Expanded  from 260 to 360 university chapters throughout North America and Europe in nine  months</li>
                                                        <li>- Increased  total volunteerism year over year by 30%</li>
                                                    </ul></td>
                                            </tr>
                                            <tr>
                                                <td><br /><p><strong><span class="TextStyle02">Testimonial</span></strong><br />
													"Empowered.org has completely transformed how students  prepare, fundraise and interact before brigades. It's made connections between  brigaders and across groups possible and gives our volunteers the opportunity  to share their passion with friends and family. Empowered.org has eased the  process of organizing group travel and has made it an interactive experience for each volunteer."</p>
                                                    <p class="TableStyle02">Michelle Menclewicz<br />
			              Director of Student Affairs, Global Brigades Inc. </p>
                                                    <div class="clr"></div></td>
                                            </tr>
                                            <tr>
                                                <td>&nbsp;</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- .coda-slider -->
                </div><!-- .coda-slider-wrapper -->
                <div class="rightAro"></div>
                <div class="clr"></div>
                <br />
            </div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>
