<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
?>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
                <?php echo $this->placeholder('aboutus_nav'); ?>
            </div>
            <div class="rightC">
                <span class="Heading01">About</span>
                <img src="<?php echo $this->contentLocation ?>public/images/marketing/world.jpg" class="right" />

                <span class="Heading03">Our Mission</span>
                <p class="Text17">To empower organizations and volunteers making positive social change through practical online solutions that help them grow and become more efficient.</p>

                <span class="Heading03">Our Vision</span>
                <p class="Text17">To foster the world's social movements.<br /><br />There are currently more than 200 participating organizations from around the world (both for-profit and non-profit) utilizing our custom platform.</p>
                <div class="clr"></div><br />
                <span class="Text17"><b>*Empowered*</b> is an initiative of <b>Global Brigades</b>, a Washington-based <em>501c3</em> organization. </span>
                <div class="clr"></div><br />
                <div class="JoinBtn JoinBtnL"><a href="/contactus">Get Started Today</a></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>
