<script type="text/javascript">
$().ready(function() {
    $('#coda-slider-1').codaSlider();
});
</script>
<style>
    .TextBox { border: none; width: 740px }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents"> 
            <div class="leftC" style="margin-right: 40px">
                <?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC">
                <span class="Heading01">The Empowered Manifesto</span>
                <div class="clr"></div>

                <div class="coda-slider-wrapper">
                  <div class="coda-slider preload" id="coda-slider-1">
                    <div class="panel">
                      <div class="panel-wrapper">
                        <div class="book">
                          <div class="bookPage">
                            <p><strong>Chapter I</strong></p><br />
                            <p>The Empowered are not concerned with borders and countries, but humanity.<br /><br />
							Their impact is not measured in words and pictures, it radiates in the lives in which they touch.<br /><br />
							Their message is not self promoting, but spreads virally for the awareness of social change. <br /><br />
							When they mobilize without creed or credit, great work is done.
							</p>
                          </div>
                          <div class="bookPage">
                            <p><strong>Chapter II</strong></p><br />
                            <p>There are many names for those with similar objectives.<br /><br />  
							Trying to further distinguish, they inevitably grow closer.<br /><br />
							Social progress spreads with the nameless, working seamlessly toward their mission.<br /><br />
							Caring little for titles, the Empowered remain focused on ideal outcomes.</p>
                          </div>
                          <div class="clr"></div>
                        </div>
                      </div>
                    </div>
                    <div class="panel">
                      <div class="panel-wrapper">
                        <div class="book">
                          <div class="bookPage">
                            <p><strong>Chapter III</strong></p><br />
                            <p>The Empowered seek sustainability to pursue their passion without excess.<br /><br />
							The health of the organization comes over wealth for stakeholders.<br /><br />
							Profit is distributed to perpetuate the mission, while costs are limited to create value.<br /><br />
							Net worth is calculated by net value to the whole society.
							</p>
                          </div>
                          <div class="bookPage">
                            <p><strong>Chapter IV</strong></p><br />
                            <p>The Empowered display damaged hands to illustrate their body’s work.<br /><br />
							Without rhetoric, they work productively toward their goals.<br /><br />
							In synch with ideals, they grow stronger and multiply. <br /><br />
							Exponentially scaling, their impact remains tangible.  
							</p>
                          </div>
                          <div class="clr"></div>
                        </div>
                      </div>
                    </div>
                    <div class="panel">
                      <div class="panel-wrapper">
                        <div class="book">
                          <div class="bookPage">
                            <p><strong>Chapter V</strong></p><br />
                            <p>Seeking power is innate.<br /><br />
							The Empowered resist controlling others for personal gain,<br /><br />
							They grow stronger by uniting their community for social good.<br /><br />
							The will of society will ultimately be realized.
							</p>
                          </div>
                          <div class="bookPage">
                            <p><strong>Chapter VI</strong></p><br />
                            <p>Both integrity and corruption is within all.<br /><br />
							Solely accepting idealism, is not accepting nature.<br /><br />
							The Empowered adopt systems which provide advantage to the Just.<br /><br />
							The balance of social change will ascend to progress.</p>
                          </div>
                          <div class="clr"></div>
                        </div>
                      </div>
                    </div>
                    <div class="panel">
                      <div class="panel-wrapper">
                        <div class="book">
                          <div class="bookPage">
                            <p><strong>Chapter VII</strong></p><br />
                            <p>Disparity exists only within perception.<br /><br />
							The pursuit of equality is rooted in the acceptance of self.<br /><br />
							Without fear of judgment the Empowered are unconcerned with accumulating wealth.<br /><br />
							Content with what they have, they see no classes.
							</p>
                          </div>
                          <div class="bookPage">
                            <p><strong>Chapter VIII</strong></p><br />
                            <p>Beliefs wildly spread both love and conflict.<br /><br />
							The Empowered hold close their motives to create social change.<br /><br />
							Their actions are their evidence; words unnecessary.<br /><br />
							Great progress is made with changing conditions and respect to all culture.
							</p>
                          </div>
                          <div class="clr"></div>
                        </div>
                      </div>
                    </div>
                  </div><!-- .coda-slider -->
                </div><!-- .coda-slider-wrapper -->
            </div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>