<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
?>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
                <?php echo $this->placeholder('aboutus_nav'); ?>
            </div>
            <div class="rightC">
                <span class="Heading01">Straight Forward Pricing</span>
                <span class="Heading02">
                    $650 / Month (Discounts Available for Non-Profits)<br />
                    <span class="Text15 grey">*Zero Added Processing Fees / Cancel Anytime</span>
                </span>


                <span class="Heading03">Comes with</span>
                <ul class="servicies">
                    <li>Unlimited use of the online platform</li>
                    <li>A pro bono consultant to assist in set up and integration into existing website(s)</li>
                    <li>Attentive customer service during traditional business hours </li>
                </ul>

                <div class="clr"></div><br />
                <div class="JoinBtn JoinBtnL"><a href="/contactus">Get Started Today</a></div>
                <div class="clr"></div><br />

                <p class="Text15">
                    <b>* Paypal</b> or merchant processing fees are not included, but can be passed onto donors as mandatory or optional. See Paypal's <a href="https://www.paypal.com/webapps/mpp/merchant-fees" target="_blank" rel="nofollow">pricing page </a>
                    for most updated rates (discounts provided for larger organizations). If you do not wish to use Paypal, other options exist.
                </p>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>
