<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
?>
<div class="container" style="margin-top: -10px">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
                <?php echo $this->placeholder('aboutus_nav'); ?>
            </div>
            <div class="rightC">
                <span class="Heading01">Services</span>
                <span class="Heading02">Compare to Blackbaud's <a href="https://www.blackbaud.com/online-marketing/friends-asking-friends" target="_blank" rel="nofollow">Friends Asking Friends</a>.</span>
                <span class="Heading03">We offer</span>
                <ul class="servicies">
                    <li><b>Unlimited</b> peer to peer fundraising pages</li>
                    <li><b>Unlimited</b> fundraising campaigns</li>
                    <li><b>Unlimited</b> volunteer activities</li>
                    <li><b>Unlimited</b> chapter or group pages</li>
                    <li><b>Facebook</b> connect</li>
                    <li><b>Membership</b> functionality</li>
                    <li>Event Management functionality</li>
                    <li>Multi-layered <b>reporting</b></li>
                    <li><b>CRM</b> integration</li>
                    <li><b>Customization</b> to look like your current website</li>
                    <li><b>And too much more, so let's schedule a phone call to learn about your needs...</b></li>
                </ul>

                <div class="clr"></div><br />
                <div class="JoinBtn JoinBtnL"><a href="/contactus">Get Started Today</a></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="clear" style="margin-bottom:5px;"></div>
