<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<?php
$fbPrefix = 'prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# ' . $this->fbAppNamespace . ': http://ogp.me/ns/fb/' . $this->fbAppNamespace . '#"';
?>

<head <?php echo $fbPrefix; ?>>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headTitle(); ?>

    <?php if(!empty($this->showOpenGraphInitiativeMeta) || !empty($this->showOpenGraphProfileMeta)) {
        // Ugly hack requested
        if(!empty($this->project->organizationId) && in_array($this->project->organization->id, Project::$NETWORKS)) {
            $ogTitle = 'Students Empowering Communities';
            $ogDescription = "Help Global Brigades to empower rural communities in Honduras, Panama, and Ghana! You can make a difference in the life of a rural community member by helping Global Brigades to bring essential health and development programs to under-resourced communities. Support this initiative by clicking this link and be a part of the world's largest student-led health and development movement!";
            $ogImage = 'http://' . $_SERVER['HTTP_HOST'] . '/images/open_graph/' . rand(1,3) . '.jpg';
        } else {
            $ogTitle = stripslashes(str_replace('"', "'", $this->project->name));;
            $ogDescription = substr(str_replace("\n", ". ", stripslashes($this->project->description)), 0, 150) . '...';

            if(isset($this->project->logo->systemMediaName)) {
                $ogImage = 'http://' . $_SERVER['HTTP_HOST'] . '/public/Media/full/' . $this->project->logo->systemMediaName;
            } elseif( !empty($this->showOpenGraphProfileMeta) ) {
                $ogImage = 'http://' . $_SERVER['HTTP_HOST'] . '/profile/loadimage?UserId=' . $this->user->id;
            } else {
                $ogImage = 'https://s-static.ak.fbcdn.net/images/devsite/attachment_blank.png';
            }
        } ?>
        <meta property="fb:app_id"      content="<?php echo $this->fbAppId; ?>" />
        <?php if(!empty($this->showOpenGraphInitiativeMeta)) { ?><meta property="og:type"    content="<?php echo $this->fbAppNamespace; ?>:initiative" /><?php } ?>
        <meta property="og:url"         content="http://<?php echo $_SERVER['HTTP_HOST']; ?><?php echo $_SERVER['REQUEST_URI']; ?>" />
        <meta property="og:title"       content="<?php echo $ogTitle ?>" />
        <meta property="og:description" content="<?php echo $ogDescription; ?>" />
        <meta property="og:image"       content="<?php echo $ogImage; ?>" />
        <?php
    } ?>

    <?= $this->cssHelper('new-global'); ?>

    <?= $this->javascriptHelper('new-global'); ?>

    <?= $this->placeholder('analytics'); ?>
</head>
<body>

<?= $this->render('profile/popup_user_info.phtml'); ?>

<?= $this->render('profile/popup_user_survey.phtml'); ?>

<?= $this->placeholder('facebook_root'); ?>

<!-- content -->
<?php echo $this->layout()->content ?>
<!-- //content -->

<!-- footer -->
<?php echo $this->placeholder('footer') ?>
<!-- // footer -->

<!-- popup login -->
<?php echo $this->placeholder('popup_user') ?>
<!-- // popup login -->

<!-- popup user info -->
<?php echo $this->placeholder('popup_user_info') ?>

<!-- popup user survey -->
<?php echo $this->placeholder('popup_user_survey') ?>

</body>
</html>
