<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

require_once 'Zend/Controller/Front.php';
$front = Zend_Controller_Front::getInstance();
$controller = $front->getRequest()->getControllerName();
$action = $front->getRequest()->getActionName();
$hide_links = array('index', 'faq', 'contactus', 'benefits', 'termsandcondition', 'aboutus', 'groups', 'privacypolicy', 'profile', 'getstarted', 'error', 'tour');
?>
<html>
    <head>

        <?= $this->headTitle(); ?>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php $metaDescription = $this->headMeta(); if(empty($metaDescription)) { ?>
            <meta name="description" content="Empowered.org is the world's fastest growing social action community, giving  groups of volunteers useful tools for recruiting and fundraising, both in local communities and abroad." />
        <?php } else { ?>
            <?= $metaDescription ?>
        <?php } ?>
        <meta name="google-site-verification" content="HFymK0U8mxk974FLxIa8AFzR8ZjcT_Ks_Mumsczmf2k" />
        <meta name="msvalidate.01" content="7386726225BEA635FA5F707EA0A74BB0" />

        <link rel="canonical" href="http://<?= $_SERVER['HTTP_HOST'] ?><?= $_SERVER['REQUEST_URI'] ?>" />

        <?= $this->cssHelper(true); ?>
        <?= $this->javascriptHelper(true); ?>

        <!--[if lte IE 7.5]><link rel="stylesheet" href="/css/ie7.css" type="text/css" /><![endif]-->
        <!--[if lte IE 6.5]><link rel="stylesheet" href="/css/ie6.css" type="text/css" /><![endif]-->
        <!--[if !IE]>
        <style>
        .headerbox-menu {
            margin-top:-30px;
        }
        .headerbox {
            position:relative;
            margin-top:5px;
        }
        .headerbox .rightContainer{
            position:absolute;
            top:5px;
            right:5px;
            margin-top:9px;
        }
        </style>
        <![endif]-->
        <!--[if IE]>
        <style>
        .headerbox .logo {
            margin-top:0px;
        }
        </style>
        <![endif]-->

    <script type="text/javascript">
    var pURLName = '<?php echo isset($this->data['pURLName']) ? $this->data['pURLName'] : '' ?>';
    var sHome   = <?=(isset($this->isHomePage)) ? 'true': 'false' ?>;
    <?php if ($this->controller != 'search') { ?>
        function beginSearch() {
            var srch_txt = $('#searchfield').val().toString();
            srch_txt = srch_txt.replace(/'/g, '');
            srch_txt = srch_txt.replace(/"/g, "");
            window.location.href = '/search?&search_text='+srch_txt;
        }
    <?php } ?>
    </script>

    <?php if($this->envUsername == "admin" && $_SERVER['REQUEST_URI'] != '/index/home') { ?>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-17384953-2']);
            _gaq.push(['_trackPageview']);
            _gaq.push(['_trackPageLoadTime']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    <?php } ?>
</head>
<body <?php if(isset($this->isHomePage)) { echo 'style="background-color:#AED5F8"'; } ?>>

    <?php echo $this->placeholder('facebook_root'); ?>

    <div id="centred">
        <div class="headerbox" style="<?php echo in_array($controller, $hide_links) ? "" : (isset($this->isHomePage) ? "background-color:#AED5F8;" : "background-color:#E7E7DE;")."border:none; box-shadow:0 0 0px #fff; border-radius:0px" ?>">
            <div class="rightContainer">
                <div class="topmenu">
                    <a href="javascript:;" class="login" style="border:none;">Login</a>
                </div>
                <?php if ($this->controller != 'search') { ?>
                <form action="/search" method="post" onsubmit="beginSearch(); return false">
                    <div class="topbar_search" style="float:right; display:block; background:#FFF;">
                        <input name="search_text" type="text" class="searchbox" id="searchfield" />
                        <input type="submit" value="" class="go"  />
                    </div>
                </form>
                <?php } ?>
                <?php if (!in_array($controller, $hide_links)) { ?>
                    <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/" style="float: right; margin-right: 30px;"><img src="http://<?= $_SERVER['HTTP_HOST'] ?>/public/images/empowered-org-logo-all-grey.png" alt="Empowered.org"/></a>
                <?php } ?>
            </div>
            <?php if (in_array($controller, $hide_links)) { ?>
            <div class="logo"><a href="http://<?= $_SERVER['HTTP_HOST'] ?>/"><img src="http://<?= $_SERVER['HTTP_HOST'] ?>/public/images/<?= $this->isHomePage ? 'empowered-org-logo-blue.png' : 'empowered-org-logo-grey.png' ?>" alt="Empowered.org" width="210" height="27"/></a></div>
            <?php } ?>
            <div class="clear"></div>

            <?php echo $this->placeholder('popup_user') ?>

        </div>

        <?php echo $this->layout()->content ?>

    </div>

        <!-- footer -->
    <div id="pageFooterOuter" style="width:100%; margin-bottom:5px; <?php echo $this->controller == 'benefits' ? 'float:left; margin-top:5px' : '' ?>">
        <div id="footer" style="margin:0 auto; width:1106px;">
            <div id="footerlogo">
                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/"><img src="http://<?= $_SERVER['HTTP_HOST'] ?>/public/images/<?= $this->controller == 'index'? 'empowered-org-logo-blue.png':'empowered-org-logo-grey.png'?>" alt="Empowered.org" style="margin:4px 0 0 16px;"/></a>
            </div>
            <div id="footermenu">
                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/about-us">About Us</a> |
                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/contactus">Contact Us</a> |
                <a href="http://blog.empowered.org/">Blog</a> |
                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/privacypolicy">Privacy Policy</a> |
                <a href="http://<?= $_SERVER['HTTP_HOST'] ?>/termsandcondition">Terms of Use</a><br />
                <div id="copyrights" align="center" style="width:100%; color:#999;">
                    &copy; 2011 Empowered.org, All Rights Reserved.
                    <?php function endrendertime() {
                        $time = explode(" ", microtime());
                        $usec = (double)$time[0];
                        $sec = (double)$time[1];
                        return $sec + $usec;
                    }
                    $end = endrendertime();
                    $run = $end - $this->starttime;
                   echo "(rendered in ".substr($run, 0, 5)."s)"; ?>
                    <?php if($this->controller != 'groups') { ?>
                        <br /><span style="padding-top:2px;">Using this site constitutes acceptance of the <a href="/termsandcondition" style="padding:0; color:#999;">Terms of Use</a>.</span>
                    <?php } ?>
                </div>
            </div>
            <div id="footersocialmedia" style="float:right;">
                <div style="height:15px; width:180px; font-size:12px; margin-top:3px;" align="center">Follow Us!<br />
                    <a href="http://www.youtube.com/empoweredorg"><img src="/public/images/footer_yt.png" style="float:right;margin-right:49px;margin-top:6px;"/></a>
                    <a href="http://www.twitter.com/empoweredorg"><img src="/public/images/footer_tw.png" style="float:right;margin-right:5px;margin-top:6px;"/></a>
                    <a href="http://www.facebook.com/empoweredorg"><img src="/public/images/footer_fb.png" style="float:right;margin-right:5px;margin-top:6px;"/></a>
                </div>
            </div>
        </div>
    </div>
        <!-- e o footer -->
</body>

</html>

