<?php if ($this->pageCount > 1): ?>
<center>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="/index/filter?page=<?php echo $this->previous; ?>&type=<?=$_REQUEST['type']?>">
    &laquo; Previous
  </a>&nbsp;&nbsp;
<?php else: ?>
  <span class="disabled">&laquo; Previous</span>&nbsp;&nbsp;
<?php endif; ?>
  
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="/index/filter?page=<?=$page?>&type=<?=$_REQUEST['type']?>">
            <?php echo $page; ?>
        </a> |
    <?php else: ?>
        <?php echo $page; ?> |
    <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  &nbsp;&nbsp;<a href="/index/filter?page=<?php echo $this->next; ?>&type=<?=$_REQUEST['type']?>">
    Next &raquo;
  </a>
<?php else: ?>
  <span class="disabled">Next &raquo;</span>
<?php endif; ?>
</div>
</center>
<?php endif; ?>
