<?php if ($this->pageCount > 1): ?>
<center>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="/participating-organizations?page=<?php echo $this->previous; ?>">
    &laquo; Previous
  </a>&nbsp;&nbsp;
<?php else: ?>
  <span class="disabled">&laquo; Previous</span>&nbsp;&nbsp;
<?php endif; ?>
  
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="/participating-organizations?page=<?php echo $page; ?>">
            <?php echo $page; ?>
        </a><?php echo (count($this->pagesInRange) != $page ? " |" : "") ?>
    <?php else: ?>
        <?php echo $page.(count($this->pagesInRange) != $page ? " |" : ""); ?>
    <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="/participating-organizations?page=<?php echo $this->next; ?>">
    Next &raquo;
  </a>
<?php else: ?>
  <span class="disabled">Next &raquo;</span>
<?php endif; ?>
</div>
</center>
<?php endif; ?>
