<?php $this->headTitle("Empowered.org - Upload Chapter Banner"); ?>
<script type="text/javascript" src="<?php echo $this->contentLocation ?>public/js/jquery.Jcrop.js"></script>
<link rel="stylesheet" href="<?php echo $this->contentLocation ?>public/css/jquery.Jcrop.css" type="text/css" />
<script language="Javascript">
    <?php if ($this->action == 'crop') { ?>
    $(function(){
        $('#cropbox').Jcrop({
            aspectRatio: 0,
            onSelect: updateCoords,
	    onChange: updateCoords,
            allowResize: true,
            //allowSelect: false,
            setSelect: [ 0, 0, 600, 100 ],
            maxSize: [1045, 200], 
            trueSize: [<?php echo $this->width ?>, <?php echo $this->height ?>]
        });
    });

    function updateCoords(c) {
        $('#x').val(c.x);
        $('#y').val(c.y);
        $('#w').val(c.w);
        $('#h').val(c.h);
    };

    function checkCoords() {
        if (parseInt($('#w').val())) return true;
        alert('Please select a crop region then press submit.');
        return false;
    };
    <?php } else { ?>
    function validate() {
        if (jQuery.trim($('#GroupBanner').val()) == '') {
            error += "Please select an image to upload.<br>";
        } else {
            var image = $('#GroupBanner').val().split(".");
            var accepted_files = new Array("jpeg", "jpg", "gif");
            var extension = image[image.length-1].toLowerCase();
            if (!accepted_files.inArray(extension)) {
                error += "Please upload pictures in jpeg, gif and png format only.<br>";
            }
        }
    }
    <?php } ?>
</script>
<div>
    <div id="centred">
        <!-- main col - 100% width -->
        <div id="mainco2">
            <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
            <div class="block001">
                <div class="blst001">
                    <div class="blst002 hsp">
                        <?php if ($this->action == 'crop') { ?>
                        <h2>Crop Chapter Banner</h2>
                        <div style="border:2px solid silver; margin-bottom:20px; color:green; padding: 5px; width:300px; <?php echo isset($this->message) ? "" : "display:none" ?>"><?php echo $this->message ?></div>
                        <div style="border:2px solid silver; margin-bottom:20px; color:red; padding: 5px; width:300px; <?php echo isset($this->error) ? "" : "display:none" ?>"><?php echo $this->error ?></div>
                        <!-- upload photo form -->
                        <img src="/public/tmp/tmp_<?php echo $this->BannerMediaId ?>.jpg" id="cropbox" style="max-width:1045px" />
                        <form method="post" onsubmit="return checkCoords();">
                            <input type="hidden" id="action" name="action" value="crop" />
                            <input type="hidden" id="GroupId" name="GroupId" value="<?php echo $this->GroupId ?>" />
                            <input type="hidden" id="BannerMediaId" name="BannerMediaId" value="<?php echo $this->BannerMediaId ?>" />
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <br>
                            <input type="submit" value="Crop Image" class="btn btngreen" />
                        </form>
                        <?php } else { ?>
                        <h2>Upload Chapter Banner</h2>
                        <form method="post" enctype="multipart/form-data" onsubmit="return validate();">
                            <input type="hidden" id="action" name="action" value="upload" />
                            <input type="hidden" id="GroupId" name="GroupId" value="<?php echo $this->GroupId ?>" />
                            <strong>Select an image:</strong>
                            <div class="clear" style="margin-bottom:2px"></div>
                            <input type="file" id="GroupBanner" name="GroupBanner" />
                            <div class="clear" style="margin-bottom:5px"></div>
                            <input type="submit" value="Upload" class="btn btngreen" />
                        </form>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
            <!-- e o block001 -->
        </div>
        <!-- e o main col -->
        <span id="ctl00_ContentPHMain_lblError"></span>
        <div class="clear"></div>
    </div>
</div>

