<script type="text/javascript">
    var ctr = 0;
    $(function() {
        $('#all-donors').bind('click', function() {
            if($('#all-donors').attr('checked')) {
                $('#activities').removeAttr('checked');
                $('#donors').removeAttr('checked');
                $('#activity-list').hide();
                $('#donor-list').hide();
            }
        });
        $('#activities').bind('click', function() {
            if($('#activities').attr('checked')) {
                $('#all-donors').removeAttr('checked');
                $('#donors').removeAttr('checked');
                $('#activity-list').show();
                $('#donor-list').hide();
            }
        });
        $('#donors').bind('click', function() {
            if($('#donors').attr('checked')) {
                $('#all-donors').removeAttr('checked');
                $('#activities').removeAttr('checked');
                $('#donor-list').show();
                $('#activity-list').hide();
            }
        });
    });
    $(function() {
        $('#all-donors').bind('click', function() {
            if($('#all-donors').attr('checked')) {
                $('#activities').removeAttr('checked');
                $('#donors').removeAttr('checked');
                $('#activity-list').hide();
                $('#donor-list').hide();
            }
        });
        $('#activities').bind('click', function() {
            if($('#activities').attr('checked')) {
                $('#all-donors').removeAttr('checked');
                $('#donors').removeAttr('checked');
                $('#activity-list').show();
                $('#donor-list').hide();
            }
        });
        $('#donors').bind('click', function() {
            if($('#donors').attr('checked')) {
                $('#all-donors').removeAttr('checked');
                $('#activities').removeAttr('checked');
                $('#donor-list').show();
                $('#activity-list').hide();
            }
        });
    });

    function validateForm() {
        var error = "";
        if($('#activities').attr('checked')) {
            var sel_act = 0;
            $('#activity-list ul li input[type=checkbox]').each(function() {
                if ($(this).attr('checked')) {
                    sel_act++;
                }
            })
            if (sel_act == 0) {
                error += "Please select atleast one volunteer activity.<br>";
            }
        }
        if($('#donors').attr('checked')) {
            var sel_mem = 0;
            $('#donor-list ul li input[type=checkbox]').each(function() {
                if ($(this).attr('checked')) {
                    sel_mem++;
                }
            })
            if (sel_mem == 0) {
                error += "Please select atleast one donor.<br>";
            }
        }
        if (jQuery.trim($('#subject').val()) == "") {
            error += "Please specify a subject.<br>";
        }
        if (jQuery.trim($('#message').val()) == "") {
            error += "Please specify a message.<br>";
        }

        if (error == "") {
            return true;
        } else {
            $('#error').html(error).show();
            return false;
        }
    }

    function addFromEmail() {
        /*
        var content = '<div id="sentFrom_'+ctr+'" style="margin-top:3px;"><input type="text" name="sentFrom[]" style="width:250px;" />&nbsp;&nbsp;<a href="javascript:removeFromMail('+ctr+')">Remove</a></div>';
        $('#from-mail').append(content);
        ctr++;
         */
        var error = "";
        var emails = jQuery.trim($('#from_emails').val()).split(",");
        if (emails.length > 0) {
            for (var i = 0; i < emails.length; i++) {
                if (!validateEmail(jQuery.trim(emails[i]))) {
                    error = "Please specify a valid email address";
                    break;
                }
            }
        } else if (emails.length == 0 || jQuery.trim($('#from_emails').val()) == "") {
            error = "Please specify atleast one email to continue.";
        }
        if (error == "") {
            $.post("/group/sendemail", {GroupId: $('#GroupId').val(), FromEmails: $('#from_emails').val(), From: $('#sentFrom').val(), action: "Add Emails"}, function(data) {
                $('#from-mail').hide();
                $('#emails').html(data);
                $('#sent-mail').show();
            })
        } else {
            alert(error);
        }
        return false;
    }

    function removeFromMail(id) {
        $('#sentFrom_'+id).remove();
        ctr--;
    }

</script>
<style type="text/css">
    .send-mail .field-label {
        float:left;
        width:70px;
        margin-top:15px;
        line-height:24px;
    }
    .send-mail .field-input {
        float:left;
        width:660px;
        margin-right:100px;
        margin-top:15px;
        line-height:24px;
    }
    .send-mail .field-input span {
        margin-right:20px;
    }
    .send-mail .field-list {
        float:left;
        width:720px;
        display:none;
        margin-left:70px;
        margin-right:280px;
        margin-top:10px;
        border:1px solid #e5e5e5;
    }
    .send-mail .field-list .leftCol {
        float:left;
        width:325px;
        padding-right:15px;
        line-height:22px;
        border-right:1px solid #e5e5e5;
    }
    .send-mail .field-list .rightCol {
        float:left;
        width:325px;
        padding-left:15px;
        line-height:22px;
    }
	<?php if(isset($_REQUEST['ProjectId'])) { ?>
	#activity-list {
		display:block;
	}
	<?php } ?>
</style>
<div class="wrapper">
   <!-- org header -->
  <?=$this->placeholder('header') ?>
  <!-- // org header -->

  <div class="clr"></div>

  <div class="BodyCon">
          
    <!-- breadcrumb -->
    <?=$this->placeholder('breadcrumb') ?>
    <!-- // breadcrumb -->
    <div class="clr"></div>

    <!-- tabs -->
    <?=$this->placeholder('tabs') ?>
    <!-- // tabs -->

    <div class="mainC">
      <div class="box05">
        <div class="headingStyle02">
            Email Donors
        </div>
        <div class="send-mail">
            <div id="error" style="border:2px solid #e5e5e5; color:red; padding:5px;width:760px; display:none"></div>
            <?php if ($this->sent) { ?>
            <div style="margin:5px 0px; padding:5px; border:1px solid #93C47D; background: #D9EAD3; width:760px;"><?=$this->message ?></div>
            <?php } ?>
                            <form method="post" onsubmit="return validateForm()">
                                <input type="hidden" id="GroupId" name="GroupId" value="<?=$this->group->id?>" />
                                <input type="hidden" id="action" name="action" value="Send Email" />
                                <div class="field-label">
                                    <strong>To:</strong>
                                </div>
                                <div class="field-input">
                                    <span><input id="all-donors" type="radio" name="sendTo" value="All Donors" <?=!isset($_REQUEST['ProjectId']) ? 'checked' : ''; ?> /> All Donors</span>
                                    <span><input id="activities" type="radio" name="sendTo" value="Activity Donors" <?=isset($_REQUEST['ProjectId']) ? 'checked' : ''; ?> /> Donors of a specific Activity or Campaign</span>
                                    <span><input id="donors" type="radio" name="sendTo" value="Specific Donors" /> Specific Donors</span>
                                </div>
                                <div id="activity-list" class="field-list">
                                    <ul style="list-style:none; padding:10px; float:left">
<?php $ctr = 1;
foreach ($this->activities as $activity) { ?>
                                            <li class="<?=$ctr % 2 == 1 ? "leftCol" : "rightCol" ?>">
                                                <input type="checkbox" name="activities[]" value="<?=$activity['ProjectId'] ?>" style="width:auto;" <?=isset($_REQUEST['ProjectId']) && $_REQUEST['ProjectId'] == $activity['ProjectId'] ? 'checked' : ''; ?> />&nbsp;<?=stripslashes(strlen($activity['Name']) > 45 ? substr($activity['Name'], 0, 42) . "..." : $activity['Name']) ?>
                                            </li>
<?php $ctr++;
} ?>
                                    </ul>
                                </div>
                                <div id="donor-list" class="field-list">
                                    <ul style="list-style:none; padding:10px; float:left">
                                        <?php $ctr = 1;
                                        foreach ($this->donors as $donor) { ?>
                                            <li class="<?=$ctr % 2 == 1 ? "leftCol" : "rightCol" ?>">
                                                <input type="checkbox" name="donors[]" value="<?=$donor['SupporterEmail'] ?>" style="width:auto; line-height:14px;" />&nbsp;<?=strlen(stripslashes($donor['SupporterName'])) > 20 ? substr(stripslashes($donor['SupporterName']), 0, 20) . "..." : stripslashes($donor['SupporterName']) ?>&nbsp;&nbsp;<span style="color:#a5a5a5"><?=(strlen($donor['SupporterEmail']) > 20) ? substr($donor['SupporterEmail'], 0, 20) . "..." : $donor['SupporterEmail'] ?></span>
                                            </li>
<?php $ctr++;
} ?>
                                    </ul>
                                </div>
                                <div class="clear"></div>
                                <div class="field-label">
                                    <strong>From:</strong>
                                </div>
                                <div class="field-input" id="from-mail">
                                    <span>
                                        <select id="sentFrom" name="sentFrom" style="font-size:14px;padding:2px 1px">
<?php foreach ($this->emails as $email) { ?>
                                                <option value="<?=$email['Email'] ?>"><?=$email['Email'] ?></option>
<?php } ?>
                                        </select>
                                    </span>
                                    <a id="add-from" href="javascript:;" onclick="$('#add-from').hide(); $('#submit').hide(); $('#add-from-email').show();">Add From Email</a>
                                    <div id="add-from-email" style="margin-top:10px; display:none">
                                        <div style="border:1px solid #dcbd00; background-color:#fff7c8; padding:10px; margin-top:8px; width:484px; line-height:16px;">List the emails you want to send "from" in the box below, separated by commas. You will be sent an email to confirm yo address before you can send emails from it. <br />You must choose to Add Emails or Cancel before you can continue with sending emails.</div>
                                        <textarea id="from_emails" name="from_emails" style="width:500px; margin-bottom:8px;" rows="4" cols="40"></textarea><br>
                                        <input type="button" class="btn btngreen" value="Add Emails" onclick="return addFromEmail()" />
                                        <input type="button" class="btn btngreen" value="Cancel" onclick="$('#add-from').show(); $('#submit').show(); $('#add-from-email').hide();" />
                                    </div>
                                </div>
                                <div class="field-input" id="sent-mail" style="display:none">
                                    <div style="background-color:#D8DFEA; padding-left:5px; margin:5px 0px; width:700px;">An email has been sent to <span id="emails" style="margin-right:0px"></span>. Please click on the verification link in this email to add this email to your group's account.</div>
                                </div>
                                <div class="clear"></div>
                                <div class="field-label">
                                    <strong>Subject:</strong>
                                </div>
                                <div class="field-input">
                                    <input style="width:380px;font-size:14px;padding:2px 1px" type="text" id="subject" name="subject" value="" />
                                </div>
                                <div class="clear"></div>
                                <div class="field-label">
                                    <strong>Message:</strong>
                                </div>
                                <div class="field-input">
                                    <textarea id="message" name="message" cols="92" rows="10"></textarea>
                                </div>
                                <div id="submit" style="margin:10px 0px;margin-left:70px; width:700px; float:left">
									<?php if(isset($_REQUEST['Prev']) && $_REQUEST['Prev'] != 'home' && isset($_REQUEST['ProjectId'])) { ?>
                                    <a class="btn btngreen" style="padding:3px 15px" href="javascript:;" onclick="view_donors.submit()">Back</a>
									<?php } else { ?>
                                    <a class="btn btngreen" style="padding:3px 15px" href="/<?=$this->group->urlName ?>/donors?Prev=home">Back</a>
									<?php } ?>
                                    <input type="submit" class="btn btngreen" value="Send" />
                                </div>
                            </form>
							<?php if(isset($_REQUEST['Prev']) && $_REQUEST['Prev'] != 'home' && isset($_REQUEST['ProjectId'])) { ?>
							<form id="view_donors" name="view_donors" method="post" action="/<?=$this->group->urlName ?>/donors?Prev=<?=$_REQUEST['Prev'] ?>" style="display:none;">
                                <input type="hidden" name="ProjectId" value="<?=$_REQUEST['ProjectId']?>" />
                            </form>
							<?php } ?>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
</div>
<div class="clr"></div>
<div class="clr"></div>
</div>