<script>
function formatTitle(title, currentArray, currentIndex, currentOpts) {
    return '<div id="tip7-title">' + (title && title.length ? '<b>' + title + '</b>' : '' ) + '<br />Image ' + (currentIndex + 1) + ' of ' + currentArray.length + '</div>';
}

$(function() {
    $(".fancyPhoto").fancybox({
        'showNavArrows'  : true,
        'centerOnScroll' : true,
        'titlePosition'  : 'inside',
        'titleFormat'    : formatTitle
    });

    $('.uploadFiles').click(function() {
        $.fancybox($('.uploadFcyBx').html());
        postFiles();
    });
});

function validate() {
    var accepted_files = new Array('gif', 'jpg','JPG','jpeg','JPEG');
    var uploads = 0;
    var invalid_file = 0;
    $('#fancybox-content .multfile input[type=file]').each(function() {
        var filename = $(this).val().toString().split(".");
        var extension = filename[filename.length-1].toString();
        if (jQuery.trim($(this).val()) != '') {
            uploads++;
            if (jQuery.inArray(extension, accepted_files) < 0) {
                invalid_file++;
            }
        }
    })
    if (uploads == 0) {
        alert("Please select a file to upload.");
        return false;
    } else if (invalid_file > 0) {
        alert("Please select a valid file format");
        return false;
    } else if ($('#fancybox-content .multfile .files-1').val() == "") {
        alert("Please select a file to upload");
        return false;
    }
    return true;
}

var counter = 1;
function addFiles() {
    counter++;
    var new_photo = '<div class="new-files-'+counter+'"><input class="photo-1 fileInput" type="file" name="files[]" />&nbsp;&nbsp;<a class="desc-'+counter+'" href="javascript:;" onclick="toggleCaption(\'.caption-'+counter+'\', \'.desc-'+counter+'\')">Add Description</a>&nbsp;&nbsp;<a href="javascript:;" onclick="removeFile('+counter+').remove()">Remove</a></div>';
    new_photo += '<div class="new-files-'+counter+' caption-'+counter+' hide" style="margin-top:5px; margin-bottom:10px"><textarea class="captions-'+counter+' descInput" name="captions[]" rows="2" cols="53" style="font-size: 12px;"></textarea><div>';
    $('#fancybox-content .multfile').append(new_photo);
}

function removeFile(id) {
    $('.new-files-'+id).remove();
}

function toggleMoreLink() {
    if ($('#fancybox-content .moreUploadsLink').hasClass('hide')) {
        $('#fancybox-content .moreUploadsLink').removeClass('hide');
    }
}

function toggleCaption(div, btn) {
    $('#fancybox-content '+div).toggle();
    $('#fancybox-content '+btn).toggle();
}

// Post all files by ajax upload
function postFiles() {
    $('#fancybox-content form.uploadphoto').iframePostForm({
        json: true,
        iframeID: 'iframeUploadFiles',
        post: function () {
            var ret = validate();
            if (ret) $.fancybox.showActivity();
            return ret;
        },
        complete: function (response) {
            $.fancybox.hideActivity();
            if (!response.ok) {
                $.fancybox.hideActivity();
                $('#fancybox-content .message').html(response.err).show();
            } else {
                window.location.reload(true);
            }
            return false;
        }
    });
}
<? if ($this->isAdmin) { ?>
function deletePhoto(photoId, mediaName) {
    if (confirm('Are you sure you want to delete the photo?')) {
        $.post(
            '/photos/deletephoto',
            { PhotoId: photoId },
            function () {
                $('#'+photoId).hide();
                if ($('.deleteImg:visible').length == 0) {
                    $("#btnDownloadAlbum").hide();
                }
            }
        );
    }
}
<? } ?>
</script>


<div class="wrapper">
  <!-- org header -->
  <?= $this->placeholder('header') ?>
  <!-- // org header -->

  <div class="clr"></div>
  <div class="BodyCon">

  <!-- breadcrumb -->
  <?= $this->placeholder('breadcrumb') ?>
  <!-- // breadcrumb -->

  <div class="clr"></div>

  <!-- tabs -->
  <?= $this->placeholder('tabs') ?>
  <!-- // tabs -->

    <div class="mainC02">
    <div class="spacer"></div>
      <div class="leftC">
        <div class="leftMainBox BG01">
          <div class="box002 noMB">
            <div class="headingStyle01 BG02 rounded">All Albums</div>
            <?php if(count($this->group->initiatives)) { ?>
            <?php foreach($this->group->initiatives as $album) { ?>
            <div class="leftBox <?= isset($this->project) && $album->id == $this->project->id ? 'border01' : '' ?>">
              <a href="/<?=$album->urlName?>/photos"><p><img src="images/albumImg.jpg" alt=" " width="67" height="38" align="left" class="imgstyle4" /><?=$album->name?></p></a>
            </div>
            <?php } } else { ?>
              None Available
            <?php } ?>
          </div>
        </div>
      </div>
      <div class="rightC">
        <div class="rightMainBox BG01">
          <div class="box004">
            <div class="headingStyle02 rounded"><?= $this->project->name ?> <span class="Text14">(<?= count($this->project->photos) ?> Photos)</span></div>
            <div class="box004Content">
              <div class="clr"></div>
              <?php if(count($this->project->photos)) { ?>
              <div class="photoBox">
                <? if ($this->isLoggedIn) { ?><div class="downloadBtn"><a href="javascript:;" class="uploadFiles">Upload Photos to Album</a></div><? } ?>
                <div class="downloadBtn NoMarginLT" id="btnDownloadAlbum"><a href="/<?=$this->project->urlName?>/download-album" target="_blank">Download Album</a></div>

                <div class="spacer"></div>
                <?php foreach($this->project->photos as $photo) { ?>
                  <div class="deleteImg" id="<?=$photo->id?>">
                  <? if ($this->isAdmin) { ?>
                  <a href="javascript:deletePhoto('<?=$photo->id?>');" title="Delete Image" class="btnDelete"><img src="/public/images/cancel.png" /></a>
                  <? } ?>
                  <a class="fancyPhoto" rel="initiativeGallery" title="<?=$photo->description?>" href="/public/Photos/full/<?=$photo->systemMediaName?>"><img src="/public/Photos/thumb/<?=$photo->systemMediaName?>" class="NoMarginLT" alt=" " /></a>
                  </div>
                <?php } ?>
              </div>
              <?php } else { ?>
                  <center><strong>No photos have been uploaded for this initiative yet.</strong></center><br />
                  <? if ($this->isLoggedIn) { ?><div class="downloadBtn"><a href="javascript:;" class="uploadFiles">Upload Photos to Album</a></div><? } ?>
              <?php } ?>
              <div class="clr"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="clr"></div>
  <div class="clr"></div>
</div>


<!-- popup upload files -->
<div class="uploadFcyBx" style="display:none;">
    <h3>Upload Files</h3>
    <div>
        <span style="color:#F00;">Please select gif,jpg files that are under 2MB in size.</span><br /><br />
        <label class="message hide error"></label>
        <form class="uploadphoto" method="post" action="/<?=$this->project->urlName?>/upload-photo-album" enctype="multipart/form-data">
            <input type="hidden" name="groupId" value="<?=$this->group->id?>" />
            <div class="multfile" style="float:left; width:100%">
                <div><input class="file-0 fileInput" type="file" name="files[]" onchange="toggleMoreLink()" />&nbsp;&nbsp;<a class="desc-0" href="javascript:;" onclick="toggleCaption('.caption-0', '.desc-0')">Add Description</a></div>
                <div class="caption-0 hide" style="margin-top:5px; margin-bottom:10px">
                    <textarea name="captions[]" rows="2" cols="53" style="font-size: 12px;"></textarea>
                </div>
            </div>
            <div class="moreUploadsLink hide" style="float:left; width:100%"><a href="javascript:;" onclick="addFiles()">Attach another File</a></div>
            <input type="submit" name="submit" value="Upload" class="button" />
        </form>
    </div>
</div>
<!-- //popup upload files -->
