<?php $this->placeholder('popup_project_stop_volunteer')->captureStart(); ?>
<div id="projectVolunteerFundsFcyBx" style="display:none">
<div class="fcybxLogin">
    <p>Please do not cancel your participation before you resolved where the funds you collected are allocated</p>

    <p><strong>Are you sure you want to continue?</strong></p>

    <div class="clr"></div>
    <div class="btnCenter">
        <input type="button" value="Yes" class="btnSubmitLarge box confirm hand" />
        <input type="button" value="No" class="btnSubmitLarge box hand" />
    </div>
</div>
</div>
<?php $this->placeholder('popup_project_stop_volunteer')->captureEnd() ?>
