<?php $this->headTitle("Empowered - Account Confirmation"); ?>
		<div id="centredpp">
			<!-- block001 -->		
			<div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
			<div class="block001">
				<div class="blst001">
					<div class="blst002">
						<div class="test">
							Thank you for registering on Empowered.org.<br />
	                        We have sent you an email to <?php echo $this->email?> with a confirmation link.
	                        Please click on the link to confirm your account and get started!<br />
							<div class="clear"></div> 	
						</div>
					</div>
				</div>
				<div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
				<!-- e o block001 -->
				<div class="clear"></div>
			</div>
		</div>
