<?php $this->headTitle("Empowered.org - Create Fundraising Campaign"); ?>
<script type='text/javascript'>
    var counter = 0;
    var start_date;

    function getSuggestedAmounts() {
        var ctr = 0;
        $('#suggested-amounts .amounts .suggestedamount').each(function() {
            ctr++;
        })
        return ctr;
    }

    $(function() {
        $('#EndDate').datepicker({ changeMonth: true, changeYear: true })
                     .change(function(){
                         $(this).focus();
                     });
        $('#isfundraising01').click(function() {
            if (document.getElementById("isfundraising01").checked == true) {
                $('li.donationgoals').show();
                document.getElementById("isfundraising02").checked = false;
            }
        });
        $('.suggestedamount').keydown(function(e) {
            var keycodes = new Array('48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '8', '13');
            if (!keycodes.inArray(e.keyCode.toString())) {
                return false;
            }
        });

        //form validate
        $("#formCreateBrigade").validate({
            onfocusout: function(element) { this.element(element); },
            errorPlacement: function(error, element) {
                if (element.attr("name") == "payment_method") {
                    error.insertBefore("#errorPayment");
                } else if (element.attr("name") == "CampaignLogo") {
                    error.insertAfter("#add-photo-pop");
                } else if (element.attr("name") == "PercentageFee"){
                    $('#PassFeesDiv').append(error);
                } else {
                    error.insertAfter(element);
                }
            },
            rules: {
                CampaignLogo: {
                    accept: "jpeg|jpg|png|gif"
                },
                Name: 'required',
                Description: 'required',
                DonationGoal: {
                    required: true,
                    number: true,
                    min: 0,
                },
                /*EndDate: {
                    required: true,
                    dateFormat: true,
                },*/
<?php if ($this->data['GoogleCheckoutAccountId'] == 0 && $this->data['PaypalAccountId'] == 0) { ?>
                payment_method: 'required',
                paypalEmail: {
                    email: true
                },
                PercentageFee: {
                    required: '.pass_donations:checked',
                    number: true
                },
<?php } ?>
                isRecurring: 'required'
            },
            messages: {
                CampaignLogo: {
                    accept: 'Please upload pictures in jpeg, png and gif format only.'
                },
                Name: 'Please specify the fundraising campaign title.',
                Description: "Please specify the fundraising campaign's description.",
                DonationGoal: {
                    required: "Please specify the fundraising campaign's donation goal.",
                    number: 'Please specify a valid donation goal.',
                    min: "Please enter a positive value.",
                },
                /*EndDate: {
                    required: "Please specify the fundraising campaign's end date.",
                    dateFormat: "Please specify a valid date."
                },*/
<?php if ($this->data['GoogleCheckoutAccountId'] == 0 && $this->data['PaypalAccountId'] == 0) { ?>
                payment_method: 'Please select your desired payment processor.',
                paypalEmail: {
                    email: 'Please specify a valid email address.'
                },
                PercentageFee: {
                    required: "Please specify a percentage.",
                    number: "Please specify a valid percentage."
                },
<?php } ?>
                isRecurring: 'Please select a recurring donations option.'
            }
        });
        
        //payment methods
        $("#Paypal").change(function() {
            $("#paypal-info").show();
            $("#googlecheckout-info").hide();
        });
        
        $('#fundraising-opt span input[type=radio]').bind('click', function() {
            if ($(this).val() == 'Yes') {
                $('#Fundraising-Details').show();
            } else {
                $('#Fundraising-Details').hide();
            }
        });
    });

    function addAmount() { //needs to display data['currency'] instead of $ for suggetedamount
        var new_amount = '<li class="amount" id="sugamt_'+counter+'"><input type="text" maxlength="5" class="suggestedamount" name="suggestedamount[]" value="$" style="" onfocus="this.value = \'\';" id="inpamt_'+counter+'" /></li><li class="amtdes" id="sugdes_'+counter+'"><input type="text" class="suggestedamountdesc" name="suggestedamountdesc[]" id="inpdesc_'+counter+'" value="Description" onfocus="this.value = \'\';" ><a href="javascript:;" class="remove-amount" onclick="removeAmount('+counter+')">Remove</a></li><div class="clear"></div><div><label for="inpamt_'+counter+'" class="error errAmt" generated="false"></label><label for="inpdesc_'+counter+'" class="error errAmt" generated="false"></label></div>';
        $('#suggested-amounts .amounts').append(new_amount);
        $('#inpamt_'+counter).rules("add", {
            required: true,
            number: true,
            min: 0,
            messages: {
                required: "Please specify atleast one suggested amount donation.",
                number: "Please specify a valid suggested amount donation.",
                min: "Please enter a positive value."
            }
        });
        $('#inpdesc_'+counter).rules("add", {
            required: true,
            messages: {
                required: "Please specify the suggested amount description.",
            }
        });
        counter ++;
    }

    function removeAmount(ctr) {
        $('#inpamt_'+ctr+',#inpdesc_'+ctr).rules("remove");
        $('label[for=inpamt_'+ctr+'],label[for=inpdesc_'+ctr+']').remove();
        $('#sugamt_'+ctr).remove();
        $('#sugdes_'+ctr).remove();
        counter --;
    }

    function updateTotalBill() {
		if(jQuery.trim($('#PercentageFee').val()).match(/^\d*(\.\d{1, 2})?$/) && $('#PercentageFee').val() >= 0 && $('#PercentageFee').val() != '') {

			var percent = Number($('#PercentageFee').val());
			if ($('#PercentageFee').length > 0) {
				$('#transfee').html(Number($('#PercentageFee').val()));
			} else {
				$('#transfee').html(Number(0));
			}
			$('#FeeExplanation').show();
		}
    }
    
</script>
<style type="text/css">
    .success { color:green }
    label.error { color:red; display:block; padding: 5px 0 10px 0; }
    label.errAmt { padding:5px 0 5px 0; }
    .hidden { display:none }
    .indicator { margin:auto; font-size:20px; text-align:center; font-weight:bold; border-bottom:1px solid #e5e5e5; width:640px; padding-bottom:5px;  }
    .indicator span { color:#999898; margin-right:10px }
    .indicator span.active { color:#669933; }
    .indicator span.last { margin-right:5px }
    .details { margin:5px 0px; margin-left:20px; }
    .options { font-weight:bold; font-size:17px; }
    .icons { width:190px; float:left }
    .desc, .desc ul { width:435px; margin-left:15px; float:left }
    #paypal-info { width:100%; float:left; margin-left:15px; margin-top:-10px; margin-bottom:15px; }
    #paypal-info div { margin-bottom:3px }
    #paypal-info div span { font-weight:bold; }
    #paypal-info div input { padding:1px; width:220px }
    #googlecheckout-info { width:100%; float:left; margin-left:15px; margin-top:-10px; margin-bottom:15px; }
    #googlecheckout-info div { margin-bottom:3px }
    #googlecheckout-info div span { font-weight:bold; }
    #googlecheckout-info div input { padding:1px; width:220px }
    #googlecheckout-info div select { padding:1px; width:70px; }
    .popup-box { width: 650px; left: 30%; right: 30%; top:25%; position: fixed; z-index: 999999!important; background-color:#ffffff; border:5px solid #e5e5e5; padding:10px 0 20px 0; -moz-border-radius:5px; margin:auto }
    #popup-overlay {
        background: url(<?php echo $this->contentLocation ?>public/images/bg-overlay.png);
        height:100%;
        position:fixed;
        display:block;
        left:0;
        top:0;
        width:100%!important;
        z-index:998;
        display:none;
    }
    .right { float:right; }
</style>
<div class="paypal-find-out-more popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <div>
        <a href="https://www.paypal.com/" target="_blank">Paypal</a> is a secure online payment method, which allows you to pay or get paid quickly and easily without sharing any of your financial information.<br><br>
        Pricing: This depends on the country. Current fees:<br><br>
    </div>
    <ul style="list-style:square; margin-left:35px;">
        <li>Between 1.9 - 2.9% of the transaction value + $0.30 in the US or</li>
        <li>up to 3.4% of the transaction value + £0.20 in the UK</li>
    </ul>
    <div>
        To receive payments you can use any e-mail address. In order to access collected funds you will need to <a href="https://www.paypal.com/" target="_blank">create a PayPal account</a> with the same e-mail address.
        PayPal accepts: all major credit and debit cards as well as bank transfers and direct debit. Your members can also pay using their PayPal account balance.<br><br>
        You can often use your PayPal account balance to purchase from other websites.
    </div>
    <br><button class="btn btngreen right" onclick="$('.paypal-find-out-more').hide(); $('#popup-overlay').hide()">Close</button>
</div>
<div class="google-find-out-more popup-box hidden" style="margin-bottom:15px; margin-left:15px; padding:10px; font-size:14px">
    <div>
    <a href="http://www.googlecheckout.com" target="_blank">Google Checkout</a> is an option if you have a US or UK bank account or already use Google Checkout.<br><br>
    In order to use Google Checkout you will first need to <a href="https://checkout.google.com/sell/" target="_blank">register for a merchant account</a>. This must be linked to a bank account before you can start receiving payments. You will also need to set up payments to your account by logging in to your <a href="https://checkout.google.com/sell/settings?section=Integration" target="_blank">Google Checkout integration settings page</a> and following the instructions in the payments set-up page within your group.<br><br>
    Pricing: Depends on country:<br><br>
    </div>
    <ul style="list-style:square; margin-left:35px;">
        <li>Between 1.4 - 3.4% + £0.20 per transaction (UK)</li>
        <li>Between 1.9% - 2.9% + $0.30 per transaction (US)</li>
        (same as PayPal)
    </ul>
    <div>
    Accepts: Most credit or debit cards are accepted (except Maestro) are accepted. Google Checkout does not accept bank transfer payments.
    </div>
    <br><button class="btn btngreen right" onclick="$('.google-find-out-more').hide(); $('#popup-overlay').hide()">Close</button>
</div>
<div id="popup-overlay"></div>
<div>
    <div id="mainco2">
        <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
        <div class="block001">
            <div class="blst001">
                <div class="blst002">
                    <div class="MainBody">
                        <h2 style="font-size:14px">
                            <div style="color:#669933; width:19%; float:left">Step 1. Campaign Details</div>
                            <div style="color:#A9A9A9; width:19%; float:left">Step 2. Add Fundraisers</div>
                            <div style="color:#A9A9A9; width:19%; float:left">Step 3. Spread the Word</div>
                            <div class="clear"></div>
                        </h2>
                        <div id="TabbedPanels1" class="TabbedPanels">
                            <div class="TabbedPanelsContentGroup">
                                <div class="TabbedPanelsContent">
                                    <div id='whiteBox' class="whiteBox">
            <a id="top" href="#top" style="text-decoration:none">&nbsp;</a>
            <form name="CreateBrigade" method="post" action="" enctype="multipart/form-data" id="formCreateBrigade">
                <?php if ($this->data['GoogleCheckoutAccountId'] > 0 || $this->data['PaypalAccountId'] > 0) { ?>
                <input type="hidden" name="Currency" value="<?php echo $this->data['Currency'] ?>" />
                <input type="hidden" name="GoogleCheckoutAccountId" value="<?php echo $this->data['GoogleCheckoutAccountId'] ?>" />
                <input type="hidden" name="PaypalAccountId" value="<?php echo $this->data['PaypalAccountId'] ?>" />
                <?php } ?>
                <style>
                    .field-label { float:left; font-weight:bold; color:#000; width:200px; margin-bottom:15px;}
                    .field-input { float:left; width:455px; margin-bottom:15px; }
                    .field-input .input { width:300px; }
                    /*.field-input input { padding:1px; }*/
                    .field-input .date { width:95px; }
                    .hidden { display:none }
                    .popup-box { width: 370px; left: 40%; right: 40%; top:25%; position: absolute; z-index: 999999!important; background-color:#ffffff; border:5px solid #e5e5e5; padding:10px 0 20px 0; -moz-border-radius:7px }
                    #ui-datepicker-div { font-size:11px }
                    .amount { float:left; width:60px; margin-right:5px; }
                    .amtdes { float:left; width:300px; }
                    .amount input { width:50px; margin-bottom:3px; }
                    .amtdes input { width:235px; margin-bottom:3px; margin-right:5px; }
                </style>
                <ul style="list-style:none; padding-bottom:0px">
                    <li style="width:180px; float:left; margin-right:20px; margin-left:5px;">
						<div style=" background-color:#BDD1DE; width:105px; height:80px; padding:20px 35px; margin:0px;">
                            <div style="border:2px solid rgb(255, 255, 255); width: 100px; height: 75px; margin:0px;">
                                <img src="/public/images/addphoto.jpeg" style="width:100px; height:75px;" />
                            </div>
                        </div>
                        <div style="width:180px; float:left; margin:0px; padding:10px">
	                        <input type="file" size="12" name="CampaignLogo" id="CampaignLogo" class="textfield" /><br>
                        </div>
                    </li>
                    <li style="border-left:1px solid #e5e5e5; width:725px; float:left; padding-left:20px">
                        <h1 style="font-weight:bold">Create Fundraising Campaign</h1>
                        <div id="message" class="error" style="width:600px; border:2px solid #e3e3e3; margin-bottom:15px; padding:5px; <?php if(!$this->message) { echo "display:none;"; } ?>"><?php if(isset($this->message)) { echo $this->message; } ?></div><br />
                        <ul style="list-style:none; padding-bottom:0px; margin-bottom:0px">
                            <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Title:</li>
                            <li class="field-input">
                                <input name="Name" type="text" maxlength="50" id="Name" class="input" value="<?php echo isset($this->Name) ? $this->Name : "" ?>" />
                            </li>
                            <div class="clear"></div>
                            <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>What are you fundraising for?</li>
                            <li class="field-input">
                                <textarea class="input" name="Description" rows="4" cols="20" id="Description" onblur="return fnKeepWordLenTrack(this,3000);" onkeyup="return fnKeepWordLenTrack(this,3000);"><?php echo isset($this->Description) ? $this->Description : "" ?></textarea>
                            </li>
                            <div class="clear"></div>
                            <li class="field-label"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Donation Goal:</li>
                            <li class="field-input">
                                <input class="input" name="DonationGoal" maxlength="6" type="text" id="DonationGoal" onblur="CheckValueLimit(this,'999999');" value="<?php echo isset($this->DonationGoal) ? $this->DonationGoal : "0" ?>" />
                            </li>
                            <div class="clear"></div>
                            <li class="field-label">Suggested Amount:</li>
                            <li class="field-input">
                                <ul style="list-style:none" id="suggested-amounts">
                                    <div class="amounts"></div>
                                    <div style="width:100%; float:left; margin-bottom:3px;"><a href="javascript:addAmount()">Add Amount</a></div>
                                </ul>
                            </li>
                            <div class="clear"></div>
                            <li class="field-label" style="display:none;"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Activate Recurring Donations?</li>
                            <li class="field-input" style="display:none;">
                                <span><input type="radio" id="isRecurring01" name="isRecurring" value="Yes">&nbsp;Yes</span>
                                <span style="margin-left:10px"><input type="radio" id="isRecurring02" name="isRecurring" value="No" checked>&nbsp;No</span>
                            </li>
                            <div class="clear"></div>
                            <li class="field-label enddate"><span style="color:#F00;font-size:16px;font-weight:bold;margin-top:4px;">* </span>Fundraising Campaign Active Till:</li>
                            <li class="field-input enddate">
                                <input style="cursor: pointer" class="text smaller" name="EndDate" type="text" maxlength="10" id="EndDate" value="<?php echo isset($this->EndDate) ? $this->EndDate : "" ?>" />
                            </li>
                            <div class="clear"></div>
                            <?php if ($this->data['GoogleCheckoutAccountId'] == 0 && $this->data['PaypalAccountId'] == 0) { ?>
                            <div class="clear" style="margin-bottom:25px; padding-bottom:15px; border-bottom:1px solid #E5E5E5;"></div>
	                        <strong style="font-size:18px; color:#669933">Online Fundraising Just Became Free!</strong><br /><br />
	                        <span style="line-height:18px; font-size:15px;">
	                            Empowered.org makes it possible for you to pass your online, merchant and credit card fees off to <br /> donors during checkout. To keep Empowered alive, this includes a 1.5% contribution to help maintain <br /> the site. This process ensures that Empowered will never have any set up costs or monthly fees... EVER!
	                        </span><br /><br />
							<div class="info-boxes" style="margin-left:0; width:680px; line-height:16px;">
								<strong style="font-size:14px;">How it works:</strong><br />
								<div class="details">
									&bull; All money fundraised on Empowered goes <strong>directly</strong> to your Paypal account which ensures a safe and secure transaction. *Paypal charges between 1.9-2.9% for credit card donations.
								</div>
								<div class="details">
									&bull; You decide whether it is mandatory or optional to have your donors cover these online transaction costs. You can set the exact percentage you want.
								</div>
								<div class="details">
									&bull; If the donor pays for your transaction costs, Empowered.org will charge your merchant processor an additional 1.5% to keep the site alive.  If the donor does not, the 1.5% is waived.
								</div>
								<div class="details">
									&bull; The donor is made aware of the total contribution they are making in both the checkout process and email receipt.
								</div>
							</div>
							<div class="clear"></div>
                            <span style="font-weight:bold;text-decoration:underline;margin-bottom:12px;">Select your Fundraising Processor</span>
                            <ul style="list-style:none; width:700px; margin-top: 5px">
                                <li class="icons"><img src="<?php echo $this->contentLocation ?>public/images/paypal.png" width="150" height="75" alt=""></li>
                                <li class="desc">
                                    <input class="paypal-info" style="margin-left:-2px" type="radio" name="payment_method" value="Paypal" id="Paypal" checked> <strong>Collect payments using Paypal</strong>
                                    <ul style="list-style:disc">
                                        <li>Accept payment via credit/debit cards and Paypal accounts</li>
                                        <li>Paypal charges up to 2.9% + $0.30 per transaction</li>
                                        <li>
                                            Start collecting payments immediately!<br>
                                            <a href="javascript:;" onclick="$('#popup-overlay').show(); $('.paypal-find-out-more').show()" style="text-decoration:underline">Find out more abour Paypal</a> or <a href="https://www.paypal.com/" target="_blank" style="text-decoration:underline">learn more at Paypal.com</a>
                                        </li>
                                    </ul>
                                    <div class="info-forms" id="paypal-info">
                                        <div><span style="margin-right:5px; margin-bottom:5px">Paypal Email:</span><input type="text" id="paypalEmail" name="paypalEmail" value=""></div>
                                        <span style="margin-right:29px">Currency:</span>
                                        <select id="paypalCurrency" name="paypalCurrency">
                                            <option value="USD">USD</option>
                                            <option value="GBP">GBP</option>
                                        </select>
                                    </div>
                                </li>
                                <div class="clear"></div>
                            </ul>
                            <div class="clear" id="errorPayment"></div>
                            <span style="font-weight:bold;text-decoration:underline;margin-bottom:12px;">Let donors cover transaction fees?</span>
                            <div style="margin-bottom:25px;" id="nonprofit-option">
                                <strong style="margin-left:20px">Would you like to allow donor's to cover your transaction fees?</strong>
                                <span style="margin:0 20px"><input type="radio" name="allowPercentageFee" value="mandatory" id="pass_donations_2" onclick="$('#PassFeesDiv').show();" />&nbsp;Mandatory</span>
                                <span style="margin:0 20px 0 0"><input type="radio" name="allowPercentageFee" value="optional" id="pass_donations_1" onclick="$('#PassFeesDiv').show();" />&nbsp;Optional</span>
	                            <div class="info-boxes" style="width: auto">
	                            If you select mandatory the percentage you elect below will automatically be added to all donations you collect in <br />
	                            addition to a 1.5% Empowered contribution.  If you select optional and the donor opts out during checkout, you will <br />
	                            have to pay the Paypal fee, and Empowered will not receive its 1.5% contribution.
	                            </div>
	                            <div class="clear"></div>
                                <div id="PassFeesDiv" style="display:none;">
                                    <div class="clear" style="margin-bottom:16px;"></div>
                                    <span style="margin-left:20px">What percentage would you like added: </span>
                                    <input type="text" name="PercentageFee" id="PercentageFee" value="" onblur="updateTotalBill();" />%
                                    <label style="margin-left:20px" class="error" for="PercentageFee" generated="false"></label>
                                </div>
								<div class="info-boxes" id="FeeExplanation" style="display:none;">
									If your donor chooses not to opt out, then their total total donation will be:<br />The original donation amount <strong>+ <span id="transfee"></span>%</strong> (to cover your merchant costs) <strong>+ 1.5%</strong> (for Empowered.org)
								</div>
								<div class="clear"></div>
                            </div>
                            <?php } ?>
                            <li style="width:100%; float:left"><span style="color:#F00;font-size:16px;font-weight:bold;">*</span><span style="color:#AAA;"> denotes a required field.</span></li>
                        </ul>
                    </li>
                </ul>
                <div style="margin-left:220px; margin-top:15px; float:left; width:100%; margin-bottom:20px">
                    <a class="btn btngreen" title="Back" href="<?php echo isset($_SESSION['getstarted']) ? '/getstarted' : '/profile/campaigns' ?>">Back</a>
                    <input type="submit" class="btn btngreen" name="btnCreateNew" value="Create New" id="btnCreateNew"/>
                </div>
            </form>
            <div class="clear"></div>
        </div>
    </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
<div class="block001f01"><div class="blst001"><div class="blst002"></div></div>
