<script type='text/javascript' src='<?php echo $this->contentLocation ?>public/js/jquery-1.3.2.min.js'></script>
<link href="<?php echo $this->contentLocation ?>public/css/styles.css" rel="stylesheet" type="text/css" />
<script>
    function updateDonationGoal() {
        if (!isFloat($('#DonationGoal').val())) {
            alert('Please specify a valid amount.');
            return false;
        } else {
	    if ($('#DonationGoal').val() < $this->DonationGoal['UserDonationGoal']) {
		alert('You may only increase your donation goal.');
		return false;
	    } else {
            	return true;
	    }
        }
    }
    function isFloat(value) {
        if(value == ""){
            return false;
        }
        value = value.replace(/,/, '.');
        if(parseFloat(value) != (value*1)) {
            return false;
        }
        return true;
    }
</script>
<div>
    <div id="mainco2">
        <div class="roundedbox">
            <form method="post" action="/profile/editdonationgoal/<?php echo $this->UserId."/".$this->ProjectId ?>" onsubmit="return updateDonationGoal();">
                <input type="hidden" id="UserId" name="UserId" value="<?php echo $this->UserId ?>" />
                <input type="hidden" id="ProjectId" name="ProjectId" value="<?php echo $this->ProjectId ?>" />
                <input type="hidden" id="VolunteerId" name="VolunteerId" value="<?php echo $this->DonationGoal['VolunteerId'] ?>" />
                <div style="width:500px;">
                    <h2>Edit Donation Goal</h2>
                    <div id="message" style="border:2px solid silver; padding:5px; color:green; width:486px; <?php echo isset($this->message) ? "" : "display:none" ?>"><?php echo $this->message ?></div>
                    <div class="txt01">
                        Donation Goal: <input type="text" id="DonationGoal" name="DonationGoal" value="<?php echo $this->DonationGoal['UserDonationGoal'] ?>" />
                    </div>
                    <br><br>
                    <input type="submit" name="Submit" value="Submit">
                </div>
            </form>
            <div class="clear"></div>
        </div>
    </div>
</div>
