<?php $this->placeholder('facebook_root')->captureStart(); ?>
<div id="fb-root"></div>
<script>
window.fbAsyncInit = function() {
    FB.init({
        appId:'<?= $this->fbAppId ?>',
        channelUrl: 'http://<?php echo $_SERVER['HTTP_HOST']; ?>/public/channel.html',
        cookie:true,
        status:true,
        xfbml:true
    });
    //_ga.trackFacebook(); //Google Analytics tracking
};

//Load the SDK Asynchronously
(function(d){
   var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
   if (d.getElementById(id)) {return;}
   js = d.createElement('script'); js.id = id; js.async = true;
   js.src = "//connect.facebook.net/en_US/all.js";
   ref.parentNode.insertBefore(js, ref);
 }(document));

</script>

<?php $this->placeholder('facebook_root')->captureEnd(); ?>
