<?php $this->headTitle("Empowered.org: Request Forgotten Password"); ?>
<script type='text/javascript'>
    function validate() {
        if (jQuery.trim($('#email').val()) == '') {
            $('#errormessage').html('Please specify your email to continue.').show();
            return false;
        } else {
            return true;
        }
    }
</script>
<!-- main col - 100% width -->
<div id="mainco2">
    <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
    <div class="block001">
        <div class="blst001">
            <div class="blst002 hsp">
                <h1>Forgot Password</h1><div class="clear1"></div>
                <div id="errormessage" style="border: solid 2px silver; color: red; padding: 5px; padding-right:40px; margin-top:15px; width: 360px; <?php echo !isset($this->error_message) ? "display:none" : "" ?>"><?php echo $this->error_message ?></div>
                <div id="message" style="border: solid 2px silver; color: green; padding: 5px; padding-right:40px; margin-top:15px; width: 360px; <?php echo !isset($this->message) ? "display:none" : "" ?>"><?php echo $this->message ?></div>
                <div class="form02">
                    <form id="forgotpassword" method="post" action="/profile/forgotpassword" onsubmit="return validate()">
                        <label for="txt001">Enter your login email below:</label>
                        <input type="text" id="email" name="email" value="" style="width:200px;" class="textfield">
                        <div class="clear"></div>
                        <input type="submit" id="submit" name="submit" value="submit" class="button">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
    <!-- e o block001 -->
</div>
<!-- e o main col -->
<span id="ctl00_ContentPHMain_lblErrorMsg" class="divError"></span>
<div class="clear"></div>
