<?php $this->headTitle("Empowered.org: Reactivate User"); ?>
<!-- main col - 100% width -->
<div id="mainco2">
    <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
    <div class="block001">
        <div class="blst001">
            <div class="blst002 hsp">
                <h1>Reactivate Account</h1><div class="clear1"></div>
                <div id="message" style="border: solid 2px silver; color: green; padding: 5px; padding-right:40px; margin-top:15px;">
                    Your account was successfully reactivated.
                    Please, try to login again.
                </div><div class="clear1"></div><br /><br /><br />
                <a href="/profile/login" class="btn btngreen">Continue</a>
            </div>
        </div>
    </div>
    <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
    <!-- e o block001 -->
</div>
<!-- e o main col -->
<span id="ctl00_ContentPHMain_lblErrorMsg" class="divError"></span>
<div class="clear"></div>
