<?php
$this->placeholder('tab')->set('profile');
?>
		<div id="centredpp">
			<!-- block001 -->		
			<div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
			<div class="block001">
				<div class="blst001">
					<div class="blst002">
						<div class="test">
	                        We have sent you an email to <?php echo $this->email?> with the activation link.<br />
	                        Please click on the link to activate your account.<br />
							<div class="clear"></div> 	
						</div>
					</div>
				</div>
				<div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
				<!-- e o block001 -->
				<div class="clear"></div>
			</div>
		</div>
