<?php 
$this->placeholder('tab')->set('profile');
?>
<?php if ($this->action == "crop") { ?>
<script type="text/javascript" src="<?php echo $this->contentLocation ?>public/js/jquery.Jcrop.js"></script>
<link rel="stylesheet" href="<?php echo $this->contentLocation ?>public/css/jquery.Jcrop.css" type="text/css" />
<script type="text/javascript">
    $(function(){
        $('#cropbox').Jcrop({
            aspectRatio: 1,
            onSelect: updateCoords,
            allowResize: false,
            //allowSelect: false,
            setSelect: [ 0, 0, 100, 100 ],
            boxWidth: 0
        });
    });

    function updateCoords(c) {
        $('#x').val(c.x);
        $('#y').val(c.y);
        $('#w').val(c.w);
        $('#h').val(c.h);
    };

    function checkCoords()
    {
        if (parseInt($('#w').val())) return true;
        alert('Please select a crop region then press submit.');
        return false;
    };

</script>
<?php } ?>
<script type="text/javascript">
    function validateForm() {
        if (jQuery.trim($('#upload').val()) == '') {
            alert("Please select an image to upload.");
        } else {
            var image = $('#upload').val().split(".");
            var accepted_files = new Array("jpeg", "jpg", "JPG", "JPEG");
            if (!accepted_files.inArray(image[image.length-1])) {
                alert("Please select jpeg files only.");
            } else {
                $('#upload-image').submit();
            }
        }
    }
</script>

<div>
    <div id="centred">
        <!-- main col - 100% width -->
        <div id="mainco2">
            <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
            <div class="block001">
                <div class="blst001">
                    <div class="blst002 hsp">
                        <h1>Upload Profile Picture</h1>
                        <div style="border:2px solid silver; margin-bottom:20px; color:green; padding: 5px; width:300px; <?php echo isset($this->message) ? "" : "display:none" ?>"><?php echo $this->message ?></div>
                        <div style="border:2px solid silver; margin-bottom:20px; color:red; padding: 5px; width:300px; <?php echo isset($this->error) ? "" : "display:none" ?>"><?php echo $this->error ?></div>
                        <!-- upload photo form -->
                        <?php if ($this->action == "upload") { ?>
                        <img id="ctl00_ContentPHMain_imgUser" src="/profile/loadimage?UserId=<?php echo $this->UserId ?>" style="border-width:0px; display: block; margin-bottom: 5px;"  />
                        <form id="upload-image" method="post" action="/profile/uploadphoto/<?php echo $this->UserId ?>/<?php echo $this->from ?>" enctype="multipart/form-data">
                            <input type="hidden" id="action" name="action" value="upload_image">
                            <input type="file" id="upload" name="upload" value=""><br>
                            <a class="btn btngreen" style="padding:3px 15px;" href="/profile/edit">Back</a>
                            <input type="submit" value="Upload & Crop" class="btn btngreen" style="margin-top:5px;" onclick="validateForm(); return false;" />
                        </form>
                        <?php } else { ?>
                        <img src="<?php echo $this->image ?>" id="cropbox" />
                        <form method="post" onsubmit="return checkCoords();">
                            <input type="hidden" id="action" name="action" value="crop_image" />
                            <input type="hidden" id="UserId" name="UserId" value="<?php echo $this->UserId ?>" />
                            <input type="hidden" id="image" name="image" value="<?php echo $this->image ?>" />
                            <input type="hidden" id="ext" name="ext" value="<?php echo $this->ext ?>" />
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <br>
                            <input type="submit" value="Crop Image" class="btn btngreen" />
                        </form>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
            <!-- e o block001 -->
        </div>
        <!-- e o main col -->
        <span id="ctl00_ContentPHMain_lblError"></span>
        <div class="clear"></div>
    </div>
</div>

<?php
/*
echo (($this->width / 500) > ($this->height / 600)) ? "max-width:500; height: auto" : "max-height:600; width: auto;"
} else {
sorry * max-width:500; height: auto
} else {
max-height:600; width: auto;
}
*/
?>