  <div class="MainBody02">
    <div class="rightCon">
    <span class="Heading01">Chapter Management</span>
     <span class="Heading02">Empower multiple chapters to create change.</span>
     <div class="clear"></div>
    <div class="con01"><img src="/public/images/tour/img13.jpg" alt=" " width="456" height="281" align="right" />
      <div class="Con01Text01"><span class="heading03">All Your Chapters Organized</span><br />
        <br />
        With a multi-chaptered organizational page set up, all your various groups and programs are located in one place, letting you observe all member and donor statistics effortlessly.</div>
     </div>
    <div class="con01"><img src="/public/images/tour/img14.jpg" alt=" " width="434" height="247" align="left" />
      <div class="Con01Text02"><span class="heading03">Communicate Effectively</span><br />
        <br />
        With complete chapter and member listings, you can target and communicate with specific chapters or your entire organization, using alerts, emails and important updates in whatever way you see fit.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img15.jpg" alt=" " width="427" height="253" align="right" />
      <div class="Con01Text01"><span class="heading03">Delegate Responsibility </span><br />
        <br />
        Assign admin controls of each chapter and update them on organizational &quot;best practices&quot; to make sure each chapter within your organization can manage fundraising, coordinate activities and grow their volunteer base to reach their full potential.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img16.jpg" alt=" " width="372" height="230" align="left" />
      <div class="Con01Text02"><span class="heading03">Chapter Automation</span><br />
        <br />
        With the 'Start A Chapter' button, anyone in the world that wants to help can join your social movement where they live (pending your approval, of course) and create new chapters on behalf of your organization.</div>
    </div>
    </div>
    <div class="leftCon">
		<?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
  </div>
  <div class="clear"></div>