  <div class="MainBody02">
    <div class="rightCon">
        <span class="Heading01">Custom Solutions</span>
        <span class="Heading02">Integrate Empowered’s platform into your new or existing website.</span>
        <div class="clear"></div>
        <div class="con01"><img src="/public/images/tour/img21.png" alt=" " align="right" />
          <div class="Con01Text01" style="width:270px;font-size:1.2em;">
            <span class="heading03">Custom Integration</span><br />
            <br />
            For qualifying organizations, <strong>Empowered</strong> web consultants will work with your team to integrate the
            management and fundraising tools into your existing website and/or offer you a newly designed site at no additional cost.
            Functionality tabs can include: members, volunteers, chapters, volunteer activities, programs, events and fundraising campaigns
            and can all be designed to fit into your existing website.
          </div>
         </div>
        <div class="con01"><img src="/public/images/tour/img22.png" alt=" " align="left" />
          <div class="Con01Text02" style="width:270px;font-size:1.2em;">
            <span class="heading03">Website Maintenance and Hosting</span><br />
            <br />
            <strong>Empowered.org</strong> will maintain and host your existing website, help you make changes in content, and offer customer support
            around your IT needs.  We will make it easy for you to track, categorize and analyze all of your website’s analytics and help
            ensure you understand and maximize your organizations online strategy (powered by <strong>Google analytics</strong>).
          </div>
        </div>
        <div class="con01"><img src="/public/images/tour/img23.png" alt=" " align="right" />
          <div class="Con01Text01" style="width:270px;font-size:1.2em;">
            <span class="heading03">Facebook Integration:</span><br />
            <br />
            Benefit from increased online presence by integrating <strong>Facebook</strong> into all of your online operations. Every time someone donates,
            becomes a member, registers for an event, or otherwise engages with your organization, their <strong>Facebook</strong> profile will update
            spreading the word to all their “friends.”
          </div>
        </div>
        <div class="con01" style="font-size:1.2em;margin-top:40px;">
            <strong>Cost: $2,900</strong> (one time set up) + <strong>$500</strong>/month for maintenance + <strong>3.9%</strong> flat fee on credit card transactions with Empowered.org's merchant processing solution.
        </div>
        
        <div class="con01" style="font-size:1.2em;margin-top:40px;text-align:center;">
            <div class="JoinBtn" style="text-align:center;margin:0px auto;float:none;">
                <a href="#" id="btnApply">Apply Now</a>
            </div>
        </div>
    </div>
    
    <div class="leftCon">
		<?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
  </div>
  <div class="clear"></div>
  
  <div id="applyForm" style="display:none">
    <div style="width:400px;">
        <h2>Apply Now</h2>
        <p>
            <strong>
                Empowered's customized online solutions will significantly increase your organization's efficiency,
                online presence and overall impact.
            </strong>
            <br />
            <br />
            Fill out the brief form below and an Empowered advocate will contact you within 24 hours.
        </p>
        
        <form class="frmApply">
            <label for="apply_name" style="display:block;margin-top:15px;">Your Name</label>
            <input id="apply_name" name="apply_name" style="width:390px;" />
            
            <label for="apply_orgname" style="display:block;margin-top:15px;">Organization Name</label>
            <input id="apply_orgname" name="apply_orgname" style="width:390px;" />
            
            <label for="apply_email" style="display:block;margin-top:15px;">Email</label>
            <input id="apply_email" name="apply_email" style="width:390px;" />
            
            <label for="apply_phone" style="display:block;margin-top:15px;">Phone Number</label>
            <input id="apply_phone" name="apply_phone" style="width:390px;" />
            
            <label for="apply_funds" style="display:block;margin-top:15px;">Fundraising Details</label>
            <select id="apply_funds" name="apply_funds" style="width:390px;">
                <option value="100k-500k">$100k - $500k</option>
                <option value="500k-1million">$500k - $1 million</option>
                <option value="1-5million">$1-5 million</option>
                <option value="5-10million">$5-10 million</option>
                <option value="10million+">$10 million+</option>
            </select>
            
            <div class="JoinBtn" style="text-align:center;margin:20px auto;float:none;">
                <a id="sendForm" href="#" onclick="sendForm(); return false;">Apply</a>
            </div>
        </form>
    </div>
  </div>
  
<script type="text/javascript">
    function sendForm() {
    	$.fancybox.showActivity();

        $.ajax({
            url: '/tour/send-apply-form',
            type: 'POST',
            data: $('#fancybox-content .frmApply').serialize(),
            success: function() {
            	$.fancybox.hideActivity();
            	$.fancybox.close();
            }
        });
    }
  
    $( function() {
        $('#btnApply').click( function() {
        	$.fancybox($("#applyForm").html());
    
            return false;
        });
    });
</script>
