  <div class="MainBody02">
    <div class="rightCon">
    <span class="Heading01">Events</span>
     <span class="Heading02">Take your events to the next level.</span>
     <div class="clear"></div>
    <div class="con01"><img src="/public/images/tour/img05.jpg" alt=" " width="444" height="254" align="right" />
      <div class="Con01Text01"><span class="heading03">A Home for Events</span><br />

        Create an unlimited number of events, manage event details with ease and keep track of all events to promote to prospective members and build awareness.</div>
     </div>
    <div class="con01"><img src="/public/images/tour/img06.jpg" alt=" " width="456" height="247" align="left" />
      <div class="Con01Text02"><span class="heading03">Sell Tickets + Organize Attendance</span><br />
        <br />
        Sell tickets to attendees, use <br />
        RSVPs to simplify event <br />
        registration and organize each <br />
        individual event easily</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img07.jpg" alt=" " width="425" height="248" align="right" />
      <div class="Con01Text01"><span class="heading03">Spread the Word</span><br />
        <br />
        Every event page comes with links to Facebook, Twitter, and email, giving attendees and members more ways to keep everyone updated on upcoming events.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img08.jpg" alt=" " width="425" height="266" align="left" />
      <div class="Con01Text02"><span class="heading03">Event Success Over Time</span><br />
        <br />
        Keep all your upcoming and past events side-by-side, allowing you to easily access previous event details, attendance and successes as resources to help you improve future events.</div>
    </div>
    </div>
    <div class="leftCon">
		<?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
  </div>
  <div class="clear"></div>