  <div class="MainBody02">
    <div class="rightCon">
    <span class="Heading01">Fundraising Campaigns</span>
     <span class="Heading02">Get more out of your fundraising campaigns.</span>
     <div class="clear"></div>
    <div class="con01"><img src="/public/images/tour/img17.jpg" alt=" " width="442" height="249" align="right" />
      <div class="Con01Text01"><span class="heading03">Donor Management</span><br />
        <br />
        Keep track of your supporters with a complete donation history that tracks donation amount, destination and date and gives a unique Transaction ID every time a single donation is made.</div>
     </div>
    <div class="con01"><img src="/public/images/tour/img18.jpg" alt=" " width="435" height="268" align="left" />
      <div class="Con01Text02"><span class="heading03">Fundraising Campaigns + Personal Fundraising Pages</span><br />
        <br />
        Start a fundraising campaign for any worth-while cause or opportunity and give your supporters the ability to create personal fundraising pages on behalf of your organization to <br />
        raise more </div>
    </div>
    <div class="con01"><img src="/public/images/tour/img19.jpg" alt=" " width="455" height="283" align="right" />
      <div class="Con01Text01"><span class="heading03">Donor Reports </span><br />
        <br />
        Turn personalized donor reports or comprehensive organizational reports into a Microsoft Excel sheet with the click of a button and quickly view charts, graphs, and all important donation metrics.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img20.jpg" alt=" " width="413" height="233" align="left" />
      <div class="Con01Text02"><span class="heading03">Automatic Donor Receipts and Messaging</span><br />
        <br />
        Automatic or manual email messaging, donor receipts and personalizing &quot;Thank you&quot; letters to your supports help you express appreciation for your supporters, communicate effectively, and encourage continued support.</div>
    </div>
    </div>
    <div class="leftCon">
		<?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
  </div>
  <div class="clear"></div>