
<div class="MainBody02">
    <div class="rightCon">
        <span class="Heading01">Management</span>
        <span class="Heading02">Organize and manage every aspect of your organization.</span>
        <div class="clear"></div>
        <div class="con01">
            <img src="/public/images/tour/img09.jpg" alt=" " width="439" height="254" align="right" />
            <div class="Con01Text01">
                <span class="heading03">Who You Are</span><br /> <br />
                List all your organizational details at the
                highest-level on your org home page and instantly
                communicate who you are, what you do, and how you help.
            </div>
        </div>
        <div class="con01">
            <img src="/public/images/tour/img10.jpg" alt=" " width="432" height="248" align="left" />
            <div class="Con01Text02">
                <span class="heading03">Member Management</span><br /> <br />
                Keep track of every individual involved with your org,
                and keep the ability to email or survey existing
                members, invite or upload new members and delegate admin
                responsibilities at your discretion.
            </div>
        </div>
        <div class="con01">
            <img src="/public/images/tour/img11.jpg" alt=" " width="426" height="251" align="right" />
            <div class="Con01Text01">
                <span class="heading03">Communicate with Supporters </span><br />
                <br /> Upload photos, share stories, start blogs and
                share files, giving your organization more ways to
                communicate internally, and simultaneously share your
                impact with the world.
            </div>
        </div>
        <div class="con01">
            <img src="/public/images/tour/img12.jpg" alt=" " width="359" height="278" align="left" />
            <div class="Con01Text02">
                <span class="heading03">A Limitless History</span><br />
                <br /> Empowered tracks your impact over weeks, months,
                and years, so you can see all your member, donation, and
                activity history and track how your organization evolves
                over time.
            </div>
        </div>
    </div>
    
    <div class="leftCon">
        <?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
</div>
<div class="clear"></div>
