<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="wrapper">
  <div class="header">
    <div class="loginBtn"><a href="#">Login</a></div>
    <div class="logo3"><a href="#"></a></div>
    <div id="menu02">
      <ul>
        <li><a href="#">Benefits</a></li>
        <li><a href="#">Participating Organizations</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </div>
  </div>
  <div class="MainBody02">
    <div class="rightCon">
    <span class="Heading01">Do more for your organization and the world - with Empowered</span>
     <span class="Heading02">Every tool you need to manage your volunteers and donors, raise more and grow easily</span>
     <div class="clear"></div>
    <div class="con01"><img src="/public/images/tour/video.jpg" width="594" height="357" alt=" " /></div>
    </div>
    <div class="leftCon">
      <div class="JoinBtn"><a href="#">Join Now &gt;</a></div>
      <div class="leftSiderBar">
      <span class="leftSiderBarHeading">Tour</span>
        <ul class="leftSiderBarStyle01">
          <li class="fundraising02"><a href="fundraising-campaigns.html">Fundraising Campaigns</a></li>
          <li class="volunteer02"><a href="volunteer-activities.html">Volunteer Activities</a></li>
          <li class="events"><a href="events.html">Events</a></li>
          <li class="management"><a href="management.html">Management</a></li>
          <li class="chapter"><a href="chapter-management.html">Chapter Management</a></li>
        </ul>
        <div class="seprator"></div>
      <span class="leftSiderBarHeading">Benefits</span>
      <ul class="leftSiderBarStyle01">
        <li>Grow </li>
        <li>Efficient</li>
        <li>Save</li>
        <li>Why We're Different</li>
        <li>Pricing</li>
      </ul>
      <div class="seprator"></div>
      <span class="leftSiderBarHeading"> About Us</span>
      <ul class="leftSiderBarStyle01">
        <li>Our Story</li>
        <li>Who We Help</li>
        <li>Impact</li>
      </ul>
      <div class="seprator"></div>
      <span class="leftSiderBarHeading"> Register for a Live Demo</span>Pick a time
      <div class="clr"></div>
      <div class="dateBox"><span class="Text10">AUG 24</span><br />
        12pm EST </div>
      <div class="dateBox"><span class="Text10">AUG 24</span><br />
        12pm EST </div>
      <div class="dateBox"><span class="Text10">AUG 24</span><br />
        12pm EST </div>
       <div class="clr"></div>
       <p><a href="#" class="Text10">Choose a different time </a>
       </p>
       <div class="clr"></div>
        <label for="textfield">Name</label>
         <input name="textfield" type="text" class="textfield001" id="textfield" />
         <div class="clr"></div>
        <label for="textfield">Email </label>
         <input name="textfield" type="text" class="textfield001" id="textfield" />
        <div class="clr"></div>
        <div class="registerBtn"><a href="#">Register</a></div>
      <span class="Text10">View our <a href="#">privacy policy</a></span></div>
    </div>
  </div>
  <div class="footerLink">
    <div class="footerLogo"><a href="#"></a></div>
    <ul>
      <li><a href="#">About Us</a></li>
      <li><a href="#"> Contact Us</a></li>
      <li><a href="#"> Blog</a></li>
      <li><a href="#"> FAQ</a></li>
      <li><a href="#"> Private Policy </a></li>
      <li><a href="#">Terms of Use</a></li>
    </ul>
    <div class="socialNets"><a href="#F"></a><a href="#T"></a><a href="#M"></a></div>
  </div>
  <div class="copyright">© 2011 Empowered.org, All Rights Reserved. (rendered in 1.829s)	Using this site constitutes acceptance of the Terms of Use</div>
</div>
</body>
</html>
