  <div class="MainBody02">
    <div class="rightCon">
    <span class="Heading01">Volunteer Activities</span>
     <span class="Heading02">Give volunteers more opportunities to create change.</span>
     <div class="clear"></div>
    <div class="con01">
     <img src="/public/images/tour/img01.png" alt=" " width="450" height="249" align="right" />
     <div class="Con01Text01"><span class="heading03">Manage Volunteer<br />
        Activities and<br />
        Volunteers</span><br />

        <br />
        Keep track of all participants, send email updates, keep notes, upload files, and share key information about every individual opportunity to coordinate and sort all your actions. </div>
     </div>
    <div class="con01">
      <img src="/public/images/tour/img02.jpg" alt=" " width="437" height="269" align="left" />
      <div class="Con01Text02"><span class="heading03">Volunteers Fundraising Ability</span><br />
        <br />
        Every member that participates in a volunteer opportunity can create personalized fundraising campaigns to fundrise directly for each individual opportunity, using photos, stories and a personalized touch to drive support.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img03.png" alt=" " width="405" height="270" align="right" />
      <div class="Con01Text01"><span class="heading03">Simplified Registration</span><br />
        <br />
        Track registration of all opportunities (past and present), send liability waivers to accelerate getting started and share surveys that let you communicate and evaluate with volunteers effectively.</div>
    </div>
    <div class="con01"><img src="/public/images/tour/img04.jpg" alt=" " width="399" height="226" align="left" />
      <div class="Con01Text02"><span class="heading03">Spread the Word</span><br />
        <br />
        Every volunteer activity page comes with links to Facebook, Twitter, and email, giving volunteers more ways to keep everyone updated on upcoming activities.</div>
    </div>
    </div>
    <div class="leftCon">
		<?php echo $this->placeholder('left_tour_nav'); ?>
    </div>
  </div>
  <div class="clear"></div>