<?php
$this->headTitle("Empowered.org:  Empowering groups of volunteers to create social change");
$this->placeholder('tab')->set('');
?>
<div>
    <div id="centred">
        <!-- main col -->
        <div id="mainco2">
            <!-- block001 -->
            <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
            <div class="block001">
                <div class="blst001">
                    <div class="blst002">
                        <h1 style="padding:0; border-bottom:1px solid #E5E5E5; margin-bottom:12px;">Terms and Conditions of Use</h1>
                        <p style="text-align:justify; padding:5px 50px 20px 50px; line-height:1.5em">
                                    <span style="font-weight:bold;">Updated 6/11/2013</span>
        <br><br>
        Welcome to Empowered.org’s (Empowered.org) website (“the Website”).  The following Terms and Conditions govern your use of this Website.  Please take a few minutes to review them.  They describe your rights and responsibilities and what you can expect from Empowered.org as you use this Website.  Your use of the Website constitutes your agreement to be bound by these Terms and Conditions.  Empowered.org reserves the right to change these Terms and Conditions at any time without prior notice.  As such, you should check these Terms and Conditions from time to time for changes.
        <br><br>
        WHEN YOU ACCESS OUR WEBSITE, YOU AGREE TO THESE TERMS AND CONDITIONS OF USE.  IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS OF USE, OR TO ANY CHANGES WE MAY SUBSEQUENTLY MAKE TO THEM, IMMEDIATELY STOP ACCESSING OUR WEBSITE. FOR PARTICIPATING ORGANIZATIONS, WE CAN CUSTOMIZE THESE TERMS FOR YOUR SPECIAL NEEDS.
        <br><br>
        Empowered.org reserves the right to take steps to block access to our Website by any person or entity or remove any user accounts from our Website for any reason, including, but not limited to violation of these Terms of Use.
        <br><br>
        <strong style="font-size:14px;">Website Use Provisions</strong>
        <br><br>
        The mission of Empowered.org is to empower groups to mobilize for their desired social change. From small grass-roots clubs to complex international organizations, Empowered.org provides a flexible platform to fundraise, recruit/coordinate volunteers, and create awareness for international service. As part of that effort, Empowered.org directs money to the participating organizations’ merchant processor to fund activities designated by the donor (or users of the site).  Empowered.org does not charge any set up costs or monthly fees, but if you elect to fundraise money on the Website we may receive a small percentage of each donation to administer and improve the Website if the donor elects to contribute to cover the online transactions.  Empowered.org is wholly-owned by Global Brigades Ventures, a California Public Benefit Corporation.  For more information, visit <a href="http://www.globalbrigades.org" target="_blank">www.globalbrigades.org.</a>
        <br><br>
        Permission to use content, documents and related graphics delivered from this Website is restricted.  You may access, use and copy information and materials available through this Website only for purposes of considering and/or participating on initiatives that are facilitated through Empowered.org posted by the participating organizations; and you may only use with the consent of the organization/group associated with the content.  That information and those materials, including pages and content, may not be copied, distributed, modified, published, or transmitted in any other manner, including for use in creative work or to sell or promote other products or services.  Violation of this policy may result in infringement of Empowered.org’s or other third parties’ intellectual property and contractual rights which are protected by domestic, state and federal law and international law and treaties and could result in substantial civil and criminal penalties.
        <br><br>
        When retrieving information from our Website, you are prohibited from (1) using or attempting to use spiders, robots, avatars, intelligent agents, or any other extraction or navigation search except for a normal browser; (2) aggregating, copying or duplicating any of the materials or information available from the Website except for the reasonable amount of materials and information temporarily required for an ordinary single use of the site; or (3) accessing data not intended for legitimate use of the Website for the purposes stated above.
        <br><br>
        <strong style="font-size:14px;">Copyright/Trademark Information</strong>
        <br><br>
        This entire Website, copy, images, logos, indicia, text, and all content therein is copyright 2011 Global Brigades Association.  All third-party trademarks, copy, images, logos, indicia, text and all other content appearing on this Website are hereby acknowledged by the respective participating organizations.  Empowered.org™, Global Brigades™, and any variation of them, are trademarks of Global Brigades Association or third party providers and may not be used without written permission.
        <br><br>
        <strong style="font-size:14px;">Submissions</strong>
        <br><br>
        We welcome your comments regarding this Website.  However, any comments, feedback, notes, messages, ideas, suggestions or other communications (collectively, "Comments") directed to Empowered.org will be and remain Empowered.org’s exclusive property.  This does not include comments directed to participating organizations. Your submission of any such Comments directed to Empowered.org, constitutes an assignment to Empowered.org of all right, title and interest in and to all copyright and other intellectual property rights in the Comments.  By registering with the Website, you certify that the information you provide through registration is accurate and pertains only to you.  You are responsible for maintaining the confidentiality of your log-in information and the password you are assigned.  Your password may not be shared with any other person.
        <br><br>
        Though we take commercially reasonable steps to protect the security of the Website, we don’t control all access channels to it.  Accordingly, you acknowledge that any information you put into any field on the Website might be publicly accessible at any time during transmission.  We are not liable for protection of privacy of any information transferred to us over the Internet until it enters our systems.
        <br><br>
        <strong style="font-size:14px;">Communication from Empowered.org</strong>
        <br><br>
        When registering on our Website, we reserve the right to email you alerts and special notices that we believe may be of interest to you.  We respect your right not to receive these communications and if any time you tell us you don’t want to receive them, we’ll disable that functionality for your account.  Each of these communications will contain a clear link to Unsubscribe.  When you unsubscribe, we will remove your name from the communication list and will no longer send you these alerts and special notices, unless you choose to re-subscribe at a later date.  To unsubscribe, email admin@Empowered.org and put Unsubscribe in the subject line.
        <br><br>
        <strong style="font-size:14px;">Interactive Material</strong>
        <br><br>
        Most portions of this Website allow users to post their own material.  Materials posted by users do not necessarily reflect the views of Empowered.org, or other participating organizations, groups, and volunteers.  By posting materials to this Website, you represent that you have all the necessary right in and to such materials, and that such materials will not violate or infringe any personal or intellectual property rights of any third parties, nor will such materials be harmful, defamatory, unlawful, threatening, obscene lewd lascivious, harassing or otherwise objectionable.  By posting materials to this Website, you authorize Empowered.org and any affiliated organization or group to use, and authorize others to use, any such materials in any manner or medium.
        <br><br>
        EMPOWERED.ORG AND ALL PARTICIPATING ORGANIZATIONS AND GROUPS EXPRESSLY DISCLAIM ANY RESPONSIBILITY OR LIABILITY FOR ANY MATERIAL COMMUNICATED BY THIRD PARTIES THROUGH THIS WEBSITE.
        <br><br>
        You may not advertise or solicit on this Website without the express written permission of Empowered.org.
        <br><br>
        <strong style="font-size:14px;">External Links</strong>
        <br><br>
        Links to other websites do not imply an endorsement of the materials disseminated at those sites, nor does the existence of a link to another site imply that the organization or person publishing at that site endorses any of the materials on this site.  Links to other websites are provided by Empowered.org as a convenience to its users; Empowered.org is not responsible for the content contained on any website linked to this site.
        <br><br>
        <strong style="font-size:14px;">Correction of Errors and Inaccuracies</strong>
        <br><br>
        While Empowered.org makes every reasonable effort to present accurate information on this Website, the information here may sometimes contain typographical errors or inaccuracies and may not be complete or current.  We reserve the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice to you (including after you have submitted your information).  Such errors, inaccuracies or omissions may relate to group or project description, cost information and availability.  We apologize for any inconvenience this may cause you.
        <br><br>
        <strong style="font-size:14px;">Indemnification</strong>
        <br><br>
        By using the Website you agree to indemnify and hold Global Brigades Ventures, Global Brigades1 and/or Empowered.org and its employees, representatives, agents, affiliates, directors, officers, managers and shareholders (the "Parties") harmless from any damage, loss, or expense (including without limitation, attorneys' fees and costs) incurred in connection with any third party claim, demand or action ("Claim") brought against any of the Parties alleging that you have breached any of these Terms and Conditions.  Empowered.org will have the right to control the defense, settlement, and resolution of any such Claim at your sole expense.  You may not settle or otherwise resolve any Claim without Empowered.org’s express written permission.
        <br><br>
        <strong style="font-size:14px;">Warranty and Limitation of Liability</strong>
        <br><br>
        Empowered.org makes no guarantee or warranty, express or implied, as to the reliability, accuracy, timeliness or completeness of the information on this Website and is not responsible for any errors or omissions in it, whether caused by the source of the information or Empowered.org.
        <br><br>
        ALL INFORMATION THIS WEBSITE IS PROVIDED "AS IS, WHERE IS," AND WITHOUT WARRANTY OF ANY KIND, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF TITLE, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL EMPOWERED.ORG OR ANY AFFILIATED ORGANIZATION OR PERSON (“AFFILIATE”) BE LIABLE FOR DAMAGES TO YOU OR ANY THIRD PARTY FOR ANY MATTER ARISING OUT OF OR IN RELATION TO YOUR USE OF THIS WEBSITE OR ANY INFORMATION CONTAINED IN IT.
        <br><br>
        IN NO EVENT WILL GLOBAL BRIGADES VENTURES, GLOBAL BRIGADES, EMPOWERED.ORG OR ANY AFFILIATE BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN RELATION TO YOUR USE OF THIS WEBSITE, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF DATA, OR LOSS OF BUSINESS OR PROFITS.  SOME LOCALITIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.
        <br><br>
        <strong style="font-size:14px;">General Terms</strong>
        <br><br>
        No failure or delay by Empowered.org in exercising any right, power or privilege under these Terms and Conditions will operate as a waiver thereof, nor will any single or partial exercise of any right, power or privilege preclude any other or further exercise thereof or the exercise of any other such right, power, or privilege.  The invalidity or unenforceability of any provision of these Terms and Conditions will not affect the validity or enforceability of any other provision of these Terms and Conditions, all of which will remain in full force and effect.
        <br><br>
        These Terms and Conditions will bind Empowered.org, its Affiliates, and you, and each such person’s or entity’s successors and assigns, and will be governed by and construed in accordance with the laws of Nevada without reference to conflict of law principles.  These Terms and Conditions contain the entire understanding of the parties regarding their subject matter and supersede all prior and contemporaneous agreements and understandings between the parties pertaining thereto.
        <br><br><br>
        Copyright 2011 Global Brigades Association.  All rights reserved.
        <br /><br />
        1* “Global Brigades” refers to one or more of Global Brigades Association, “Global Brigades USA,” “Global Brigades ASG,” “Global Brigades Ireland,” or “Global Brigades UK.” Each of "Global Brigades Association" “Global Brigades USA,” “Global Brigades ASG,” “Global Brigades Ireland,” “Global Brigades UK,” “Global Brigades Ghana,” “Asociacion Global Brigadas de Honduras,” Fundacion Brigadas Globales de Panama,” and Fundacion Brigadas Globales de Nicaragua, as separate and independent legal entities.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="block001f01">
                    <div class="blst001">
                        <div class="blst002"></div>
                    </div>
                </div>
                <!-- e o block001 -->
            </div>
        </div>
        <!-- e o main col -->
        <div class="clear"></div>
    </div>
</div>
