<?php $this->headTitle("Empowered.org - Survey"); ?>
<script type="text/javascript" language="javascript">
    function filterfeedbacks() {
        $('#rows').load("/survey/filterfeedbacks", {UserId: $('#RespondentId').val(), SurveyId: $('#SurveyId').val()});
    }
</script>
<style type="text/css">
    .success { color:green }
    .error { color:red }
    table tr td.header { font-size:15px; font-weight:bold; text-align:center; padding:5px }
    table tr td.rows { font-size:13px; padding:5px; border-top:none }
    table tr td { border:1px solid #aaa; border-right:none }
    table tr td.last { border-right:1px solid #aaa }
</style>

<div id="mainco2">
    <div class="roundedbox">
        <a id="top" href="#top" style="text-decoration:none">&nbsp;</a>
        <h2>
            Edit Survey Responses
            <?php if (count($this->respondents) && $this->filter) { ?>
            <div style="float:right">
                <strong style="color:#000; font-size:14px;">Filter By Respondent:</strong>&nbsp;
                <select id="RespondentId" style="padding: 2px" onchange="filterfeedbacks()">
                    <option selected value="0">All</option>
                    <?php foreach ($this->respondents as $respondent) { ?>
                    <option value="<?php echo $respondent['UserId'] ?>" <?php $respondent['UserId'] ?>><?php echo stripslashes($respondent['FullName']) ?></option>
                    <?php } ?>
                </select>
            </div>
            <?php } ?>
        </h2>
        <div class="clear"></div>
        <div id="message" class="success" style=" border:2px solid #e3e3e3; margin-bottom:15px; padding:5px; width:475px; <?php if(!$this->message) { echo "display:none;"; } ?>">
            <?php if(isset($this->message)) { echo $this->message; } ?>
        </div>
        <form method="post" action="/survey/edit-responses/<?php echo $this->SurveyId ?>">
            <input type="hidden" id="SurveyId" name="SurveyId" value="<?php echo $this->SurveyId ?>" />
            <table style="width:1040px; margin:auto" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <td class="header">Answered By</td>
                        <td class="header">Question</td>
                        <td class="header last">Feedback</td>
                    </tr>
                </thead>
                <tbody id="rows">
                    <?php foreach($this->feedbacks as $feedback) { ?>
                    <tr>
                        <td class="rows" style="width:200px">&nbsp;<?php echo stripslashes($feedback['FullName']) ?></td>
                        <td class="rows" style="width:420px">&nbsp;<?php echo stripslashes($feedback['Question']) ?></td>
                        <td class="rows last" style="width:420px"><textarea cols="52" rows="2" name="survey_feedback[<?php echo $feedback['SurveyFeedbackId'] ?>]"><?php echo stripslashes($feedback['Answer']) ?></textarea></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <div class="clear" style="margin-top:5px"></div>
			<?php if(isset($this->prev)) { if($this->prev == 'profile') { ?>
            	<a class="btn btngreen" style="padding:3px 15px; margin-left:20px; margin-top:5px" href="/<?=$this->userNew->urlName?>">Back</a>&nbsp;
			<?php } else if ($this->prev == 'group') { ?>
            	<a class="btn btngreen" style="padding:3px 15px; margin-left:20px; margin-top:5px" href="/<?php echo $this->siteInfo['URLName'] ?>/manage-surveys">Back</a>&nbsp;
			<?php } else if ($this->prev == 'organization') { ?>
	            <a class="btn btngreen" style="padding:3px 15px; margin-left:20px; margin-top:5px" href="/<?php echo $this->siteInfo['URLName'] ?>/manage-surveys">Back</a>&nbsp;
			<?php } } ?>
            <input class="btn btngreen" type="submit" value="Submit" />
        </form>
        <div class="clear"></div>
    </div>
</div>