<?php
$this->headTitle("Empowered.org:  Empowering groups of volunteers to create social change");
?>

<div id="mainco2">
    <!-- block001 -->
    <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
    <div class="block001">
        <div class="blst001">
            <div class="blst002 hsp">
                <h2>Donation Canceled</h2>
                <p style="font-size:15px">You had canceled the payment confirmation process on Paypal.</p><br>
                <a class="btn btngreen" href="/<?php echo $this->data['pURLName'] ?>/donate">Back</a>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
    <!-- e o block001 -->
</div>