<?php $this->placeholder('header')->captureStart() ?>
<div class="banner">
<!-- login link -->
<?php echo $this->placeholder('login_link') ?>
<!-- //login link -->

<? if (isset($this->group)) { ?>

<?if ($this->siteBanner) {?>
<style>
div.banner {
  background: url(<?=$this->siteBanner['path']?>) no-repeat;
  -moz-border-radius:10px 10px 0 0;
  -webkit-border-radius:10px 10px 0 0;
  border-radius:10px 10px 0 0;
}
</style>
<? } else if (isset($this->group->logo->systemMediaName)) { ?>
  <div id="bannerLogo"><img src="<?=$this->contentLocation ?>public/Media/full/<?=$this->group->logo->systemMediaName?>" /></div> <h1><?=stripslashes($this->group->name)?></h1>
<? } else { ?>
  <div id="bannerLogo"></div><h1><?=stripslashes($this->group->name)?></h1>
<? } ?>
<style>
<?=$this->group->organization->cssStyles;?>
</style>
<? } else { ?>
<div id="bannerLogo"></div><h1><?=stripslashes($this->event->title)?></h1>
<? } ?>

</div>
<div class="clr"></div>
<?php $this->placeholder('header')->captureEnd() ?>
