<?php $this->placeholder('tool_box')->captureStart() ?>
<div class="adminPanelCon">
  <div class="adminPanel">
    <h1><span></span>Tools</h1>
    <div class="tool-box-content">
      <ul>
        <li><a class="editDetails" href="/event/edit?EventId=<?=$this->event->id?>" onclick=""><span style="vertical-align:top;">Edit Details</span></a></li>
      </ul>
      <div class="adminPanelSeprator"></div>
      <ul>
        <li><a href="javascript:;" onclick="deleteEvent()"><span style="vertical-align:top;">Delete Event</span></a></li>
      </ul>
    </div>
  </div>
</div>

<?php echo $this->placeholder('popup_upload_logo') ?>
<?php $this->placeholder('tool_box')->captureEnd() ?>
