<?php
$this->headTitle("Empowered.org - Manage Photos");
?>
<script type='text/javascript' src='<?php echo $this->contentLocation ?>public/js/CalendarControl.js'></script>
<link rel="stylesheet" href="<?php echo $this->contentLocation ?>public/css/CalendarControl.css" type="text/css" media="screen" />
<script type="text/javascript" language="javascript">
    function getForm(form, id) {
        if (form == 'add') {
            $('#form').load('/media/add', {form:'add', SiteId: id, Type: $('#Type').val()});
        }
    }

    function deletePhoto() {
        var deleted = 0;
        $('#media-list tr td input[type=checkbox]').each(function(){
            var chkbox = $(this).attr('name');
            var media_id = chkbox.split('_');
            if (document.getElementById(chkbox).checked == true) {
                $.post('/media/deletemedia', {MediaId: media_id[1], SystemMediaName: $('#SystemMediaName').val(), SiteId: $('#SiteId').val(), Type: $('#Type').val()});
                deleted++;
            }
        })
        if (deleted > 0) {
            alert("Photo(s) has been successfully deleted.")
            window.location = '/media/manage/'+$('#SiteId').val()+'/'+$('#Type').val();
            return false;
        } else {
            alert("Please select a record(s) to be deleted.")
            return false;
        }
    }

    function setPrimary(mediaID) {
        var isPrimary;
        $('#media-list tr td input[type=hidden]').each(function(){
            var id = $(this).val();
            if (mediaID == id) { isPrimary = 1 }
            else { isPrimary = 0; }
            $.post('/media/setprimary', {MediaId: id, isPrimary: isPrimary});
        });
        alert('Photo has been set as primary.');
        window.location = '/media/manage/'+$('#SiteId').val()+'/'+$('#Type').val();
    }

    function validate() {
        if (jQuery.trim($('#upload').val()) == '') {
            alert("Please select an image to upload.");
            return false;
        } else {
            var image = $('#upload').val().split(".");
            var accepted_files = new Array("jpeg", "gif", "png", "jpg", "JPG", "JPEG");
            if (!accepted_files.inArray(image[image.length-1])) {
                alert("Please select jpeg, gif and png files only.");
                return false;
            } else {
                return true;
            }
        }
    }
</script>
<style type="text/css">
    .tblHeader {
        color:#F7F7F7;
        background-color:#000;
        font-weight:bold;
    }
    .tblHeader th {
        text-align:center;
    }
    #media-list tr td {
        padding:2px;
    }
    #media-list {
        width:100%;
        border:1px solid #E7E7FF;
        border-collapse:collapse;
    }
</style>

<div>
    <div id="mainco2">
        <div class="roundedbox">
            <h2>Photo List</h2>
            <div>
                <table id="media-list" cellspacing="3" cellpadding="3" border="0">
                    <tr class="tblHeader" style="">
                        <th scope="col" style="width:20px;"></th>
                        <th scope="col" >Image</th>
                        <th scope="col" >Added By</th>
                        <th scope="col" >Date Added</th>
                        <th scope="col" style="width:90px;">Primary</th>
                    </tr>
                    <?php if (count($this->media)) :?>
                        <?php $ctr = 0; foreach($this->media as $media) { ?>
                    <tr style="background-color:<?php echo $ctr%2 == 1 ? "#e7e7e9" : "white" ?>;">
                        <td>
                            <input type="hidden" id="MediaId" name="MediaId" value="<?php echo $media['MediaId'] ?>" />
                            <input type="hidden" id="SystemMediaName" name="SystemMediaName" value="<?php echo strtolower($media['SystemMediaName']) ?>" />
                            <input id="delete_<?php echo $media['MediaId'] ?>" type="checkbox" name="delete_<?php echo $media['MediaId'] ?>" />
                        </td>
                        <td style="padding:5px;">
                            <img src="<?php echo $this->contentLocation ?>public/Media/<?php echo $media['SystemMediaName'] ?>" height="50" width="100">
                        </td>
                        <td style="text-align:center;">
                            <a href='/<?php echo $media['URLName'] ?>' target="_blank"><?php echo stripslashes($media['FirstName'])." ".stripslashes($media['LastName']) ?></a>
                        </td>
                        <td style="text-align:center;">
                            <?php echo date('Y-m-d', strtotime($media['CreatedOn'])) ?>
                        </td>
                        <td align="center">
                            <?php if ($media['isPrimary'] == 1) { ?>
                            Default
                            <?php } else { ?>
                            <a href="javascript:;" onclick="setPrimary('<?php echo $media['MediaId'] ?>')">Set as Primary</a>
                            <?php } ?>
                        </td>
                    </tr>
                        <?php $ctr++; } ?>
                    <?php else:?>
                    <tr>
                        <td colspan="6" style="font-style:italic">No record found</td>
                    </tr>
                    <?php endif;?>
                </table>
                <br/>
                <div>
                    <?php if (count($this->media)) :?>
                    <input type="button" class="btn btngreen" name="delete" value="Delete" onclick="return deletePhoto()" />
                    <?php endif;?>
                    <!--
                    <input type="button" class="btn btngreen" name="add" value="Add New" onclick="getForm('add', 0)" />
                    -->
                    <a class="btn btngreen" title="Upload" href="javascript:;" onclick="getForm('add', '<?php echo $this->SiteId ?>')">Upload</a>
                    <a class="btn btngreen" title="Back" href="/<?php echo $this->URLName ?>" >Back</a>
                </div>
                <input type="hidden" id="UserId" name="UserId" value="<?php echo $this->UserId ?>" />
                <input type="hidden" id="SiteId" name="SiteId" value="<?php echo $this->SiteId ?>" />
                <input type="hidden" id="Type" name="Type" value="<?php echo $this->Type ?>" />
            </div>
            <br/><br/><br/>
            <div id="form"></div>
            <div class="clear"></div>
        </div>
    </div>
</div>
