<?php $this->placeholder('paymentform')->captureStart() ?>
<script type="text/javascript" src="https://www.paypalobjects.com/js/external/dg.js"></script>
<script>
function generateCC() {
    var cc_number = new Array(16);
    var cc_len = 16;
    var start = 0;
    var rand_number = Math.random();
    switch(document.PaypalPayment.creditCardType.value) {
        case "Visa":
            cc_number[start++] = 4;
            break;
        case "Discover":
            cc_number[start++] = 6;
            cc_number[start++] = 0;
            cc_number[start++] = 1;
            cc_number[start++] = 1;
            break;
        case "MasterCard":
            cc_number[start++] = 5;
            cc_number[start++] = Math.floor(Math.random() * 5) + 1;
            break;
        case "Amex":
            cc_number[start++] = 3;
            cc_number[start++] = Math.round(Math.random()) ? 7 : 4 ;
            cc_len = 15;
            break;
    }
    for (var i = start; i < (cc_len - 1); i++) {
        cc_number[i] = Math.floor(Math.random() * 10);
    }
    var sum = 0;
    for (var j = 0; j < (cc_len - 1); j++) {
        var digit = cc_number[j];
        if ((j & 1) == (cc_len & 1)) digit *= 2;
        if (digit > 9) digit -= 9;
        sum += digit;
    }
    var check_digit = new Array(0, 9, 8, 7, 6, 5, 4, 3, 2, 1);
    cc_number[cc_len - 1] = check_digit[sum % 10];
    document.PaypalPayment.creditCardNumber.value = "";
    for (var k = 0; k < cc_len; k++) {
        document.PaypalPayment.creditCardNumber.value += cc_number[k];
    }
}

function validateForm2() {
    var error = '';
    var amount = $('#donationAmount').val();
    var percent = Number($('#PercentageFee').val());

    if(!($('#donationAmount').val() >= 1)) {
        error = "The amount should be greater than $1.<br>";
    }

    if(!$('#rdoName').is(':checked') && !$('#rdoVolunteer').is(':checked')) {
        error += "Please select your donation's destination.<br>";
    }
    if($('#rdoVolunteer').is(':checked') && $('#volunteers').val() == 'none') {
        error += "Please select which volunteer should receive your donation.<br>";
    }
    <?php if($this->project->allowPercentageFee == 'optional' && ($this->project->paypalId || $this->project->percentageFee)) { ?>
        if ($('#coverTransFee1').val() && $('#coverTransFee2').val()) {
            if (!$('#coverTransFee1').attr('checked') && !$('#coverTransFee2').attr('checked')) {
                error += "Please select if you want to cover the transaction fee or not.";
            }
        }
    <?php } ?>
    if (error != '') {
        $('#error').html(error).show();
        myEmbeddedPaymentFlow.closeFlow();
        return false;
    } else {
        _gaq.push(['_trackEvent', 'Initiative', 'Donate', 'Donation']);

        FB.api(
            '/me/<?php echo $this->fbAppNamespace ?>:donate?initiative=http://<?php echo $_SERVER['HTTP_HOST']; ?>/<?php echo $this->project->urlName ?>',
            'post'
        );

        alert("You are being redirected to Paypal, please fill in your credit card info there for your donations.");
        return true;
    }
}
</script>


<form action="/donation/chainedpayment" method="post" onSubmit="return validateForm2();">
    <input type="hidden" id="expType" name="expType" value="light" />
    <input type="hidden" id="ProjectId" name="ProjectId" value="<?=$this->project->id; ?>" />
    <input type="hidden" id="pURLName" name="pURLName" value="<?=$this->project->urlName; ?>" />
    <input type="hidden" id="VolunteerId" name="VolunteerId" value="<?=$this->UserId != '' ? $this->UserId : '' ?>" />
    <input type="hidden" id="PaypalEmail" name="PaypalEmail" value="<?=$this->paypal['email'] ?>" />
    <input type="hidden" id="editCartURI" name="editCartURI" value="<?=$_SERVER['REQUEST_URI'] ?>" />
    <?php if($this->project->allowPercentageFee != 'no') { ?>
    <input type="hidden" id="PercentageFee" name="PercentageFee" value="<?=$this->project->percentageFee ?>" />
    <?php } ?>
    <p style="padding-bottom:0px">Please enter any amount you wish to donate:</p>
    <p>
        <strong><?=$this->project->currency ?></strong>
        <input type="hidden" id="CurrencyCode" name="CurrencyCode" value="<?=$this->paypal['currencyCode'] ?>" />
        <input id="donationAmount" name="donationAmount" onfocus="this.style.color='black'; this.value='';" size="11" style="color:grey;" type="text" value="Enter Amount" onblur="validateDonationAmount($(this).val())" />
    </p>

    <?php if($this->project->allowPercentageFee == 'mandatory') { ?>
    <h2>Transaction Fees</h2>
    <input type="hidden" name="coverTransFee" value="1" />
    <input type="hidden" name="allowPercentageFee" value="mandatory" />
    <input type="hidden" name="PercentageFee" value="<?=$this->project->percentageFee ?>" />
    <p style="padding-bottom:0px">
        <?php if($this->project->paypalId == 211) { ?>
        Thank you for contributing an extra <?=($this->project->percentageFee + 1.5) ?>% to cover credit card and transaction costs so our communities receive the full benefit of your donation.<br />
        <?php } else { ?>
        Thank you for contributing <?=($this->project->percentageFee + 1.5) ?>% of your donation to cover the online credit card and transaction fees; this ensures 100% of your donation goes to its purpose.
        <?php } ?>
    </p>
    <span id="transfeemandatory" style="font-weight: bold; display: none">An additional amount of <?=$this->project->currency ?><span id="trans-fee"></span> will be added to your total donation to cover online transaction costs and ensure 100% of your donation is received.</span><br>
    <div class="clear"></div>

    <?php } else if($this->project->allowPercentageFee == 'optional') {  ?>

    <h2>Transaction Fees</h2>
    <input type="hidden" name="allowPercentageFee" value="optional" />
    <input type="hidden" name="PercentageFee" value="<?=$this->project->percentageFee ?>" />
    <p style="padding-bottom:0px">
        <?php if($this->project->paypalId == 211) { ?>
        Would you help us by contributing an extra <?=($this->project->percentageFee + 1.5) ?>% to cover credit card and transaction costs so our communities receive the full benefit of your donation?<br />
        <?php } else { ?>
        Thank you for contributing an extra <?=($this->project->percentageFee + 1.5) ?>% to cover any credit card and transaction costs, so 100% of your donation can go towards its purpose.<br />
        <?php } ?>
        <span><input type="radio" name="coverTransFee" value="1" checked /> Yes</span>
        <span style="margin-left: 15px"><input type="radio" name="coverTransFee" value="0" /> No</span>
        <div style="display:none;" id="feebox" class="errorBox" style="">Please reconsider making this extra contribution. These small amounts compounded over all supporters can make up nearly half of our total administrative budget. These savings help fund our supplemental community projects voted on by the Campus Chairpeople. To learn more about how Global Brigades budgets, please contact admin@globalbrigades.org. Regardless of this extra contribution, we certainly appreciate your support!</div>
        <span id="transfee" style="font-weight: bold; display: none">By selecting yes, an additional amount of <?=$this->project->currency ?><span id="trans-fee"></span> will be added to your total donation to cover online transaction costs and ensure 100% of your donation is received.</span>
        <div class="clear"></div>
    </p>
    <?php } ?>
    <h2>Comment</h2>
    <p>Leave a comment?<br />Your message will be displayed on the group's (& volunteer's) pages</p>
    <textarea name="DonationComments" rows="3" cols="70" id="DonationComments"></textarea><br><br>
    <p style="padding-bottom:0px">Please provide your name:</p>
    <p><input type="text" name="DonorsName" id="DonorsName" class="anonymousToggle" value="<?=isset($this->donorsName) ? stripslashes($this->donorsName) : ''; ?>" />
    <input type="checkbox" id="isAnonymous" name="isAnonymous" />&nbsp;Make my donation anonymous</p>
    <input id="embeddedPaypal" name="embeddedPaypal" type="image" src="/public/images/paypaldonate.jpg"/>
</form>
<script type="text/javascript" charset="utf-8">
var embeddedPPFlow = new PAYPAL.apps.DGFlow({trigger: 'embeddedPaypal'});
function get_full_url(url_path)
{
    var loc = window.location;
    var url = '' + loc.protocol + '//' + loc.host + url_path;
    return url;
}
function MyEmbeddedFlow(embeddedFlow) {
          this.embeddedPPObj = embeddedFlow;
          this.paymentSuccess = function () {
               this.embeddedPPObj.closeFlow();
               window.location.href = get_full_url('/donation/thankyou');
          };
          this.paymentCanceled = function () {
               this.embeddedPPObj.closeFlow();
               window.location.href = get_full_url('/donation/unsuccessful?ProjectId=' + '<?=$this->project->id ?>');
          };
          this.closeFlow = function () {
               this.embeddedPPObj.closeFlow();
          }
 }
 var myEmbeddedPaymentFlow = new MyEmbeddedFlow(embeddedPPFlow);
</script>

<?php $this->placeholder('paymentform')->captureEnd() ?>
