<?php
$this->headTitle("Empowered.org:  Empowering groups of volunteers to create social change");

?>
<style>
    ul {margin-left:20px}
    h3 {font-weight: bold;
        color: #144;
        font-size:130%;
    }
</style>
<div id="mainco2">
    <!-- block001 -->
    <div class="block001h01"><div class="blst001"><div class="blst002"></div></div></div>
    <div class="block001">
        <div class="blst001">
            <div class="blst002 hsp">
	     <h2 style="color:#693;">Global Brigades Cancellation and Refunds Policy</h2>
         <p>Global Brigades understands that sometimes a volunteer can no longer participate on a service program as planned, and upon cancellation, a donor may wish to withdraw support from the organization. By the IRS rule (Pub. 526) or country equivalent, all un-dispensed donations are refundable at the request and consent of the original donor to the original donor, with the understanding that the returned portion of the donation is no longer tax deductible, and the already issued tax receipt must be discarded.</p>
         <p>If you are cancelling your brigade and/or you want to ask for a transfer or refund, please read the full policy and FAQ section before submitting your request.</p>
         <h3 id="toc1"><span>Non-Refundable Initial Pledge</span></h3>
         <p>A volunteer may withdraw from a volunteer activity, but the initial pledge of $250, or country equivalent, for all participants is non-refundable<sup>1</sup> and non-transferable<sup>1</sup> in order for the Honduran, Ghanaian, and Panamanian team members to secure commitments with community leaders and finalize project plans. Any brigade cancellations can affect the relationships with communities that are expecting services. To mitigate those risks, the initial pledges are granted out as soon as they are become fully committed.</p>
         <p>Your understanding is much appreciated. The initial deposit is subject to your tax advisor's discretion as to whether it is tax deductible.</p>
         <p><strong><sup>1</sup>Exceptions can be made for the following, upon request by the volunteer:</strong></p>
         <ul>
         <li>If the canceling volunteer finds a replacement volunteer, his/her initial pledge can be transferred to the replacement. The refund is contingent upon any obligations to the airlines, if applicable.</li>
         <li>If a chapter has met all brigade size requirements and a cancellation is initiated by Global Brigades, volunteers have 10 days from the notification to request a refund or transfer of their initial pledge.</li>
         <li>In the event of an emergency situation with approval from the Program Advisor, a refund can be requested. See the list of emergencies in the FAQ section.</li>
         <li>If a cancellation is initiated by the Global Brigades chapter, volunteers have 10 days from the notification to request a transfer of their initial pledge.</li>
         <li>If the group has not been ticketed and it's more than 40 days before the scheduled brigade, the initial pledge is not considered to be fully committed, therefore it is refundable to the original donor upon request, can be transferred to another volunteer, or to the Global Brigades chapter. Any deposits to the airlines will be deducted from the amount refunded or transferred.</li>
         <li>As courtesy, if a non US citizen followed all procedures in a timely and proper manner did not receive his/her visa in time.</li>
         <li>As courtesy, if a professional participant must cancel.</li>
         </ul>
         <h3 id="toc2"><span>Requests After Ticketing and Securing Airfare</span></h3>
         <p>If a volunteer withdraws from the scheduled brigade after the Global Brigades chapter has secured its airfare, the volunteer would have to request a refund from the Global Brigades’ travel partner. Any refund on committed airfare is granted by and at the discretion of the airlines, and Global Brigades cannot make any guarantee of a refund. For all additional donations beyond the initial pledge and airfare, the Cancellation and Refund policy applies. See additional information about ticket cancellations on the <a href="http://globalbrigades.wikidot.com/travel:policies">Travel page</a>.</p>
         <h3 id="toc3"><span>Requests After the Scheduled Brigade</span></h3>
         <p>Cancellations will not be accepted and no refunds will be issued after the scheduled brigade begins.</p>
         <h3 id="toc4"><span>Donations Received Beyond Goal</span></h3>
         <p>Donations collected beyond the volunteer’s specific goal can not be refunded without a cancellation. Additional funds can be transferred to the Global Brigades chapter for a current or future brigade, to the volunteer for another brigade, or to the Global Brigades' program of the volunteer’s choice. Such requests must be submitted no later than two weeks after the brigade. Please contact <a href="mailto:accounting@globalbrigades.org" class="wiki-email">accounting@globalbrigades.org</a> with this request. Unclaimed donations will become donations to Global Brigades.</p>
         <p>Global Brigades will use all additional donations to support the beneficiaries in accordance with its mission statement and will demonstrate accountability to donors in publishing an annual audit from an independent accounting firm.</p>
         <h3 id="toc5"><span>Donations Transferred Between Volunteers</span></h3>
         <p>Any donation that is otherwise eligible for transfer can be transferred to another volunteer or brigade at the volunteer’s request and without the consent of the original donor.</p>
         <h3 id="toc6"><span>Matching Donations</span></h3>
         <p>A special rule applies for matching donations received from participating corporations. Such donations and their matching counterparts can only be refunded with the approval and by the rules of the company in question, and therefore must be handled on a case-by-case basis. Please contact <a href="mailto:accounting@globalbrigades.org" class="wiki-email">accounting@globalbrigades.org</a>.</p>
         <h3 id="toc7"><span>Credit Card Transaction Costs</span></h3>
         <p>For any refund, a 3.5&#160;% merchant recovery fee is calculated for the refunded portion of the donation to offset the credit card charges that applied on the original transaction.</p>
         <h2 style="border:none;" id="toc8"><span>Process for Cancellation, Refund, or Transfer</span></h2>
         <p>All cancellation, refund or transfer requests should be made as soon as possible to the <strong>chapter president and the Program Advisor</strong> in order to inform the Global Brigades travel partner and Global Brigades Accounting. The Global Brigades travel partner will contact the airline and request a cancellation and refund, if applicable.</p>
         <p>To report a donation error, <strong><em>please do not call your credit card provider</em></strong>, but notify Global Brigades’ Accounting at <a href="mailto:accounting@globalbrigades.org" class="wiki-email">accounting@globalbrigades.org</a> immediately.</p>
         <p>To request a cancellation, refund, or transfer, please contact a Program Advisor with the following information:</p>
         <ul>
         <li>Name and contact information (e-mail address and/or phone number) of the volunteer and chapter president.</li>
         <li>Name of the Global Brigades chapter.</li>
         <li>Date of scheduled brigade and detailed ticketing information (cost, contribution deadline).</li>
         <li>Amount to be refunded or transferred in accordance with the Cancellation and Refund Policy.</li>
         </ul>
         <p>After all the necessary information is submitted and the request has been processed, the donor or volunteer will be contacted by Global Brigades Accounting with a resolution.</p>
         <h2 style="border:none;" id="toc9"><span>Frequently Asked Questions</span></h2>
         <p><em><strong>My donor made his/her donation to the chapter, can you transfer it to my page?</strong></em></p>
         <ul>
         <li>Yes, that is a simple procedure if you are signed up as a volunteer. But you must have your donation page set up on Empowered.org to complete the transfer.</li>
         </ul>
         <p><em><strong>My donor accidentally donated (twice)/(the incorrect amount); can he/she get (one)/(the difference) back?</strong></em></p>
         <ul>
         <li>Yes, if it is reported within 48 hours of the event.</li>
         </ul>
         <p><em><strong>My donor used the wrong credit card; can you cancel the donation?</strong></em></p>
         <ul>
         <li>Yes, if it is reported within 48 hours of the event</li>
         </ul>
         <p><em><strong>My donor used the wrong name to donate, can you change the name on the donation?</strong></em></p>
         <ul>
         <li>No we can’t. The donation must be cancelled, and a new donation for the desired name should be made. If the request is within 48 hours, there will be no charge for this cancellation. If it falls beyond this time frame, the 3.5% merchant service fee deduction is applied.</li>
         </ul>
         <p><em><strong>What is the 3.5% merchant service fee (MSF)?</strong></em></p>
         <ul>
         <li>All credit card transactions are conducted by a Merchant Service Provider. For Global Brigades, the MSP is Google/Empowered. Global Brigades pays fee for this service. When we issue a refund, we deduct the fee from the refund.</li>
         </ul>
         <p><em><strong>If I am cancelling my brigade, can I receive a refund?</strong></em></p>
         <ul>
         <li>Yes, by the IRS rule (Pub. 526) and by the design of Global Brigades’ Cancellation and Refund Policy, the original donors can ask for a refund. If you were an original donor, you may ask for a refund. Please refer to the complete Cancellation and Refund Policy for more details.</li>
         </ul>
         <p><em><strong>What amount of my donation can I receive in a refund?</strong></em></p>
         <ul>
         <li>Depending on the time of the cancellation with respect to your scheduled participation, a refund is available to the extent of the donation that was not yet dispensed in your behalf (airfare, share of collective supply purchase, etc.). The 3.5% MSF deduction is applied to all refunds of donations. Please read the Cancellation and Refund Policy for the applicable rules outlined for the timeframes, restrictions, and exceptions.</li>
         </ul>
         <p><strong><em>How will I get my refund?</em></strong></p>
         <ul>
         <li>The refund of a donation, unless you were your own donor, must be requested by the original donor. The refund will be issued by the same means as it was received. Please give a notice if the credit card used is no longer valid or is compromised.</li>
         </ul>
         <p><strong><em>If I am cancelling my brigade, but I already got my ticket, what will happen to that ticket? Am I getting a refund for that too?</em></strong></p>
         <ul>
         <li>Refunds on tickets are issued at the discretion of the airlines. If the cancellation was promptly reported to the Travel Lead, an attempt to recover as much value of the ticket as possible will be made.</li>
         </ul>
         <p><strong><em>I am cancelling my brigade and by reading the Cancellation and Refund Policy I am eligible for a partial refund of my total donations. I have different donors, which donation will be refunded?</em></strong></p>
         <ul>
         <li>This decision has to be made by you. You may wish to consult with your donors.</li>
         </ul>
         <p><strong><em>If I am cancelling my brigade, can I transfer my initial pledge to another brigader/group?</em></strong></p>
         <ul>
         <li>This transfer is not possible unless you are eligible to make the transfer under one of the exceptions listed in the Cancellation and Refund Policy.</li>
         </ul>
         <p><strong><em>Since I am cancelling my brigade, can I receive refunds for all of my donations?</em></strong></p>
         <ul>
         <li>By the IRS rule (Pub. 526) donations can be refunded only to the original donors. You can only be refunded donations that you contributed. All other donations are refunded to the original donor and can no longer be claimed as tax-deductible. Requests should be made to <a href="mailto:accounting@globalbrigades.org" class="wiki-email">accounting@globalbrigades.org</a>.</li>
         </ul>
         <p><strong><em>I am cancelling my brigade. I understand that my initial pledge is non-refundable, but can I give my additional donations to another brigader or to my group?</em></strong></p>
         <ul>
         <li>Yes, all donations that would be available for refund can be transferred to any brigader or group, including yourself for a later brigade, excluding the MSF deduction.</li>
         </ul>
         <p><strong><em>I am cancelling my brigade because&#8230;. Can I have my donations refunded?</em></strong></p>
         <ul>
         <li>If you believe that you have an exception not stated in the Cancellation and Refund Policy, please contact your program advisor.</li>
         </ul>
         <p><strong><em>If I received an additional donation last minute from a friend/relative, can I have my donation refunded?</em></strong></p>
         <ul>
         <li>Donations collected beyond the volunteer’s specific goal cannot be refunded, but can be transferred to the chapter, to any brigader, to the volunteer for a later use, or to be donated to a special project of the volunteer’s choice. Such request must be submitted no later then 2 weeks after the brigade.</li>
         </ul>
         <p><strong><em>We (the brigade group)/I have more donations than our brigade participation goal, can we use those extra funds to purchase supplies?</em></strong></p>
         <ul>
         <li>Yes, legitimate purchases with a receipt are eligible for dispensation or reimbursement. The 3.5% MSF deduction applies. Reimbursement for such purchases will be limited to the actual amount of the items, or the additional funds on Empowered beyond the group's funds required for brigade participation, whichever is the lesser amount. <em>See below for a definition of legitimate purchases.</em></li>
         </ul>
         <p><strong><em>What are considered legitimate purchases?</em></strong></p>
         <ul>
         <li>Any supplies or medications that are used on the brigade, or are used to help fundraise for such items fall under this category. Legitimate purchases must benefit the entire group, and be approved by the chapter's Program Advisor in order to qualify for reimbursement. Expenditures that are to enhance individual fundraising, or to be spent on individual needs - such as obtaining visa or shots - are not considered legitimate purchases.</li>
         </ul>
         <p><strong><em>I am expecting a matching donation, but my donation schedule to get my ticket is coming up very soon. If I put my fund in as a donation, can I get that back when the matching donation received?</em></strong></p>
         <ul>
         <li>Please contact <a href="mailto:accounting@globalbrigades.org" class="wiki-email">accounting@globalbrigades.org</a> before you place your donation to see if another option is available to hold you over.</li>
         </ul>
         <p><em><strong>I am a non US citizen and did not receive my visa before my scheduled brigade, can I receive a refund?</strong></em></p>
         <ul>
         <li>A refund can be made as a courtesy if the volunteer followed all procedures in a timely and proper manner.</li>
         </ul>
         <p><em><strong>I am a professional (physician, nurse, educator, engineer, parent etc.) and my work schedule has changed, can I receive a refund?</strong></em></p>
         <ul>
         <li>A refund can be made as a courtesy.</li>
         </ul>
         <p><strong><em>Can I use my additional donations to get my passport/visa/shots etc?</em></strong></p>
         <ul>
         <li>No, those are personal expenditures, even if they are necessary to participate. If you expect to have such needs, you may ask one of your donors to give you a personal gift instead of a donation on your behalf. However, your donor must understand that a gift to you is not a tax deductible donation.</li>
         </ul>
         <p><strong><em>Can we (group)/I have a refund for the additional suitcase charges from the airline when we transported our medication?</em></strong></p>
         <ul>
         <li>Yes, to the extent of the additional funds -3.5%, and the receipt from the airline must be submitted to the Global Brigades Accounting department.</li>
         </ul>
         <p><strong><em>I signed up for two brigades/I signed up for the wrong brigade, can I have my deposit and other donations transferred to my proper Empowered.org brigade?</em></strong></p>
         <ul>
         <li>Yes, you may have any or all donations that you have collected transferred between your accounts.</li>
         </ul>
         <p><strong><em>I am a president and I was granted scholarship, but I already collected my full/partial pledge. Can I get a refund?</em></strong></p>
         <ul>
         <li>No, your collected donations are non-refundable without cancellation. But you may chose to share your additional funds with a fellow brigader, keep it for a later brigade for yourself, use it in behalf of the chapter for supply/medication purchases, or donate to any of our special projects.</li>
         </ul>
         <p><strong><em>I/we (group) will get our tickets independently, how many donations will we need to collect on Empowered?</em></strong></p>
         <ul>
         <li>Your goal will be $250 initial deposit and the additional $500/$570/$630/etc., depending on your destination. The goal must be collected by no later than 14 days before the scheduled brigade. Please remember, even if you get your tickets independently, you must submit your itineraries and Alternative Transportation Waivers to your program advisor.</li>
         </ul>
         <p><strong><em>I have more donations than my goal, and we are getting our tickets from another agent. Can I use my additional donations to pay for the ticket?</em></strong></p>
         <ul>
         <li>Not directly, but here are some options:
         <ul>
         <li>Ask one your peers to transfer some of your donations to them, and in exchange they can help you out with your ticket.</li>
         <li>Ask one/more of your donors, that placed the donation for you on Empowered - anticipating that a ticket will be purchased for you - to ask for a refund of their donation, and give you personal a check instead. The Accounting department will permit this if explained, but the 3.5% MSF deduction will be applied. Keep it in mind that neither the returned donation nor the check that is given to you are eligible for tax deduction.</li>
         </ul>
         </li>
         </ul>
         <p><strong><em>I really want to go on a brigade, but I can not collect enough donations. Can I go anyway?</em></strong></p>
         <ul>
         <li>Global Brigades does not have the resources to support a specific individual with fairness to all other students. Establishing a need-based scholarship is among our future projects. In the meantime, you may seek advice from your peers on how to successfully fundraise. Some funds may be available for you from your school. Please explore these options!</li>
         </ul>
         <p><strong><em>Ok, so I can’t go on the brigade, can I receive a refund of my donations?</em></strong></p>
         <ul>
         <li>If you cancel, some of your donations maybe available for refund following Global Brigades’ Cancellation and Refund Policy.</li>
         </ul>
         <p><strong><em>I joined my group late/did not go at the last minute/departed early, can I have a refund for my program contributions?</em></strong></p>
         <ul>
         <li>No, if the alternative time spent on the brigade was due to any negligence or wrongdoing on your part, such as expired passport, late arrival to the meeting point, inappropriate behavior, etc.</li>
         <li>Yes, if it was due to an unforeseen medical condition/injury or it was a consequence of any wrongdoing or mistake of Global Brigades.</li>
         </ul>
         <p><strong><em>Our group was delayed at the airport and we arrived late and/or had to go into a hotel, etc. Can we/I get any refund for the time we missed on the brigade?</em></strong></p>
         <ul>
         <li>Under such circumstances, a decision will be made on the case-to-case basis. Please keep all receipts of additional expenses in case reimbursement becomes available. Your program advisor and travel lead will be in touch with all who were affected.</li>
         </ul>
         <p><em><strong>What is the fully committed pledge?</strong></em></p>
         <ul>
         <li>The initial pledge becomes fully committed 40 days before the scheduled brigade, or at the time when the brigade is engaged for airfare; whichever comes first.</li>
         </ul>
         <p><em><strong>What is considered an emergency?</strong></em></p>
         <ul>
         <li>A sudden illness, injury, accident that is verified by a physician and an unexpected death of a parent, child or spouse. Anyone in these sad predicaments may be also eligible to receive refund from the airlines.</li>
         </ul>
         <hr />
         <p><em><strong>Last Updated on December 5, 2011</strong><br />
         “Global Brigades” refers to one or more of Global Brigades Association, “Global Brigades USA,” “Global Brigades ASG,” “Global Brigades Ireland,” or “Global Brigades UK.” Each of &quot;Global Brigades Association&quot; “Global Brigades USA,” “Global Brigades ASG,” “Global Brigades Ireland,” “Global Brigades UK,” “Asociacion Global Brigadas de Honduras,” Fundacion Brigadas Globales de Panama,” are separate and independent legal entities.</em></p>            </div>
        </div>
    </div>
    <div class="block001f01"><div class="blst001"><div class="blst002"></div></div></div>
    <!-- e o block001 -->
</div>
