<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
$this->placeholder('tab')->set('');
?>
<link href="<?php echo $this->contentLocation ?>public/css/style2.css" rel="stylesheet" type="text/css" />
<style>
    .TextBox { border: none; width: 740px }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px;">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
				<?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC"><span class="Heading01">Increase Efficiency</span>
                <div class="clr"></div>
                <div class="TextBox">

                    <div class="donation">
                        <div class="title">Donations Straight To Your Bank</div>
                        <div class="cont">No waiting for a donation from us, as funds are directed right into your merchant
						account, making it faster and more secure to raise money online.</div>
                    </div>
                    <div class="donor">
                        <div class="title">Simple Donor Management</div>
                        <div class="cont">Detailed reports on donors and donations, sorted by who raised the donation and for
						which activity, program and group.</div>
                        </a></div>
                    <div class="admin">
                        <div class="title">Flexible Admin Control</div>
                        <div class="cont">Organizations can set admin rights at nearly every level of the site with a highly
						developed admin panel for reporting.</div>
                    </div>
                    <div class="dynamic">
                        <div class="title">Dynamic Group
                            Creation and Volunteer
                            Registration</div>
                        <div class="cont">Save hundreds of hours of administrative time manually creating volunteer activities and
							registering groups and volunteers. Coordinate all your chapters on one platform.</div>
                    </div>
                    <div class="comn">
                        <div class="title">Internal Communication
                            Made Easy</div>
                        <div class="cont">Send messages and alerts to the people that matter to your group, improving efficiency
							and productivity and saving you time.</div>
                    </div>
                    <div class="sharing">
                        <div class="title">File Sharing</div>
                        <div class="cont">Sharing important files like project portfolios, marketing documents and other group
						resources keeps everyone in your group updated with new materials and strategies.</div>
                    </div>
                    <div class="liability">
                        <div class="title">Safe and Secure</div><div class="cont">We adhere to the strict standards and security policies of our processors, ensuring the
							security of your donor and member information.</div>
                    </div>
                    <div class="safe">
                        <div class="title">Liability Waivers
                        </div>
                        <div class="cont">Save time and money by automating electronic waivers that volunteers must sign before
						participating in activities, all under generally accepted legal requirements.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
