<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
$this->placeholder('tab')->set('');
?>
<link href="<?php echo $this->contentLocation ?>public/css/style2.css" rel="stylesheet" type="text/css" />
<style>
    .BenefitBox { border: none; width: 740px }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px;">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
				<?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC"><span class="Heading01">Grow</span>
                <div class="clr"></div>
                <div class="BenefitBox">
                    <div class="open"> 
                        <div class="title">Open to All</div>
                        <div class="cont"> Empowered is open to any group or organization that wants to create social change in more than 190 
                            countries, regardless of charitable status.</div>
                    </div>
                    <div class="pers"> 
                        <div class="title">Personalized Fundraising Pages</div>
                        <div class="cont"> 
                            Fundraising pages for you members to customize
                            and collect support from friends and family, all 
                            connected to your programs, volunteer activities, 
                            events or campaigns.</div>
                        </a></div>
                    <div class="demons"> 
                        <div class="title">Demonstrating Impact (Past and Present)</div>
                        <div class="cont"> Show all your group content, photos, fundraising
                            amounts and accomplishments across all your
                            chapters while uniquely being able to show all
                            PAST activities as well as upcoming activities.</div>
                    </div>
                    <div class="stru"> 
                        <div class="title">Provide Structure To Grow Chapters</div>
                        <div class="cont"> Connect all your current groups to your organization
                            and easily add new groups as the form. Read more
                            about this strategy in the “Why We Are Different”
                            section.</div>
                    </div>
                    <div class="reln"> 
                        <div class="title">Customer Relationship Management </div>
                        <div class="cont"> Pull data into your current CRM or directly
                            communicate to specific members, group leaders
                            and donors on the platform with the ability to segment
                            across activities, programs or groups. Automate
                            thank you notes to donors, reminders for 
                            volunteers and more.</div>
                    </div>
                    <div class="survey"> 
                        <div class="title">Surveys</div>
                        <div class="cont">Send out targeted surveys to your supporters and 
                            members to collect feedback to improve your 
                            programming and involve your constituents.</div>
                    </div>
                    <div class="network"> 
                        <div class="title">Share Your Entire 
                            Network’s Pictures,
                            Videos and Blogs
                        </div><div class="cont">
                            All of your chapters and members under one roof,
                            sharing photos, videos and content around 
                            your programs.</div>
                    </div>
                    <div class="social"> 
                        <div class="title">Social Media</div>
                        <div class="cont"> Take full advantage of integrating with your
                            Facebook and Twitter accounts to virally spread
                            your message to donors and your members around
                            the world.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
