<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
$this->placeholder('tab')->set('');
?>
<link href="<?php echo $this->contentLocation ?>public/css/style2.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->contentLocation ?>public/css/layout.css" rel="stylesheet" type="text/css" />
<style>
    .TextBox { border: none; width: 740px }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px;">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
				<?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC" style="color:#000;">
                <span class="Heading01">Pricing</span>
                <span class="Heading02">Two Options for Organizations of All Kinds.</span>
                <div class="clear"></div>
                
                <p style="line-height:18px; font-size:15px;">
                    <strong>1) Custom Solution Integrated Into Your Existing Website:</strong>
                    <br /><br />
                    Are you looking to optimize your web presence, maximize efficiency, and scale your impact? Empowered.org works with <strong>select</strong> organizations to do exactly that, offering complete and comprehensive online solutions tailored to meet your organization’s goals. This includes:
                    <br /><br />
                    -Website Integration: Our developers and consultants work with you to integrate powerful coordination and fundraising tools (including member/volunteer coordination, chapter listings, volunteer activities, programs, events, fundraising campaigns and more) into your existing web site.
                    <br /><br />
                    - Website Redesign: change the look and feel of your website to best incorporate your new online tools.
                    <br /><br />
                    -Website Maintenance and Hosting: Save on IT costs with Empowered by letting us maintain and host your existing site and utilizing our 24/7 support team; use analytics to track and analyze your strengths and areas for improvement online.
                    <br /><br />
                    -Facebook Integration: Every time someone donates, becomes a member, registers for an event or otherwise engages with your organization, their <strong>Facebook</strong> profile will update spreading the word to all their “friends." Raise more support and awareness and watch your mission go viral.
                    <br /><br />
                    Cost: <strong>$2,900</strong> (one time set up) + <strong>$500</strong>/month for website hosting and maintenance + *3.9% flat fee on credit card transactions with Empowered's merchant processing solution. *The 3.9% can be passed onto donors.
                    <br /><br />
                    
                    <strong>2) Unmatched Value: The Customizable Open Platform</strong>
                    <br /><br />
                    Beyond having the most tools around mobilizing your supporters and members, we developed a pricing model to allow for organization to receive 100% of donations processed with credit fees passed onto donors.
                    <br /><br />
                    <strong>No set up fees, no monthly costs, 1.5% per transaction for Empowered + Paypal Fee (all can be passed to donors).</strong>
                </p>
                <br /><br />
    			<div class="info-boxes" style="margin-left:0; width:680px; line-height:16px;color:#000;">
    				<strong style="font-size:14px;">How it works:</strong><br />
    				<div class="details" style="color:#000;">
    					&bull; When initially setting up your fundraising settings, you select the percentage to cover your organization's transactions costs (suggested between 3-5%) and decide whether it is 'Mandatory' or 'Optional' to have donors cover those costs.
    				</div>
    				<div class="details" style="color:#000;">
    					&bull; For 'Mandatory': in addition to the initial donation, the organization's transaction fees are automatically covered by the donor (ex: for a $100 donation and 4% transaction costs, the donor pays $104 in total).
    				</div>
                    
    				<div class="details" style="color:#000;">
    					&bull; For 'Optional': the donor is allowed to choose to cover transaction costs or not; if the donor chooses to OPT OUT, the organization is charged for merchant (i.e. credit card) processing and Empowered's 1.5% is waived (ex: the $100 donation is intact, the organization pays roughly $2-3 to cover merchant processing costs and Empowered receives $0).
    				</div>
    				<div class="details" style="color:#000;">
    					Notes: The donor is made aware of the total contribution in both the checkout process and via email receipt; all money fundraised on Empowered goes directly to your PayPal account (minus transaction fees) to ensure a safe and secure transaction.
    				</div>
    			</div>
                <div class="clear"></div>
                <br /><br />
                <p style="line-height:18px; font-size:15px;">
                    Not a fan of PayPal? No problem – please contact us and we will work out a solution.
                </p>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
