<?php
$this->headTitle("Empowered.org : world's largest student-led global health and sustainable development organization");
$this->placeholder('tab')->set('');
?>
<link href="<?php echo $this->contentLocation ?>public/css/style2.css" rel="stylesheet" type="text/css" />
<style>
    .TextBox { border: none; width: 740px }
    #footermenu a, #copyrights { font-size: 11px }
    #copyrights span { margin-top: -5px }
</style>
<div class="container" style="margin-top: -10px;">
    <div class="MainBody">
        <div class="MainBodyTop"></div>
        <div class="MainBodyContents">
            <div class="leftC" style="margin-right: 40px">
				<?php echo $this->placeholder('left_tour_nav'); ?>
            </div>
            <div class="rightC"><span class="Heading01">Save</span>
                <div class="clr"></div>
                <div class="TextBox">
                    <div class="unqn"> 
                        <div class="title">Unquestionable Value</div>
                        <div class="cont">Unlimited access to the site with no start up costs 
                            and no fee (through Google Checkout) or 1.5% (through Paypal) of any donations raised (in addition 
                            to any standard credit card processing rates from 
                            your processor). </div>
                    </div>
                    <div class="cost"> 
                        <div class="title">Passing Costs 
                            onto Donors
                        </div>
                        <div class="cont"> 
                            By August 2011, all fees, including merchant fees may be passed to donors during checkout instead of as an additional coast to participating organizations.</div>
                        </a></div>
                    <div class="shop"> 
                        <div class="title">A One Stop Shop</div>
                        <div class="cont">A single online platform for all your fundraising campaigns, volunteer activities and events reduces coordination time and saves money from being used to purchase multiple systems.</div>
                    </div>
                    <div class="account"> 
                        <div class="title">Better Accounting and Transparency</div>
                        <div class="cont">Since all donations go directly into your account
                            without an additional middleman, reconciliations
                            become easier and keeping track of every donation
                            related to a specific member or initiative is 
                            transparent.</div>
                    </div>
                    <div class="mprocessing"> 
                        <div class="title">Multiple Processing Options Direct to Your 
                            Bank Account
                        </div>
                        <div class="cont">
                            Empowered currently supports, but is not limited to:
                            Google Checkout, Paypal, and AlertPay to give you 
                            many options to collect funds.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
